go.mod, go.sum, internal/buf/bufos/image_writer.go, internal/buf/cmd/internal/cmdtesting/cmdtesting_test.go, internal/pkg/cli/cliproto/cliproto.go, internal/pkg/util/utilproto/utilproto.go, internal/pkg/util/utilproto/utilprototesting/utilprototesting.go
=> Deterministically marshal messages and update to latest protoreflect

internal/pkg/storage/storagepath/storagepath.go
Fixes https://github.com/bufbuild/buf/issues/51
=> Only check if paths starts with ../ for NormalizeAndValidate

go.mod, go.sum, internal/buf/bufbuild/normalize.go, internal/buf/bufbuild/normalize_test.go, internal/buf/cmd/buf/buf.go, internal/pkg/storage/storagemem/bucket.go, internal/pkg/storage/storagepath/storagepath.go
=> Properly check if one path is equal to or contains another path

.github/workflows/ci.yaml
Windows commented out for now.
=> Update GitHub Actions to use both linux and mac

go.mod, go.sum, internal/buf/cmd/buf/buf.go, make/buf/base.mk
=> Fix panic in parser

go.mod, go.sum, make/buf/base.mk
=> Unpin golang.org/x/sys and upgrade spf13/cobra

go.mod, go.sum, internal/buf/buffetch/internal/git_ref.go, internal/buf/buffetch/internal/internal.go, internal/buf/buffetch/internal/reader.go, internal/buf/buffetch/ref_parser_test.go, internal/pkg/git/cloner.go
=> Add git protocol handling

internal/buf/bufcheck/bufbreaking/internal/bufbreakingcheck/bufbreakingcheck.go, internal/buf/bufcheck/bufbreaking/testdata/breaking_enum_value_same_name/1.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_enum_value_same_name/1.proto, internal/pkg/stringutil/stringutil.go, internal/pkg/stringutil/stringutil_test.go
Fixes https://github.com/bufbuild/buf/issues/195.
=> Check that new enum value names are a superset of old names instead of equal in ENUM_VALUE_SAME_NAME

go.mod, go.sum, internal/buf/bufcore/bufmodule/external_lock_file.go, internal/buf/bufcore/bufmodule/validate.go, internal/pkg/netextended/netextended.go, internal/pkg/netextended/netextended_test.go, internal/pkg/storage/storageos/bucket.go
=> Continue walk on broken symlinks

internal/buf/bufgen/config.go, internal/buf/bufgen/config_test.go, internal/buf/bufgen/testdata/gen_success3.json, internal/buf/bufgen/testdata/gen_success3.yaml
=> Fix incorrect unmarshalling of buf.gen.yaml options

.github/workflows/ci.yaml, data/buf/template/buf.go.gen.yaml, go.mod, go.sum, internal/buf/bufcore/bufmodule/bufmodule.go, internal/buf/bufcore/bufmodule/bufmoduletesting/bufmoduletesting.go, internal/buf/bufcore/bufmodule/module_reference.go, internal/buf/bufcore/bufmodule/module_reference_test.go, internal/buf/bufcore/bufmodule/util.go, internal/buf/bufcore/bufmodule/validate.go, internal/buf/buffetch/ref_parser_test.go, make/buf/base.mk, proto/buf.yaml
- Move `buf.yaml` to `proto/buf.yaml`.
- Move `buf.gen.yaml` to `data/buf/template/buf.go.gen.yaml`.
- Work on `bufmodule`.
=> Sync from internal

go.mod, go.sum, internal/pkg/github/githubtesting/archive_reader.go, make/buf/all.mk
Fixes https://github.com/bufbuild/buf/issues/314 again
=> Upgrade protoreflect version and increase testing file lock

go.mod, go.sum, internal/buf/bufcheck/bufbreaking/testdata/breaking_enum_value_no_delete/2.proto, internal/buf/bufcheck/bufbreaking/testdata/breaking_enum_value_no_delete_unless_name_reserved/2.proto, internal/buf/bufcheck/bufbreaking/testdata/breaking_enum_value_no_delete_unless_number_reserved/2.proto, internal/buf/bufcheck/bufbreaking/testdata/breaking_enum_value_same_name/2.proto, internal/buf/bufcheck/bufbreaking/testdata/breaking_reserved_enum_no_delete/2.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_enum_value_no_delete/2.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_enum_value_no_delete_unless_name_reserved/2.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_enum_value_no_delete_unless_number_reserved/2.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_enum_value_same_name/2.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_reserved_enum_no_delete/2.proto, internal/buf/bufcheck/buflint/testdata/ignores1/buf/bar/bar2.proto, internal/buf/bufcheck/buflint/testdata/ignores2/buf/bar/bar2.proto, internal/buf/bufcheck/buflint/testdata/ignores3/buf/bar/bar2.proto, internal/buf/cmd/protoc-gen-buf-breaking/breaking.go, internal/buf/cmd/protoc-gen-buf-lint/lint.go, make/buf/all.mk
Re: https://github.com/jhump/protoreflect/issues/400
=> Fix enum c++ scoping issue

internal/buf/bufcheck/bufbreaking/bufbreaking_test.go, internal/buf/bufcheck/bufbreaking/internal/bufbreakingcheck/bufbreakingcheck.go, internal/buf/bufcheck/bufbreaking/internal/bufbreakingcheck/util.go, internal/buf/bufcheck/bufbreaking/testdata/breaking_file_no_delete_ignores/a/b/a_b.proto, internal/buf/bufcheck/bufbreaking/testdata/breaking_file_no_delete_ignores/buf.yaml, internal/buf/bufcheck/bufbreaking/testdata/breaking_file_no_delete_ignores/sub/a/b/sub_a_b.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_file_no_delete_ignores/buf.yaml, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_file_no_delete_ignores/root/a/a.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_file_no_delete_ignores/root/a/b/a_b.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_file_no_delete_ignores/root/a/c/c.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_file_no_delete_ignores/root/no_package.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_file_no_delete_ignores/root/sub/a/b/sub_a_b.proto, internal/buf/bufcheck/internal/helper.go, internal/buf/bufcheck/internal/rule.go, internal/buf/bufcheck/internal/runner.go
=> Use previous protosource.Descriptors as part of ignore calculation for FILE_NO_DELETE and PACKAGE_NO_DELETE

go.mod, go.sum, internal/buf/cmd/buf/command/protoc/const_unix.go, internal/buf/cmd/buf/command/protoc/const_windows.go, internal/buf/cmd/buf/command/protoc/flags.go, internal/buf/cmd/buf/command/protoc/flags_test.go
=> Split protoc include directory paths by separator

internal/pkg/app/appproto/appprotoexec/protoc_proxy_handler.go
This issue arises for `buf generate ...` in Windows when you're using one of the built in plugins to protoc (i.e. js, csharp, etc).
The protoc_proxy_handler normally uses stdin to pass the descriptor set to the protoc command however on Windows because there is no stdin file, I had to use a temporary file instead.
Since our test cases for Windows don't yet pass, I'm not sure how to show that this PR actually works. I can tell you I've tested on my windows machine and I'm able to run `buf generate ...` now when it includes one of the standard plugins.
=> Fix windows generation of protoc default plugins

.github/workflows/codeql.yaml
https://github.com/github/codeql-action/issues/572
=> Fix CodeQL permissions

.github/workflows/codeql.yaml, go.mod, go.sum, make/buf/all.mk, make/go/go.mk
=> Turn off codeql on PRs and cron

go.mod, go.sum, internal/buf/bufcheck/bufbreaking/bufbreaking_test.go, internal/buf/bufcheck/bufbreaking/internal/bufbreakingcheck/bufbreakingcheck.go, internal/buf/bufcheck/bufbreaking/testdata/breaking_ignore_unstable_packages_delete_file/a/v1beta1/a.proto, internal/buf/bufcheck/bufbreaking/testdata/breaking_ignore_unstable_packages_delete_file/buf.yaml, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_ignore_unstable_packages_delete_file/a/v1beta1/a.proto, internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_ignore_unstable_packages_delete_file/a/v1beta1/b.proto, make/buf/scripts/release.bash
=> Properly ignore deleted enums, messages, and services in unstable packages if their corresponding file is deleted

make/buf/scripts/release.bash
This adds Windows builds to the release process.
=> Add Windows build to the `buf` release script

private/buf/bufcli/bufcli.go
Fixes https://github.com/bufbuild/buf/issues/454
We only need to support `BUF_TOKEN`, not `BUF_USERNAME`. The new logic:
- Check for `BUF_TOKEN`. If it exists, use it for all RPCs.
- Otherwise, check the netrc file. If an entry exists for  the address, use it for all RPCs.
- Otherwise, do not authenticate.
=> Support BUF_TOKEN for authentication

private/buf/bufconfig/provider.go, private/buf/bufgen/config.go, private/buf/cmd/buf/buf_test.go, private/buf/cmd/buf/workspace_test.go, private/buf/cmd/protoc-gen-buf-lint/lint_test.go
This is one of the few breaking changes we must make before v1.
=> Error if no version set for buf.yaml and change error messages to use v1

private/pkg/app/appproto/generator.go, private/pkg/bandeps/checker.go, private/pkg/storage/copy.go, private/pkg/thread/thread.go
Adds `thread.ParallelizeWithMultiplier` and `thead.ParallelizeWithCancel`.
=> Expand thread.Parallelize

private/buf/bufgen/generator.go, private/buf/cmd/buf/command/generate/generate_test.go, private/buf/cmd/buf/command/generate/testdata/simple/a/v1/a.proto, private/buf/cmd/buf/command/generate/testdata/simple/buf.gen.yaml, private/buf/cmd/buf/command/generate/testdata/simple/buf.yaml
=> Fix buf generate --output

private/buf/cmd/buf/buf_test.go, private/buf/cmd/buf/command/mod/modinit/modinit.go
=> Remove `--name` and `--deps` flags from `buf mod init`

private/buf/bufcli/bufcli.go, private/buf/cmd/buf/command/alpha/registry/token/tokencreate/tokencreate.go, private/buf/cmd/buf/command/alpha/registry/token/tokendelete/tokendelete.go, private/buf/cmd/buf/command/alpha/registry/token/tokenget/tokenget.go, private/buf/cmd/buf/command/alpha/registry/token/tokenlist/tokenlist.go, private/buf/cmd/buf/command/beta/registry/branch/branchcreate/branchcreate.go, private/buf/cmd/buf/command/beta/registry/branch/branchlist/branchlist.go, private/buf/cmd/buf/command/beta/registry/commit/commitget/commitget.go, private/buf/cmd/buf/command/beta/registry/commit/commitlist/commitlist.go, private/buf/cmd/buf/command/beta/registry/organization/organizationcreate/organizationcreate.go, private/buf/cmd/buf/command/beta/registry/organization/organizationdelete/organizationdelete.go, private/buf/cmd/buf/command/beta/registry/organization/organizationget/organizationget.go, private/buf/cmd/buf/command/beta/registry/plugin/plugincreate/plugincreate.go, private/buf/cmd/buf/command/beta/registry/plugin/plugindelete/plugindelete.go, private/buf/cmd/buf/command/beta/registry/plugin/pluginlist/pluginlist.go, private/buf/cmd/buf/command/beta/registry/plugin/pluginversion/pluginversionlist/pluginversionlist.go, private/buf/cmd/buf/command/beta/registry/repository/repositorycreate/repositorycreate.go, private/buf/cmd/buf/command/beta/registry/repository/repositorydelete/repositorydelete.go, private/buf/cmd/buf/command/beta/registry/repository/repositoryget/repositoryget.go, private/buf/cmd/buf/command/beta/registry/repository/repositorylist/repositorylist.go, private/buf/cmd/buf/command/beta/registry/tag/tagcreate/tagcreate.go, private/buf/cmd/buf/command/beta/registry/tag/taglist/taglist.go, private/buf/cmd/buf/command/beta/registry/template/templatecreate/templatecreate.go, private/buf/cmd/buf/command/beta/registry/template/templatedelete/templatedelete.go, private/buf/cmd/buf/command/beta/registry/template/templatelist/templatelist.go, private/buf/cmd/buf/command/beta/registry/template/templateversion/templateversioncreate/templateversioncreate.go, private/buf/cmd/buf/command/beta/registry/template/templateversion/templateversionlist/templateversionlist.go
Fixes https://github.com/bufbuild/buf/issues/552.
=> Add warnings for alpha and beta commands

private/buf/bufwork/workspace_builder.go
We were unnecessarily checking if each workspace directory is non-empty more than once. If the module is cached, we already know it's non-empty. Plus, we weren't using the mapped `readBucket`, so this was starting at the directory containing the `buf.work.yaml`, which isn't what we want.
=> Validate each workspace directory once

private/buf/bufcli/errors.go
`buf mod init` was moved to `buf config init`.
=> Update error to point to new command

CHANGELOG.md, go.mod, go.sum, make/buf/all.mk
Fixes https://github.com/bufbuild/buf/issues/620
=> Upgrade protoreflect

private/buf/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
Fixes https://github.com/bufbuild/buf/issues/627
=> Clean up error message for DIRECTORY_SAME_PACKAGE when file with no package exists

private/gen/proto/go/buf/alpha/registry/v1alpha1/plugin.pb.go, proto/buf/alpha/registry/v1alpha1/plugin.proto
reordering requests/response to conform with style
=> reorder GetTemplateVersionRequest/response

private/gen/proto/api/buf/alpha/registry/v1alpha1/registryv1alpha1api/repository_commit.pb.go, private/gen/proto/apiclientgrpc/buf/alpha/registry/v1alpha1/registryv1alpha1apiclientgrpc/repository_commit.pb.go, private/gen/proto/go/buf/alpha/registry/v1alpha1/repository_commit.pb.go, private/gen/proto/go/buf/alpha/registry/v1alpha1/repository_commit_grpc.pb.go, proto/buf/alpha/registry/v1alpha1/repository_commit.proto
updating GetRepositoryCommitBySequenceID to GetRepositoryCommitBySequenceId for autogeneration purposes
=> update GetRepositoryCommitBySequenceID rpc name

go.mod, go.sum, private/pkg/ulidutil/ulidutil.go, private/pkg/ulidutil/ulidutil_test.go, private/pkg/ulidutil/usage.gen.go, private/pkg/uuidutil/uuidutil.go, private/pkg/uuidutil/uuidutil_test.go
This new function lets us creates ULIDs. This will be useful
for the audit logging work as ULIDs should index much more
efficiently for its usage patterns.
=> Add new ulidutil package

private/bufpkg/bufcheck/bufbreaking/bufbreakingconfig/bufbreakingconfig.go
=> Add `nil` check for breaking config

private/gen/proto/go/buf/alpha/audit/v1alpha1/repository.pb.go, proto/buf/alpha/audit/v1alpha1/repository.proto
This was missed in the initial implementation
=> Make tags repeated in commits

.github/workflows/windows.yaml
=> Add windows/** to the cache key

go.mod, go.sum, make/buf/all.mk
Pending https://github.com/jhump/protoreflect/pull/477
=> Upgrade protoreflect version

go.mod, go.sum, make/buf/all.mk
This reverts commit 8dd662613586808e8667cdab1fbc297a0905da6e.
=> Revert "Upgrade protoreflect version (#833)"

go.mod, go.sum
=> Run `make upgradegodeps`

go.sum, make/buf/scripts/release.bash, private/pkg/app/appcmd/appcmd.go
Fixes https://github.com/bufbuild/buf/issues/858.
There was a reason I removed this years ago, but I think it was related to a cobra issue. This seems to work fine now.
=> Add manpages

CHANGELOG.md, private/buf/bufgen/bufgen.go, private/buf/bufgen/config.go, private/buf/bufgen/config_test.go, private/buf/bufgen/generator.go, private/buf/bufgen/testdata/v1/gen_success6.json, private/buf/bufgen/testdata/v1/gen_success6.yaml, private/buf/bufgen/testdata/v1/gen_success6.yml, private/bufpkg/bufimage/bufimagemodify/bufimagemodify.go, private/bufpkg/bufimage/bufimagemodify/java_package.go, private/bufpkg/bufimage/bufimagemodify/java_package_test.go, private/bufpkg/bufimage/bufimagemodify/testdata/javaemptyoptions/a.proto
=> add except and override to java_package_prefix

CHANGELOG.md, go.mod, go.sum, private/buf/cmd/buf/buf.go, private/buf/cmd/buf/command/mod/modopen/modopen.go, private/buf/cmd/buf/command/mod/modopen/usage.gen.go
Fixes https://github.com/bufbuild/buf/issues/850
=> Add buf mod open

private/buf/cmd/buf/command/beta/decode/decode.go
Some very nit-picky updates to the `buf beta decode` help text.
=> Update decode command help text

private/bufpkg/bufstyle/bufstyle.go
I tested this manually for various ways of having `sync.Pool` used and it seems to work:
```go
// both fail
var _ = sync.Pool{}
func a() *sync.Pool { return nil }
```
The next thing we need to add ASAP is testing for checkers we add, https://pkg.go.dev/golang.org/x/tools@v0.1.9/go/analysis/analysistest provides some helpers, but just getting this in as it's simple.
=> Add no_sync_pool to bufstyle

README.md
Some minor flubs that I missed on my last pass through the README text.
=> Fix small issues in README

CHANGELOG.md
Update changelog to reflect all features and fixes for upcoming release.﻿
=> Update changelog in preparation for v1.1.0 release

private/gen/proto/go/buf/alpha/image/v1/image.pb.go, proto/buf/alpha/image/v1/image.proto
=> Fix comment in image.proto

private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
'Twas a bad merge. The original PR was pretty stale.
=> fix 5a0e42709378a8cb4eaaf9765e4a418550401adc

private/bufpkg/bufstyle/analyzers.go, private/pkg/app/appproto/appprotoexec/binary_handler.go, private/pkg/protogenutil/protogenutil.go, private/pkg/storage/storagetesting/storagetesting.go
Context: https://github.com/bufbuild/connect-go/pull/227#issuecomment-1139261227
=> Add BEHAVIOUR linter to bufstyle

CHANGELOG.md, private/bufpkg/bufcheck/buflint/buflint_test.go, private/bufpkg/bufcheck/buflint/testdata/enum_zero_value_suffix_custom/a.proto
=> Revert "Add tests and changelog for ENUM_ZERO_VALUE_SUFFIX"

private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go, private/bufpkg/bufplugin/bufplugin.go, private/bufpkg/bufplugin/bufplugin_test.go
Update the `buf alpha plugin push` command to call CreateCuratedPlugin
to add the plugin to the BSR.
=> update plugin push to create curated plugin

go.mod, go.sum
=> Run `make upgrade`

private/buf/bufcli/bufcli.go, private/pkg/transport/http/httpclient/client.go, private/pkg/transport/http/httpclient/httpclient.go, private/pkg/transport/http/httpclient/httpclient_test.go
This reverts commit f986e87dd0fd9400676fc5d9d7cc424953510906.
Investigating an unrelated issue with module references and reverting temporarily to easily isolate that issue.
=> Revert "Merge http clients for ease of use (#1288)"

private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go, private/bufpkg/bufplugin/bufplugindocker/docker.go
Update the `buf alpha plugin push` to allow for using cached images
published to a Docker registry, pulling the latest base images at build
time, and bypassing pushing to the BSR so local testing can run builds.
Additionally, add some rudimentary parsing of the `moby.buildkit.trace`
messages so we get more details when run with `--debug`.
=> add --cache-from/--pull/--dry-run options

private/buf/cmd/buf/buf.go, private/buf/cmd/buf/command/beta/registry/commit/commitget/commitget.go, private/buf/cmd/buf/command/beta/registry/commit/commitget/usage.gen.go, private/buf/cmd/buf/command/beta/registry/commit/commitlist/commitlist.go, private/buf/cmd/buf/command/beta/registry/commit/commitlist/usage.gen.go, private/buf/cmd/buf/command/beta/registry/tag/tagcreate/tagcreate.go, private/buf/cmd/buf/command/mod/modprune/modprune.go, private/buf/cmd/buf/command/push/push.go
=> Revert "Change commit to snapshot"

private/bufpkg/bufmodule/module_test.go
`NewModuleForBucket` didn't have any coverage, so here's some I added as
I was working on other things.
=> bufmodule: test NewModuleForBucket

private/bufpkg/bufimage/bufimagebuild/builder_test.go
If you run `go test -count 1` repeatedly, the `private/bufpkg/bufimage/bufimagebuild` package tests pass every time.
**But** if you try `go test -race`, they fail every time. I'm not sure what changes when `-race` is introduced that might impact execution order... but _something_ changes. So this updates the one test that fails with race detection so that it now passes in _both_ configurations.
=> make cyclic import test deterministic

private/buf/cmd/buf/internal/internaltesting/internaltesting.go
CONFIG_DIR is useful for controlling TLS.
=> internaltesting: also inject CONFIG_DIR envvar

private/buf/cmd/buf/command/push/push_test.go
Push never had testing before. Now it does!
=> push: add testing

private/buf/cmd/buf/command/push/push_test.go
Some small testing tweaks for readability in push_test.go.
=> push: tweak testing

private/bufpkg/bufimage/bufimagebuild/builder_test.go
=> fix flaky tests caused by compiler's internal parallelism

private/buf/bufcli/bufcli.go, private/buf/bufcli/bufcli_test.go
Related to https://github.com/bufbuild/buf/pull/1563
=> [bsr-721] Reader only interface

private/buf/bufcli/bufcli.go, private/buf/cmd/buf/command/alpha/protoc/protoc.go, private/buf/cmd/buf/command/breaking/breaking.go, private/buf/cmd/buf/command/export/export.go, private/buf/cmd/buf/command/format/format.go, private/buf/cmd/buf/command/generate/generate.go, private/buf/cmd/buf/command/lint/lint.go, private/buf/cmd/buf/command/lsfiles/lsfiles.go, private/bufpkg/bufapimodule/bufapimodule.go, private/bufpkg/bufapimodule/module_reader.go, private/bufpkg/bufapimodule/module_resolver.go
=> use plain connect client stubs for DownloadService

private/buf/cmd/buf/command/mod/modprune/modprune.go, private/buf/cmd/buf/command/mod/modupdate/modupdate.go
=> use plain connect stubs for ResolveService

private/buf/cmd/buf/command/beta/registry/plugin/plugincreate/plugincreate.go, private/buf/cmd/buf/command/beta/registry/plugin/plugindelete/plugindelete.go, private/buf/cmd/buf/command/beta/registry/plugin/plugindeprecate/plugindeprecate.go, private/buf/cmd/buf/command/beta/registry/plugin/pluginlist/pluginlist.go, private/buf/cmd/buf/command/beta/registry/plugin/pluginundeprecate/pluginundeprecate.go, private/buf/cmd/buf/command/beta/registry/plugin/pluginversion/pluginversionlist/pluginversionlist.go, private/buf/cmd/buf/command/beta/registry/template/templatecreate/templatecreate.go, private/buf/cmd/buf/command/beta/registry/template/templatedelete/templatedelete.go, private/buf/cmd/buf/command/beta/registry/template/templatedeprecate/templatedeprecate.go, private/buf/cmd/buf/command/beta/registry/template/templatelist/templatelist.go, private/buf/cmd/buf/command/beta/registry/template/templateundeprecate/templateundeprecate.go, private/buf/cmd/buf/command/beta/registry/template/templateversion/templateversioncreate/templateversioncreate.go, private/buf/cmd/buf/command/beta/registry/template/templateversion/templateversionlist/templateversionlist.go
=> use raw connect client for PluginService

private/buf/bufprint/bufprint.go, private/buf/bufprint/repository_printer.go, private/buf/cmd/buf/command/beta/registry/organization/organizationcreate/organizationcreate.go, private/buf/cmd/buf/command/beta/registry/organization/organizationdelete/organizationdelete.go, private/buf/cmd/buf/command/beta/registry/organization/organizationget/organizationget.go, private/buf/cmd/buf/command/beta/registry/repository/repositorycreate/repositorycreate.go, private/buf/cmd/buf/command/beta/registry/repository/repositoryget/repositoryget.go, private/buf/cmd/buf/command/beta/registry/repository/repositorylist/repositorylist.go
=> use plain connect client for OrganizationService

private/buf/cmd/buf/command/beta/registry/webhook/webhookcreate/webhookcreate.go, private/buf/cmd/buf/command/beta/registry/webhook/webhookdelete/webhookdelete.go, private/buf/cmd/buf/command/beta/registry/webhook/webhooklist/webhooklist.go
=> use plain connect stubs for WebhookService

private/buf/cmd/buf/command/alpha/registry/token/tokencreate/tokencreate.go, private/buf/cmd/buf/command/alpha/registry/token/tokendelete/tokendelete.go, private/buf/cmd/buf/command/alpha/registry/token/tokenget/tokenget.go, private/buf/cmd/buf/command/alpha/registry/token/tokenlist/tokenlist.go
=> use plain connect stub for TokenService

private/pkg/manifest/module.go, private/pkg/manifest/storage.go
Had some doubts when using this from push, had to read implementation, so just updating the funcs docs.
=> Improve Bucket and Module docs

private/bufpkg/bufimage/bufimageutil/bufimageutil.go, private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go, private/bufpkg/bufimage/bufimageutil/image_index.go, private/bufpkg/bufimage/bufimageutil/testdata/extensions/extensions-excluded.txtar, private/bufpkg/bufimage/bufimageutil/testdata/importmods/regular_public.txtar, private/bufpkg/bufimage/bufimageutil/testdata/importmods/weak_public.txtar, private/bufpkg/bufimage/bufimageutil/testdata/options/all-exclude-options.txtar, private/bufpkg/bufimage/bufimageutil/testdata/options/pkg.FooService.Do.txtar, private/pkg/protosource/file.go, private/pkg/protosource/message.go, private/pkg/protosource/message_range.go, private/pkg/protosource/protosource.go
* Add options to control whether extensions and custom options are included
* Add support for extension range options
* Add support for using a method name to filter elements
* Fix issue related to public imports
Fixes TCN-802
=> improvements to image filtering

private/buf/bufcli/bufcli.go
=> Return to development

CHANGELOG.md, private/buf/bufgen/bufgen.go, private/buf/bufgen/generator.go
=> bufgen: Batch generation

private/buf/cmd/buf/command/curl/curl.go
Not complete, needs to be done for all flags if we want to do this
=> Suggestion to make flag text wrapped

private/buf/cmd/buf/buf.go, private/buf/cmd/buf/command/alpha/plugin/plugindelete/plugindelete.go, private/buf/cmd/buf/command/alpha/plugin/plugindelete/usage.gen.go, private/bufpkg/bufplugin/bufpluginref/plugin_identity.go, private/bufpkg/bufplugin/bufpluginref/plugin_reference.go
This PR adds a `buf alpha plugin delete ...` command to delete a curated plugin from the BSR registry.
=> Add plugin delete command

.github/actions/changelog-action/entrypoint.sh, .github/workflows/release.yaml
Small bash step to fetch changelog of current release version from changelog before putting it into the body of the release.
[example](https://github.com/elliotmjackson/buf/releases/tag/v1.12.0)
=> Update release.yaml to fetch changelog

.github/workflows/release.yaml
>BufCLI Release vv1.13.0 is complete: https://github.com/bufbuild/buf/releases/tag/v1.13.0
=> Remove superfluous v in slack notification

private/pkg/git/git.go, private/pkg/git/lister.go, private/pkg/licenseheader/cmd/license-header/main.go
It turns out we do have a use case for these already.
=> Switch git.Lister ignores to regexps

.github/workflows/release.yaml
Adding a step to trigger npm publish after release is complete.
=> Add step to trigger npm publish

README.md
Adding call to install via npm.
=> Add npm install reference

.github/workflows/release.yaml
indentation has been incorrect and causing the release action to fail quietly
=> Fix indentation bug

private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingcheck/bufbreakingcheck.go, private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingcheck/util.go, private/pkg/protodescriptor/protodescriptor.go
It turns out we need these in core as well.
=> Expose pretty strings for FieldDescriptorProto enums

.github/workflows/release.yaml
provide ID `output_version` to last step of `post-release` job so that it is accessible by 
```
outputs:
version: ${{ steps.output_version.outputs.version }}
```
and
```
needs.post-release.outputs.version
```
=> Update post-release jobs output step

private/buf/cmd/buf/command/beta/price/price.go
swapping Team for teams; renaming some vars/methods
=> Swap Team for Teams in buf beta price

private/bufpkg/bufwasm/bufwasm.go
This branch merges our internal code with the existing bufwasm code here. Once this lands, bufbuild/buf will be the source of truth for bufwasm.
=> Merge internal bufwasm code into this repo

go.mod, go.sum
Supplants https://github.com/bufbuild/buf/pull/1969
=> Make upgrade

CHANGELOG.md, private/bufpkg/bufanalysis/bufanalysistesting/bufanalysistesting_test.go, private/bufpkg/bufanalysis/file_annotation.go, private/bufpkg/bufanalysis/print.go, private/bufpkg/bufanalysis/util.go
Fixes https://github.com/bufbuild/buf/issues/1930
=> Output at least 1 for line and column information for JSON and MSVS

private/pkg/storage/multi.go, private/pkg/storage/storagetesting/storagetesting.go
I've verified this is unused in `bufbuild/core` as well.
=> Remove unused `MultiReadBucketSkipMultipleLocations`

private/buf/buffetch/internal/errors.go, private/buf/buffetch/internal/proto_file_ref.go, private/buf/buffetch/internal/ref_parser.go, private/buf/bufwire/image_config_reader.go, private/pkg/app/app.go
Fixes https://github.com/bufbuild/buf/issues/1920.
Fixes https://github.com/bufbuild/buf/issues/1915.
=> Add error message if protofile is attempted to be read or written from stdio

private/buf/cmd/buf/command/curl/curl.go
basic auth needs the Basic prefix
Refs #2010
=> Fix basic auth in buf curl

private/buf/bufcurl/invoker.go
I think I was wrong on this one.
=> Indent for buf curl

private/pkg/diff/diffmyers/diffmyers.go, private/pkg/diff/diffmyers/diffmyers_test.go, private/pkg/diff/diffmyers/usage.gen.go
Add a new `diffmyers` package to calculate the diff between two files in pure go. This is the same algorithm that `git` uses.
=> Add `diffmyers` package

private/buf/cmd/buf/buf.go, private/pkg/app/appflag/builder.go
Basically reverts https://github.com/bufbuild/buf/pull/1305. Fixes #2187.
=> Remove `noTimeoutBuilder`

CHANGELOG.md, private/buf/cmd/buf/command/beta/studioagent/studioagent.go
=> Update default origin for buf beta studio-agent to buf.build

.github/workflows/release.yaml
Fixes the PR triggering so that the PRs on other repos should occur automatically only needing merging after they get raised
=> Fix PR trigger release github actions

private/buf/bufwire/module_config_reader.go
In the `moduleConfigReader`, we print a warning if a `buf.lock` does not have coverage on all the dependencies declared inside a `buf.yaml`. However, it's valid to have dependencies in a `buf.yaml` that are within a workspace but not in your `buf.lock`. Even worse, these dependencies may not actually be on the BSR, so when you follow the instructions to `buf mod update`, `buf mod update` will then fail.
This PR makes it so that if the dependency is inside the workspace, no warning is printed. It also deletes `getModuleConfig`, which was only used in `getSourceModuleConfig`, so this just merges the two functions.
=> Fix detectMissingDependencies in moduleConfigReader for workspaces

private/buf/bufwire/module_config_reader.go, private/buf/bufwork/bufwork.go, private/buf/bufwork/workspace_builder.go, private/buf/cmd/buf/workspace_test.go, private/bufpkg/bufmodule/bufmodule.go, private/bufpkg/bufmodule/bufmodulebuild/module_file_set_builder.go, private/bufpkg/bufmodule/workspace.go
See code comments. This is also starting to undo the mess in the workspace code, this is a long story.
We don't have super high confidence in this PR, but we think it puts us in a better state than we were in. It may cause bugs, although I have extensively QA'ed this.
=> Fix bugs in ModuleFileSetBuilder and Workspace

private/pkg/diff/diffmyers/diffmyers.go, private/pkg/diff/diffmyers/diffmyers_test.go, private/pkg/diff/diffmyers/testdata/lao-tzu
It was ignoring the first edit after a skip. Also tweak the algorithm to prioritize deletions.
=> Fix `diffmyers` print and tweak the algorithm

private/bufpkg/bufgraph/builder.go, private/pkg/dag/dag.go
This commit was in #2240 but the GitHub outage meant it didn't get pushed. Unfortunate it didn't make the release (may want to do a 1.23.1 tomorrow, with this plus a few other things).
=> Fix buf graph for unattached nodes

private/bufpkg/bufgraph/bufgraph_test.go, private/bufpkg/bufgraph/builder.go, private/bufpkg/bufgraph/testdata/basic/buf.work.yaml, private/bufpkg/bufgraph/testdata/basic/test-a/a/v1/a.proto, private/bufpkg/bufgraph/testdata/basic/test-a/a2/v1/a2.proto, private/bufpkg/bufgraph/testdata/basic/test-a/buf.yaml, private/bufpkg/bufgraph/testdata/basic/test-b/b/v1/b.proto, private/bufpkg/bufgraph/testdata/basic/test-b/buf.yaml, private/bufpkg/bufgraph/testdata/basic/test-c/buf.yaml, private/bufpkg/bufgraph/testdata/basic/test-c/c/v1/c.proto, private/bufpkg/bufgraph/testdata/basic/test-d/buf.yaml, private/bufpkg/bufgraph/testdata/basic/test-d/d/v1/d.proto, private/bufpkg/bufgraph/testdata/basic/test-e/buf.yaml, private/bufpkg/bufgraph/testdata/basic/test-e/e/v1/e.proto, private/bufpkg/bufgraph/testdata/basic/test-f/buf.yaml, private/bufpkg/bufgraph/testdata/basic/test-f/f/v1/f.proto, private/bufpkg/bufgraph/testdata/basic/test-g/buf.yaml, private/bufpkg/bufgraph/testdata/basic/test-g/g/v1/g.proto, private/bufpkg/bufmodule/bufmodulebuild/bufmodulebuild.go, private/pkg/dag/dag.go
This caches the building of individual nodes, and adds basic testing for `bufgraph`.
=> Cache node building in graph and add testing

CHANGELOG.md, private/buf/cmd/buf/command/beta/price/price.go
=> Update `buf beta price` with the latest pricing information

private/pkg/observabilityzap/observabilityzap.go
Update the observabilityzap package to return an interface instead of a pointer to an unexported type.
=> Update method that returns unexported struct

private/buf/cmd/buf/command/alpha/repo/reposync/reposync.go
Improve output of synced commits, to make clear the source and destination.
=> Improve sync output

CHANGELOG.md, private/bufpkg/bufmodule/bufmodulebuild/module_file_set_builder.go
Fixes https://github.com/bufbuild/buf/issues/2333.
=> Fix issue where all files were being iterated over when using path filtering

.github/workflows/buf-shadow-sync.yaml
Enable current-branch sync for `main`. Once that's synced once, we can enabled it for every branch.
=> Re-enable shadow sync

private/pkg/protoversion/package_version.go, private/pkg/protoversion/protoversion.go, private/pkg/protoversion/protoversion_test.go
=> Add protoversion.NewPackageVersionForComponent

private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder.go
=> Fix issue where bufmodulebuild.ModuleBucketBuilder.BuildForBucket did not properly accept an empty configuration

private/bufpkg/bufmanifest/bucket.go, private/bufpkg/bufmanifest/bufmanifest.go, private/bufpkg/bufmanifest/mapper.go, private/gen/proto/go/buf/alpha/module/v1alpha1/module.pb.go, private/gen/proto/go/buf/alpha/registry/v1alpha1/download.pb.go, private/gen/proto/go/buf/alpha/registry/v1alpha1/push.pb.go, private/pkg/manifest/blob.go, private/pkg/manifest/blob_test.go, private/pkg/manifest/digest.go, private/pkg/manifest/manifest.go, private/pkg/manifest/manifest_test.go, private/pkg/storage/storagemanifest/storagemanifest_test.go, proto/buf/alpha/module/v1alpha1/module.proto, proto/buf/alpha/registry/v1alpha1/download.proto, proto/buf/alpha/registry/v1alpha1/push.proto
Update buf/manifest docs (and remove a few options which should have always been enabled). Improve documentation in the module .proto files.
=> Improve buf/manifest package and proto docs

private/buf/bufcli/bufcli.go, private/buf/cmd/buf/command/curl/curl.go, private/gen/proto/go/buf/alpha/registry/v1alpha1/webhook.pb.go, proto/buf/alpha/registry/v1alpha1/webhook.proto
- Update Eliza module: bufbuild/eliza -> connectrpc/eliza (also update import path and commit to be consistent with new module)
- Update connect.build -> connectrpc.com
=> Update connect.build and Eliza references

.github/workflows/release.yaml
This fixes the formatting on the release workflow.
=> Fix release workflow yaml

private/buf/cmd/buf/command/curl/curl.go
Just noticed this browsing the help - fantastic tool otherwise :-).
=> Fix minor typo in buf curl flags

private/buf/bufformat/bufformat.go
So individual files can be formatted in memory.
=> Expose formatting of ast.FileNode

private/buf/bufformat/bufformat.go
=> Revert "Expose formatting of ast.FileNode"

private/buf/bufsync/backfill_tags_test.go, private/buf/bufsync/bufsync_test.go, private/buf/bufsync/commits_to_sync_test.go, private/buf/bufsync/prepare_sync_test.go
It also supports multi-repo properly, something I'll need in the tests I'm going to add soon.
=> Change `mockSyncHandler` to `testSyncHandler`

Dockerfile.buf, Dockerfile.workspace, make/buf/all.mk
Follow-up to https://github.com/bufbuild/buf/pull/2652.
=> Adjust rest of alpine image references to point to 3.19

private/pkg/app/appflag/builder.go
This lets you manually control the parallelism when doing operations such as profiling, to try to see what happens when you don't multithread items like image building.
=> Add hidden --parallelism flag

.pre-commit-hooks.yaml
Fixes https://github.com/bufbuild/buf/issues/2833.
=> Add language_version to .pre-commit-hooks.yaml

go.mod, go.sum
```console
$ go get buf.build/gen/go/bufbuild/registry/connectrpc/go@latest
$ go mod tidy
$ make generate # no changes
```
=> Update registry-proto dependency

private/bufpkg/bufimage/bufimagemodify/field_option.go
Fixes `field_name` disables to work on the file and field levels. Previous fix #2860 broke file level disables for when a field name was present. We now filter all the override and disable rules upfront for the image file, check for file level disables, then apply disables at a field level and finally apply the override per field. Filtering upfront will also reduces the number of rules checked per field.
=> Fix field_name file level checks for field_options

CHANGELOG.md
Add missing changelog updates.
- https://github.com/bufbuild/buf/pull/2824
=> Update CHANGELOG.md for v1.30.1

private/bufpkg/bufmodule/bufmoduleapi/uploader.go
Update to ensure that push sends content even if no labels are provided with --draft/--tag/--branch/--label.
=> Fix push with no flags

CHANGELOG.md, private/buf/bufcli/bufcli.go
Merging main to update the changelog and CLI version.
=> Merge origin/main to dev

private/buf/cmd/buf/command/export/export.go
This PR changes `buf export` so that when `--exclude-imports` is
passed, it does not require the input to be buildable as an image.
This allows a user to provide an input that may not be buildable, and
they can still get the source files back when `--exclude-imports` is
set, since we do not need the image to check for import files.
Fixes #3002
=> Avoid building image for `buf export` when `--exclude-imports` flag is set

README.md
Fixes https://github.com/bufbuild/buf/issues/3026
=> Fix link to tour

private/buf/cmd/buf/command/beta/registry/archive/archive.go
=> Fix typo on archive label validation

CHANGELOG.md, private/bufpkg/bufcheck/buflint/internal/buflintvalidate/adder.go, private/bufpkg/bufcheck/buflint/testdata/protovalidate/proto/buf.yaml, private/bufpkg/bufcheck/buflint/testdata/protovalidate/proto/field.proto
Fixes https://github.com/bufbuild/buf/issues/3048.
=> Fix comment ignores for PROTOVALIDATE lint rule

private/bufpkg/bufmodule/module.go
See https://github.com/bufbuild/buf/pull/3075.
=> Clarify docs for Module.OpaqueID and Module.BucketID

private/bufpkg/bufprotosource/bufprotosource.go, private/bufpkg/bufprotosource/location.go, private/bufpkg/bufprotosource/merge_comment_location.go
This will be needed for upcoming plugins work.
=> Add Path to bufprotosource.Location

private/bufpkg/bufprotosource/bufprotosource.go, private/bufpkg/bufprotosource/file.go, private/bufpkg/bufprotosource/location.go, private/bufpkg/bufprotosource/location_store.go, private/bufpkg/bufprotosource/merge_comment_location.go, private/bufpkg/bufprotosource/option_extension_descriptor.go, private/bufpkg/bufprotosource/option_extension_descriptor_test.go
This will make interoperability with bufplugin-go much easier.
=> Add FilePath to bufprotosource.Location

private/pkg/storage/map.go
Param is missing on constructor, close isn't called.
=> Fix close on write storage mappers

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/3-other.yml
This is still happening, see the issue that was just filed. Making this even stricter.
=> Make issue templates even stricter

private/buf/cmd/buf/buf_test.go, private/bufpkg/bufcheck/client.go, private/bufpkg/bufcheck/internal/bufcheckserver/internal/bufcheckserverhandle/breaking.go, private/bufpkg/bufcheck/internal/bufcheckserver/internal/bufcheckserverhandle/lint.go, private/bufpkg/bufcheck/internal/bufcheckserver/internal/bufcheckserverhandle/lint_util.go, private/bufpkg/bufcheck/internal/bufcheckserver/internal/buflintvalidate/buflintvalidate.go
I did a quick audit of our `TODO`s from `bufplugin`, and put together a pretty small PR to address some of the low-hanging ones. In-lined comments in the PR to help with review.
=> Review low hanging TODOs

.golangci.yml, private/buf/bufcurl/invoker_test.go
Follow up for #3346 to increase coverage for text and yaml formats.
=> Force usage of private/pkg/protoencoding for text and yaml

go.mod, go.sum, private/bufpkg/bufregistryapi/bufregistryapiplugin/bufregistryapiplugin.go
Pulls in the latest registry proto which adds the plugin Resource client.
=> Update registry proto

go.mod, go.sum
=> Upgrade wazero and quic-go

private/bufpkg/bufplugin/plugin.go
This fixes missing documentation for the new Plugin interface.
=> Fix documentation for Plugin interface

.github/workflows/docker-publish.yaml
Missing semicolon, update descriptions to make options clearer.
=> Fix typo docker workflow command

.github/workflows/docker-publish.yaml
This goes through testing the command and adds fixes.
=> Fix docker workflow publish command

private/gen/proto/connect/buf/alpha/registry/v1alpha1/registryv1alpha1connect/organization.connect.go, private/gen/proto/go/buf/alpha/audit/v1alpha1/event.pb.go, private/gen/proto/go/buf/alpha/registry/v1alpha1/organization.pb.go, proto/buf/alpha/audit/v1alpha1/event.proto, proto/buf/alpha/registry/v1alpha1/organization.proto
Primarily to support updating the role override. Also add associated audit event.
=> Add `UpdateOrganizationGroup`

private/bufpkg/bufplugin/plugin_data_provider.go, private/bufpkg/bufplugin/plugin_key_provider.go, private/bufpkg/bufpolicy/bufpolicy.go, private/bufpkg/bufpolicy/commit.go, private/bufpkg/bufpolicy/digest.go, private/bufpkg/bufpolicy/errors.go, private/bufpkg/bufpolicy/policy.go, private/bufpkg/bufpolicy/policy_data.go, private/bufpkg/bufpolicy/policy_data_provider.go, private/bufpkg/bufpolicy/policy_key.go, private/bufpkg/bufpolicy/policy_key_provider.go, private/bufpkg/bufpolicy/policy_visibility.go, private/bufpkg/bufpolicy/uploader.go, private/bufpkg/bufpolicy/usage.gen.go
This initializes the bufpolicy pkg to manage polices. The pkg is not currently used and theres no change in behaviour.
=> Init bufpolicy pkg for policies

go.mod, go.sum, private/bufpkg/bufpolicy/digest.go, private/bufpkg/bufpolicy/policy_data.go
This pulls in the latest registry for policy changes and renames the digest type.
=> Upgrade registry proto for policy digest

private/gen/proto/connect/buf/alpha/registry/v1alpha1/registryv1alpha1connect/organization.connect.go, private/gen/proto/connect/buf/alpha/registry/v1alpha1/registryv1alpha1connect/repository.connect.go, private/gen/proto/go/buf/alpha/registry/v1alpha1/organization.pb.go, private/gen/proto/go/buf/alpha/registry/v1alpha1/repository.pb.go, proto/buf/alpha/registry/v1alpha1/organization.proto, proto/buf/alpha/registry/v1alpha1/repository.proto
This PR drops two RPCs that have been unimplemented in production for ~2 months:
- GetRepositoryContributor
- SetOrganizationMember
=> Drop some unused RPCs

private/bufpkg/bufpolicy/digest.go, private/bufpkg/bufpolicy/policy_config.go
This exposes the stable JSON marshal for the policy configuration.
=> Export MarshalPolicyConfigAsJSON for policies

.github/workflows/back-to-development.yaml, .github/workflows/build-and-draft-release.yaml, .github/workflows/create-release-pr.yaml, .github/workflows/make-upgrade.yaml
=> Update App Token Workflow to Latest

private/buf/bufctl/controller.go, private/bufpkg/bufpolicy/policy_plugin_data_provider.go, private/bufpkg/bufpolicy/policy_plugin_key_provider.go
This fixes resolving a policy ref to its plugins in the `buf.lock` file and provides some better error messages and validation. Policies are stored by the full ref (`buf.build/acme/policy:label`) in the `buf.yaml` and the full name (`buf.build/acme/policy`) in the `buf.lock` file. A ref is resolved to its full name for lookup.
=> Fix remote policy ref resolution for plugins
