- internal/buf/bufos/env_reader.go
- internal/buf/bufos/internal/input_ref_parser.go
- internal/buf/bufos/internal/input_ref_parser_test.go
- internal/buf/bufos/internal/internal.go
- internal/pkg/storage/internal/storagetesting/storagetesting_test.go
- internal/pkg/storage/storagegit/storagegit.go
Fixes #42.
Example:
```
$ buf check lint --input https://github.com/foo/bar.git#branch=master,recurse_submodules=true
```
> Add recurse_submodules input option

- go.mod
- go.sum
- internal/pkg/fetch/errors.go
- internal/pkg/fetch/fetch.go
- internal/pkg/fetch/git_ref.go
- internal/pkg/fetch/reader.go
- internal/pkg/fetch/ref_parser.go
- internal/pkg/fetch/ref_parser_test.go
- internal/pkg/git/branch.go
- internal/pkg/git/cloner.go
- internal/pkg/git/git.go
- internal/pkg/git/git_test.go
- internal/pkg/git/ref.go
- internal/pkg/git/ref_branch.go
- make/buf/scripts/release.bash
A valid ref is defined as anything accepted by "git checkout". Depth can further be configured by specifying the depth option. It defaults to 50 when ref is used, or 1 otherwise.
> Support arbitrary git refs in input

- go.mod
- go.sum
- internal/buf/bufcli/bufcli.go
- internal/buf/bufcli/env_reader.go
- internal/buf/cmd/buf/buf.go
- internal/buf/cmd/buf/buf_test.go
- internal/buf/cmd/buf/cmds.go
- internal/buf/cmd/buf/flags.go
- internal/buf/cmd/buf/run.go
- internal/buf/cmd/buf/testdata/customoptions1/a.proto
- internal/buf/cmd/protoc-gen-buf-check-breaking/breaking.go
- internal/pkg/proto/protoencoding/json_marshaler.go
- internal/pkg/proto/protoencoding/json_unmarshaler.go
- internal/pkg/proto/protoencoding/resolver.go
This PR does two things:
1. Properly marshals/unmarshals custom options in JSON. This fixes #50. For example:
```proto
syntax = "proto3";
import "google/protobuf/descriptor.proto";
extend google.protobuf.FieldOptions {
int32 baz = 50007;
}
message Foo {
string bar = 1 [(baz) = 42];
}
```
Running `buf image build --exclude-imports --exclude-source-info -o -#format=json | jq` results in:
```json
{
"file": [
{
"name": "a.proto",
"dependency": [
"google/protobuf/descriptor.proto"
],
"messageType": [
{
"name": "Foo",
"field": [
{
"name": "bar",
"number": 1,
"label": "LABEL_OPTIONAL",
"type": "TYPE_STRING",
"jsonName": "bar",
"options": {
"[baz]": 42
}
}
]
}
],
"extension": [
{
"name": "baz",
"number": 50007,
"label": "LABEL_OPTIONAL",
"type": "TYPE_INT32",
"extendee": …
```
> Marshal/unmarshal custom options in JSON and add image convert command

- internal/buf/bufbuild/builder_test.go
- internal/buf/cmd/buf/buf.go
- internal/buf/cmd/buf/internal/protoc/protoc_test.go
- internal/pkg/app/appproto/appprotoexec/binary_handler.go
- internal/pkg/app/appproto/appprotoexec/protoc_proxy_handler.go
- internal/pkg/diff/diff.go
- internal/pkg/prototesting/prototesting.go
- make/buf/base.mk
- make/go/base.mk
- make/go/dep_protoc.mk
- make/go/go.mk
- make/go/protoc_gen_go.mk
- make/go/scripts/protoc_gen_plugin.bash
This does the following:
- Uses `buf protoc` instead of `protoc` for buf.
- Fixes an issue where stderr was not propagated for protoc plugins on the CLI side.
- Re-adds `SourceCodeInfo` comparison testing, as that now works.
> Dogfood buf, propagate stderr for protoc plugins, and re-add SourceCodeInfo comparison testing

- internal/pkg/app/appproto/appprotoexec/protoc_proxy_handler.go
Fixes issue where the opt flag is interpreted as a file to generate,
causing the compilation to fail.
> Add missing `--` to protoc proxy handler opt flag

- go.mod
- go.sum
- internal/pkg/app/appproto/response_writer.go
- internal/pkg/app/appproto/util.go
Per https://github.com/protocolbuffers/protobuf/blob/95e6c5b4746dd7474d540ce4fb375e3f79a086f8/src/google/protobuf/compiler/plugin.proto#L68
```
// The file name, relative to the output directory.  The name must not
// contain "." or ".." components and must be relative, not be absolute (so,
// the file cannot lie outside the output directory).  "/" must be used as
// the path separator, not "\".
```
We were validating this for `CodeGeneratorResponse.File.Names`, but some plugins do not conform to this, and this causes errors. This relaxes the validation to produce a warning when possible instead.
> Relax filename validation for CodeGeneratorResponses

- go.mod
- go.sum
- internal/buf/bufcore/bufimage/bufimage.go
- internal/buf/bufcore/bufimage/bufimagebuild/builder_test.go
- internal/buf/bufcore/bufimage/image.go
- internal/buf/bufcore/bufimage/util.go
- internal/buf/bufcore/bufimage/validate.go
- internal/buf/bufcore/bufmodule/bufmodulebuild/util.go
- internal/buf/bufcore/bufmodule/targeting_module.go
- internal/buf/bufwire/image_reader.go
- internal/buf/cmd/buf/command/generate/generate.go
- internal/buf/internal/buftesting/buftesting.go
- internal/pkg/github/githubtesting/archive_reader.go
- internal/pkg/github/githubtesting/githubtesting.go
- Adds file locking for testing
- Updates some error messages
- Clarifies that `--path` values must be fully contained within roots
> Sync from internal

- internal/buf/bufcheck/bufbreaking/bufbreaking_test.go
- internal/buf/bufcheck/bufbreaking/testdata/breaking_file_no_delete_unstable/a/v1beta1/a.proto
- internal/buf/bufcheck/bufbreaking/testdata/breaking_file_no_delete_unstable/buf.yaml
- internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_file_no_delete_unstable/a/v1beta1/a.proto
- internal/buf/bufcheck/bufbreaking/testdata_previous/breaking_file_no_delete_unstable/a/v1beta1/b.proto
- internal/buf/bufcheck/internal/runner.go
> Check if descriptor is nil when filtering unstable packages

- go.mod
- go.sum
- internal/buf/bufgen/bufgen.go
- internal/buf/bufgen/config.go
- internal/buf/bufgen/config_test.go
- internal/buf/bufgen/generator.go
- internal/buf/bufgen/testdata/gen_success1.json
- internal/buf/bufgen/testdata/gen_success1.yaml
Fixes #208.
This adds the `plugins.strategy` option for `buf.gen.yaml` configuration files. You can choose either `directory` or `all`:
```yaml
version: v1beta1
plugins:
- name: doc
out: doc
strategy: all
```
The default is `directory`.
> Add plugin generation strategy

- internal/buf/cmd/buf/command/generate/generate.go
Currently the sample YAML file has a typo that results in an invalid file, this PR fixes it.
There is no existing linked issue filed for this, please let me know if one is needed.
> Fix typo in generate command sample YAML

- .github/workflows/ci.yaml
- Dockerfile.buf
As per #288, I have made this PR to make GitHub Actions supports building multi-architecture Docker image by using [docker/setup-qemu-action](https://github.com/docker/setup-qemu-action), [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action), and [docker/build-push-action](https://github.com/docker/build-push-action).
I have tested the GitHub Actions workflow in my fork. The `docker` job depends on `build` job, and `docker` job will be run if and only if it is on `master` branch or a tag is pushed.
EDIT: This PR will make `.github/scripts/docker.bash` redundant, the maintainers can consider to remove it.
> Support multi-architecture Docker image

- internal/buf/bufcli/errors.go
- internal/buf/cmd/buf/command/beta/mod/modexport/modexport.go
- internal/buf/cmd/buf/command/beta/mod/modinit/modinit.go
- internal/buf/cmd/buf/command/breaking/breaking.go
- internal/buf/cmd/buf/command/build/build.go
- internal/buf/cmd/buf/command/convert/convert.go
- internal/buf/cmd/buf/command/protoc/protoc.go
- internal/pkg/licenseheader/cmd/license-header/main.go
- internal/pkg/spdx/cmd/spdx-go-data/main.go
Fixes #317
This updates some errors like this:
```
Failed to "breaking": Flag --against is required..
```
to be this:
```
Failed to "breaking": --against is required.
```
This includes some refactors to use bufcli.NewFlagIsRequiredError rather
than appcmd.NewInvalidArgumentErrorf, but only in those instances where
bufcli was already imported. I wasn't sure if adding that import in e.g.
`internal/pkg/spdx/cmd/spdx-go-data` was desired, so I left those
changes out.
> Fix double-dot missing flag errors

- internal/buf/bufcheck/buflint/buflint_test.go
- internal/buf/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
- internal/buf/bufcheck/buflint/internal/buflintcheck/util.go
- internal/buf/bufcheck/buflint/testdata/comments/a.proto
This makes COMMENT_* checks stop considering buf:lint:ignore directives to be valid comments.
fixes #297
> Make linter not consider directives to be valid comments

- internal/buf/cmd/buf/command/protoc/const_unix.go
- internal/buf/cmd/buf/command/protoc/const_windows.go
- internal/pkg/filepathextended/filepathextended_unix_test.go
- internal/pkg/interrupt/interrupt.go
- internal/pkg/interrupt/interrupt_unix.go
- internal/pkg/interrupt/interrupt_windows.go
- internal/pkg/netrc/netrc_unix.go
- internal/pkg/netrc/netrc_unix_test.go
Starts to address https://github.com/bufbuild/buf/issues/362.
Starts to supplant https://github.com/bufbuild/buf/pull/363.
See https://github.com/cockroachdb/cockroach/issues/67216.
We will deal with the `app` package in a separate PR - the solution for now might be to allow the build to process with similar opt-in to unix-like system build tags, but document what the issues could be for unsupported platforms.
> Add unix-like build tags in locations other than app package

- internal/pkg/app/app_unix.go
- internal/pkg/app/appname/appname_unix_test.go
Fixes https://github.com/bufbuild/buf/issues/362.
Supplants https://github.com/bufbuild/buf/pull/363.
See https://github.com/cockroachdb/cockroach/issues/67216.
This doesn't certify that `app` features will actually work with all unix-like platforms, but on balance, allowing these builds seems better than blocking the builds, or actually setting up testing for each platform. If there is an issue down the road for an unsupported platform, we can fix it when we add support.
> Expand build tags in app packages

- internal/pkg/app/app_windows.go
Fixes #385 
Update the environment variables from camel case to all caps for windows to get correct cache, config and data directory paths
> Fix Environment Variables for Windows

- go.mod
- go.sum
- internal/buf/cmd/buf/buf_test.go
- internal/buf/cmd/buf/command/export/export.go
- internal/buf/cmd/buf/testdata/export/another/proto/another.proto
- internal/buf/cmd/buf/testdata/export/another/proto/buf.yaml
- internal/buf/cmd/buf/testdata/export/buf.work.yaml
- internal/buf/cmd/buf/testdata/export/other/proto/buf.yaml
- internal/buf/cmd/buf/testdata/export/other/proto/request.proto
- internal/buf/cmd/buf/testdata/export/other/proto/unimported.proto
- internal/buf/cmd/buf/testdata/export/proto/buf.yaml
- internal/buf/cmd/buf/testdata/export/proto/rpc.proto
- make/buf/scripts/brew.sh
- make/buf/scripts/release.bash
When we do `buf export`, we export all files from dependencies, even if they are not used as imports. This means, for example, that if you depend on googleapis, you get all 4000 files exported, even if you only import 1 file. This caused an OOM error for a customer.
If you are not excluding imports, this changes `buf export` so that you only export those files that you import. This is accomplished by building a merged image, and if you are going to export an import, checking if the file is in the merged image.
> Only export files from dependencies that are imported

- go.mod
- go.sum
- internal/pkg/git/cloner.go
- internal/pkg/git/git_test.go
Fixes https://github.com/bufbuild/buf/issues/419. The issue was caused when a user's default git branch name that would get checked out during `init` would be the same branch as they attempt to fetch with `branch=`, because git would refuse to update the checked out `HEAD`. By switching to a bare init, we don't have any ref checked out during fetch and this issue isnt possible. As a side effect of switching to a bare init, we can't checkout in the same dir as we fetch so use a separate worktree dir.
Verified that the flags work going back to with git 2.10 (Sept 2016)
> Use bare clones for git cloner

- go.mod
- go.sum
- internal/pkg/git/cloner.go
git-lfs needs a remote set: https://sourcegraph.com/github.com/git-lfs/git-lfs@7266ee06beb3fe0a641640322dc12bf40ea9dd29/-/blob/config/config.go?L223:20
Fixes https://github.com/bufbuild/buf/issues/424
> Add url as remote on git fetch

- cmd/protoc-gen-buf-check-breaking/main.go
- cmd/protoc-gen-buf-check-lint/main.go
- internal/buf/cmd/protoc-gen-buf-breaking/breaking.go
- internal/buf/cmd/protoc-gen-buf-lint/lint.go
- internal/buf/cmd/protoc-gen-buf-lint/lint_test.go
We have been notifying users of this via a message since January 2021. This now upgrades to making each of these plugins exit with code 1. Maintaining these binaries is having a cost, both in clutter of the releases, and just plain build time, and will only get worse when we add Windows support and releases.
The message printed:
```
protoc-gen-buf-check-breaking has been moved to protoc-gen-buf-breaking.
Use protoc-gen-buf-breaking instead.
As one of the few changes buf will ever make, protoc-gen-buf-check-breaking was deprecated and
scheduled for removal for v1.0 in January 2021. In preparation for v1.0, instead of just printing
out a message notifying users of this, this command now returns an error for every invocation
and will be completely removed when v1.0 is released.
The only …
```
> Error on all usage of protoc-gen-buf-check-breaking and protoc-gen-buf-check-lint

- internal/buf/cmd/buf/command/login/login.go
- internal/bufpkg/bufmodule/bufmodulecache/module_cacher.go
- internal/pkg/storage/storagetesting/storagetesting.go
The io/ioutil package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). Since PR #430 had already upgraded the project to Go 1.17, we can replace all usage of `io/ioutil` to `io` and `os` package.
I did not create an issue beforehand because this is a small PR and does not introduce any breaking change. I hope the maintainers don't mind
> refactor: move from io/ioutil to io and os package

- private/bufpkg/bufimage/bufimagemodify/csharp_namespace.go
- private/bufpkg/bufimage/bufimagemodify/csharp_namespace_test.go
- private/bufpkg/bufimage/bufimagemodify/testdata/csharpoptions/underscore/csharp.proto
- private/pkg/stringutil/stringutil.go
Fixes #445 
This updates the `csharp_namespace` transformation in **Managed Mode** to use `stringutil.ToPascalCase` so that we use an idiomatic C# namespace in the generated code. Previously package elements like `foo_bar` were translated to `Foo_bar` instead of `FooBar`.
> Fix C# namespace transformation

- make/buf/all.mk
- make/buf/scripts/release.bash
- make/go/dep_minisign.mk
- Add `minisign` as a dependency.
- Print out the directory that assets are located in, along with an `open` string that can be copy/pasted into the terminal.
> Fix make bufrelease

- private/buf/bufgen/bufgen.go
- private/buf/bufgen/config.go
- private/buf/bufgen/config_test.go
- private/buf/bufgen/generator.go
- private/buf/bufgen/testdata/v1/gen_success1.json
- private/buf/bufgen/testdata/v1/gen_success1.yaml
- private/bufpkg/bufimage/bufimagemodify/java_package.go
- private/bufpkg/bufimage/bufimagemodify/java_package_test.go
Re: https://github.com/bufbuild/buf/issues/465#issuecomment-907779934
This proposes a `java_package_prefix` option so that users can customize what prefix is used to generate the `java_package` value in **Managed Mode**.
This idea was originally suggested in Slack, with the following context:
```
It's not a super big deal for us if the package path changes as part of adopting Managed Mode,
but it's still a breaking change that affects all our current generated code. It'll make Managed
Mode a little tougher sell.
...
The issue right now is that it's not just the generated code that has a custom TLD as package prefix,
but also our Maven artifacts. E.g:
<groupId>tech.einride</groupId>
<artifactId>proto</artifactId>
This is a bit of a hurdle for smooth adoption.
```
> Add java_package_prefix option

- private/buf/cmd/buf/command/mod/modprune/modprune.go
- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufmodule/module.go
- private/bufpkg/bufmodule/util.go
- Make it so that `newModuleForBucket` and `newModuleForProto` are more independent.
- Do not always read the `documentation` from the `ReadBucket`, instead pass it as a parameter to `newModule`.
- Delete `NewModuleWithDependencyModulePins`.
- Add `DependencyModulePinsForBucket` and expand `PutDependencyModulePinsToBucket`.
- Replace unnecessary creates of `bufmodule.Modules` in `mod prune` and `mod update`.
> Simplify bufmodule

- .github/workflows/windows.yaml
- private/pkg/storage/storagetesting/storagetesting.go
- windows/setupDeps.ps1
This PR adds a cache for both Chocolatey and Go dependencies for faster builds and removes the `setupDeps.ps1` script, since we are using the `setup-go` action, and only need to install `protoc` using Chocolatey.
Refs: #478
> Clean up Windows Github Action

- private/bufpkg/bufmodule/bufmodulecache/bufmodulecache_test.go
- private/bufpkg/bufmodule/bufmodulecache/module_cacher.go
- private/bufpkg/bufmodule/bufmodulecache/module_reader.go
This adds a log message if we have a sum mismatch in the module cacher. This makes future diagnostics slightly better.
This also uses `storage.ReadPath` in one place.
> Add a warn-level log if the module cacher has a sum mismatch

- private/bufpkg/bufimage/bufimagemodify/php_namespace.go
- private/bufpkg/bufimage/bufimagemodify/php_namespace_test.go
- private/bufpkg/bufimage/bufimagemodify/ruby_package.go
- private/bufpkg/bufimage/bufimagemodify/ruby_package_test.go
- private/bufpkg/bufimage/bufimagemodify/testdata/phpoptions/underscore/php.proto
- private/bufpkg/bufimage/bufimagemodify/testdata/rubyoptions/underscore/ruby.proto
Similar in spirit to #472, but for `php_namespace` and `ruby_package`.
> Use stringutil.ToPascalCase in Image modifiers

- private/bufpkg/bufmodule/bufmodulecache/bufmodulecache_test.go
- private/bufpkg/bufmodule/bufmodulecache/module_cacher.go
- private/bufpkg/bufmodule/bufmodulecache/module_reader.go
- private/bufpkg/bufmodule/bufmodulecache/util.go
When using file locks with the module cache, we were doing the following:
- ReadLock
- CacheGet
- ReadUnlock
- If not exists or invalid sum:
- DelegateGet
- WriteLock
- CachePut
- WriteUnlock
This was already causing duplicate downloads because we were doing a DelegateGet if the CacheGet failed without having a write lock, see https://github.com/bufbuild/buf/pull/456. However, we didn't think this was an actual issue beyond duplicate downloads.
The problem is that when inside the ReadLock, another caller could be inside the WriteLock, modifying the underlying data in the cache. If this was happening, we could have inconsistent state for a caller that expects the cache to be stable.
Instead, we move to double locking:
- ReadLock
- CacheGet
- ReadUnlock
- If not exists or invalid sum:
- …
> Fix module caching

- private/buf/bufgen/generator.go
Previously we were sending an array with a single
empty element if the options were omitted.
> Only include parameters if non-empty

- make/buf/all.mk
- make/go/buf.mk
- make/go/dep_buf.mk
This allows us to use `buf` from `./cmd/buf` instead of from releases. We can turn this off selectively if there is a bug and we need to run `make generate`. This is similar to what we had in the past.
> Add ability to install buf directly in makego

- private/buf/bufcheck/buflint/buflint_test.go
- private/buf/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
- private/buf/bufcheck/buflint/testdata/comment_ignores_cascade/a.proto
See #161 and #243. This adds cascading for `ENUM_ZERO_VALUE_SUFFIX` at the enum level as well.
> Cascade ENUM_ZERO_VALUE_SUFFIX comment ignore from the enum level

- .github/workflows/windows.yaml
Change the cache to point at the Go module cache on Windows, fixes #522.
> Fix go module cache on Windows Github Actions

- private/buf/bufgen/generator.go
- private/bufpkg/bufimage/bufimagemodify/bufimagemodify.go
- private/bufpkg/bufimage/bufimagemodify/cc_enable_arenas.go
- private/bufpkg/bufimage/bufimagemodify/cc_enable_arenas_test.go
- private/bufpkg/bufimage/bufimagemodify/csharp_namespace.go
- private/bufpkg/bufimage/bufimagemodify/csharp_namespace_test.go
- private/bufpkg/bufimage/bufimagemodify/go_package.go
- private/bufpkg/bufimage/bufimagemodify/java_multiple_files.go
- private/bufpkg/bufimage/bufimagemodify/java_multiple_files_test.go
- private/bufpkg/bufimage/bufimagemodify/java_outer_classname.go
- private/bufpkg/bufimage/bufimagemodify/java_outer_classname_test.go
- private/bufpkg/bufimage/bufimagemodify/java_package.go
- private/bufpkg/bufimage/bufimagemodify/java_package_test.go
- private/bufpkg/bufimage/bufimagemodify/java_string_check_utf8.go
- private/bufpkg/bufimage/bufimagemodify/java_string_check_utf8_test.go
- private/bufpkg/bufimage/bufimagemodify/objc_class_prefix.go
- private/bufpkg/bufimage/bufimagemodify/objc_class_prefix_test.go
- private/bufpkg/bufimage/bufimagemodify/optimize_for.go
- private/bufpkg/bufimage/bufimagemodify/optimize_for_test.go
- private/bufpkg/bufimage/bufimagemodify/php_metadata_namespace.go
- private/bufpkg/bufimage/bufimagemodify/php_metadata_namespace_test.go
- private/bufpkg/bufimage/bufimagemodify/php_namespace.go
- private/bufpkg/bufimage/bufimagemodify/php_namespace_test.go
- private/bufpkg/bufimage/bufimagemodify/ruby_package.go
- private/bufpkg/bufimage/bufimagemodify/ruby_package_test.go
Fixes #485
This adds a `WARN` log similar to the one introduced for unused `override` modules in the `go_package_prefix` configuration, but for per-file overrides in general.
Using a `buf.gen.yaml` that includes an override for each file option for a non-existent filename, the user will see something along the lines of the following:
```yaml
version: v1
managed:
enabled: true
cc_enable_arenas: true
java_string_check_utf8: true
optimize_for: CODE_SIZE
override:
CSHARP_NAMESPACE:
buf/alpha/image/v1/image.proto: Buf.Alpha.Image.V1
foo/bar/baz.proto: Foo.Bar
CC_ENABLE_ARENAS:
buf/alpha/image/v1/image.proto: false
foo/bar/baz.proto: false
...
```
```sh
$ buf generate
WARN	CSHARP_NAMESPACE override for "foo/bar/baz.proto" was unused
WARN	CC_ENABLE_ARENAS override for "foo/bar/baz.proto" was …
```
> Managed Mode: Add warnings for missing file overrides

- private/buf/cmd/buf/command/mod/modprune/modprune.go
- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
This adds a directory argument that defaults to `.` to `buf mod update` and `buf mod prune`.
Support for taking a directory already existed, so this primarily exposes that through an argument.
> Add directory argument for `buf mod update` and `buf mod prune`

- .github/workflows/ci.yaml
- .github/workflows/windows.yaml
- Dockerfile.buf
- Dockerfile.workspace
- make/buf/all.mk
1.17.1 contains a security fix for archive/zip: https://groups.google.com/g/golang-announce/c/dx9d7IOseHw
> Update Go to v1.17.1

- private/buf/cmd/buf/command/push/push.go
Fixes #540, I took a look at the log statements in the `command` directory to make sure that we have new lines where approriate.﻿
> Add newline to push log message

- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/protoc/protoc.go
- private/buf/cmd/buf/command/version/usage.gen.go
- private/buf/cmd/buf/command/version/version.go
- private/pkg/app/appcmd/appcmd.go
- private/pkg/app/appcmd/appcmd_test.go
- private/pkg/app/appcmd/cobra.go
- private/pkg/bandeps/cmd/bandeps/main.go
- private/pkg/licenseheader/cmd/license-header/main.go
- private/pkg/spdx/cmd/spdx-go-data/main.go
- private/pkg/storage/cmd/ddiff/main.go
- private/pkg/storage/cmd/storage-go-data/main.go
Fixes https://github.com/bufbuild/buf/issues/535.
This moves `-h, --help, help` to stdout, and `--version` to `version, while preserving usage errors to stderr.
> Move help to stdout and --version to version

- CHANGELOG.md
- private/buf/bufcli/bufcli.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/breaking/breaking.go
- private/buf/cmd/buf/command/build/build.go
- private/buf/cmd/buf/command/generate/generate.go
- private/buf/cmd/buf/command/generate/generate_test.go
- private/buf/cmd/buf/command/lint/lint.go
- private/buf/cmd/buf/command/lsfiles/lsfiles.go
Re: #483
This builds upon #526 and removes all of the previously deprecated flags from `buf`. All of the tests that used deprecated flags are now removed.
Note that a couple `bufcli` helpers are kept so that we can more easily deprecate flags in the future (i.e. `bufcli.GetString[Slice]FlagOrDeprecatedFlag`).
> CLI V1: Remove all deprecated flags

- private/buf/bufgen/generator.go
- private/bufpkg/bufplugin/bufplugin.go
Fixes https://github.com/bufbuild/buf/issues/541
This removes all of the unnecessary error wrapping in the `buf generate` command, and makes slight improvements to the places where wrapping makes sense.
Now, when users run `buf generate` with duplicate plugins like so:
```yaml
version: v1
managed:
enabled: true
go_package_prefix:
default: github.com/bufbuild/buf/private/gen/proto/go
plugins:
- name: go
out: private/gen/proto/go
opt: paths=source_relative
- name: go
out: private/gen/proto/go
opt: paths=source_relative
```
They will see:
```sh
$ buf generate
Failure: file "buf/alpha/module/v1alpha1/module.pb.go" was generated multiple times
```
And for plugins that don't exist, they will see:
```sh
$ buf generate
Failure: could not find protoc plugin for name foo
```
> Remove unnecessary error wrapping in 'buf generate'

- private/buf/bufgen/generator.go
- private/bufpkg/bufplugin/bufplugin.go
- private/bufpkg/bufplugin/bufplugin_test.go
Fixes https://github.com/bufbuild/buf/issues/560
> The issue described above is only loosely related to this change - the only action item there was to improve our error messages (hence why this PR fixes the issue).
This builds upon https://github.com/bufbuild/buf/pull/564, and introduces a new `PluginResponse` type that includes the `PluginName` responsible for the creation of a given `CodeGeneratorResponse`.
This was tested with a variety of configurations, including:
```sh
$ buf generate
Failure: file "buf/alpha/image/v1/image.pb.go" was generated multiple times: once by plugin "buf.build/library/plugins/go:v1.27.1-1" and again by plugin "buf.build/library/plugins/go"
```
```sh
$ buf generate
Failure: file "buf/alpha/image/v1/image.pb.go" was generated multiple times: once by plugin …
```
> Include plugin name in 'buf generate' errors

- private/pkg/rpc/errors.go
- private/pkg/rpc/errors_test.go
This is useful for unwrapping just the message from
a wrapped RPC error.
> Add GetErrorMessage to rpc package

- private/bufpkg/bufplugin/bufplugin.go
This uses a representation of template versions that is not consistent with the front-end URLs, and it's not used anyway.
> Remove unused ParseTemplateVersion method

- CHANGELOG.md
- private/buf/bufcli/bufcli.go
- private/buf/bufwire/bufwire.go
- private/buf/bufwire/file_lister.go
- private/buf/cmd/buf/command/lsfiles/lsfiles.go
Not having this has been annoying me.
We also might want to add a flag such as `--root-relative` or so that strips the external paths.
> Add --include-imports to ls-files

- CHANGELOG.md
- private/pkg/git/cloner.go
- private/pkg/git/git_test.go
This should fix https://github.com/bufbuild/buf/issues/584. 
Apparently the submodule subcommand does not support the `--worktree` argument, and needs to be run from a checked out worktree. By changing the first checkout to use `git worktree` (https://git-scm.com/docs/git-worktree, available since git 2.6.7) and the later submodules command to run in the new worktree, git submodules seems to be ok.
Verified this locally with git 2.10 (Sept 2016), similar to https://github.com/bufbuild/buf/pull/421.
> Fix regression in recurse_submodules

- CHANGELOG.md
- private/buf/bufwire/bufwire.go
- private/buf/bufwire/file_lister.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/lsfiles/lsfiles.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref.go
Other potential names for this flag:
- `--as-image-paths`: I don't like this as it makes people understand what an Image is.
- `--as-import-paths`: Just seems long, and we don't use the terminology "import paths" anywhere else.
We can always easily change the flag name later.
> Add --strip flag to ls-files

- private/buf/cmd/buf/buf_test.go
I think these were made to check for exit code 1 when we deleted these for v1.0.0-rc1. I'd argue they aren't really testing anything anymore, other than commands fail on a non-existent flag. Expecting them causes extra test creation overhead.
> Delete tests for --input flags

- CHANGELOG.md
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/lsfiles/lsfiles.go
When you print out image paths, they are (properly) not slashed, so the paths we want to print out really are different, and aren't just stripped, they're potentially always slashed. This means they are “import paths”.
> Add more tests for ls-files and switch --strip to --as-import-paths

- CHANGELOG.md
- private/buf/cmd/buf/command/generate/testdata/insertion_point/test.txt
- private/buf/cmd/buf/command/generate/testdata/nested_insertion_point/gen/proto/insertion/test.txt
- private/buf/cmd/buf/command/protoc/internal/protoc-gen-insertion-point-receiver/main.go
- private/buf/cmd/buf/command/protoc/internal/protoc-gen-insertion-point-writer/main.go
- private/pkg/app/appproto/response_builder.go
Fixes #702 
We were guarding against duplicate files, but did not take into account whether or not the file contained an insertion point. The insertion point test was adapted to match the test case demonstrated in #702.
> Support multiple insertion points

- private/gen/proto/go/buf/alpha/registry/v1alpha1/doc.pb.go
- proto/buf/alpha/registry/v1alpha1/doc.proto
Small change from https://github.com/bufbuild/buf/pull/711, just wanted the naming to match `protosource`.
> Small nit change: `OneOf` -> `Oneof` to match protosource definitions

- .golangci.yml
- make/buf/all.mk
- make/go/dep_buf.mk
- make/go/dep_git_ls_files_unstaged.mk
- make/go/dep_go_fuzz.mk
- make/go/dep_golangci_lint.mk
- make/go/dep_jq.mk
- make/go/dep_license_header.mk
- make/go/dep_minisign.mk
- make/go/dep_protoc.mk
- make/go/dep_protoc_gen_go.mk
- make/go/dep_protoc_gen_go_grpc.mk
- private/pkg/git/git_test.go
This updates all makego dependencies, including the newest version of `golangci-lint`. New linters that have been added are enabled where they are desired.
> Update all makego dependencies

- CHANGELOG.md
- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
This creates a new repository service per remote across dependencies, and then resolves dependencies based on their remote.
Fixes #729
> Use a separate repository service per remote for resolving dependencies

- CHANGELOG.md
- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
The message displayed as part of an interactive `buf login` command
should refer to the Buf Schema Registry address that the user is
attempting to login to.
> Display correct remote in `buf login`

- private/buf/bufcli/bufcli.go
A user entering EOF (^D) when prompted does not warrant filing a bug
report.
> registry login: suppress bug report message on EOF

- go.mod
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/config/configinit/configinit.go
- private/bufpkg/bufcheck/bufbreaking/bufbreakingconfig/bufbreakingconfig.go
- private/bufpkg/bufcheck/buflint/buflintconfig/buflintconfig.go
- private/bufpkg/bufconfig/bufconfig.go
- private/bufpkg/bufconfig/write.go
- private/bufpkg/bufconfig/write_test.go
- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufmodule/bufmodulecache/bufmodulecache_test.go
- private/bufpkg/bufmodule/bufmoduletesting/bufmoduletesting.go
- private/bufpkg/bufmodule/module.go
Add `WriteConfigWithBreakingConfig`, `WriteConfigWithLintConfig`, and `WriteConfigWithVersion` options for the `bufconfig.WriteConfig` function to support more generic use cases of the `WriteConfig`.
Before this change, we are only using `bufconfig.WriteConfig` in the `buf config init` command, but we now need it to write configuration structures into our module cache so that we are persisting `breaking` and `lint` config in our cache for our module structure.
> Refactor the `WriteConfig` function for bufconfig for a generic use case

- private/bufpkg/bufcheck/bufbreaking/bufbreakingconfig/bufbreakingconfig.go
- private/bufpkg/bufcheck/buflint/buflintconfig/buflintconfig.go
As a part of #682, we are encoding the modules, but we need to have a `nil` check for mappers for the `Config` structures from the proto structures. Remote references stored in the BSR will not have configs stored and this needs to handle the `nil` case seamlessly.
As a follow-up, tests in `core` will need to be added with unmarshalling references from the `DownloadService`.
> Add `nil` check for `ConfigForProto` for `breaking` and `lint` configs

- private/bufpkg/bufcheck/bufbreaking/bufbreakingconfig/bufbreakingconfig.go
- private/bufpkg/bufcheck/buflint/buflintconfig/buflintconfig.go
- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufmodule/module.go
A small clean-up related to #682 re: https://github.com/bufbuild/buf/pull/781#discussion_r767933162
This moves the `nil` checks to the call sites and keeps the concerns of the constructors/mappers in the `bufbreakingconfig` and `buflintconfig` packages clean.
> Move `nil` checks out of `breaking` and `lint` mappers

- private/usage/usage.go
In 1.18, https://pkg.go.dev/runtime/debug#ReadBuildInfo returns true for tests, when it returned false in 1.17. The resulting `*debug.BuildInfo` has an empty `Main.Path`, which results in a panic.
> Fix private/usage for Golang 1.18

- CHANGELOG.md
This edits the first couple of points made in the `v1.0.0-rc9` release notes.
For the first point, we don't need to communicate internal API changes to our CLI users so it can be removed altogether. As for the second point, we should phrase these changes in terms of fixes and/or additions - the implementation details are irrelevant.
> Cleanup CHANGELOG.md for v1.0.0-rc9

- private/bufpkg/bufconfig/bufconfig.go
- private/bufpkg/bufconfig/write.go
- private/bufpkg/bufmodule/bufmodulecache/module_cacher.go
- private/bufpkg/bufmodule/module.go
Now that we have migrated to the `b3` digest, we are using the `breaking` and `lint` configs for the digest calculation. For remote references, we do not have any `breaking` and `lint` configs stored. Thus, when we construct the module based on the response we are receiving from the proto, we need to create the same default configurations that are created for modules from buckets without a `buf.yaml`.
Fixes: #790
> Default to the `v1beta1` configuration in the module constructor for proto structures

- private/bufpkg/bufimage/bufimage.go
- private/bufpkg/bufimage/image_test.go
Fixes #793
The workspace is processed deterministically (in the order specified by the `buf.work.yaml`), but the order was not preserved when the images are merged in [MergeImages](https://github.com/bufbuild/buf/blob/b87ac6eb1d295e39f6595d89f10b0adee51cc774/private/bufpkg/bufimage/bufimage.go#L141) because we use a `map` to handle duplicates. Now we preserve the order by adding the files in the same order they were provided.
> Fix image construction non-determinism

- private/buf/cmd/buf/command/config/configinit/configinit.go
- private/bufpkg/bufconfig/write.go
- private/bufpkg/bufconfig/write_test.go
This is a follow-up to address post-merge comments on #766.﻿
> Clean-up `WriteConfig` function

- CHANGELOG.md
Re: https://github.com/bufbuild/buf/issues/799 & https://github.com/bufbuild/buf/pull/718
This adds a note to the `CHANGELOG.md` about setting the `compiler_version` parameter in the `CodeGeneratorRequest`.
> Mention protoc version in CHANGELOG.md

- private/bufpkg/bufcheck/bufbreaking/bufbreaking.go
- private/bufpkg/bufcheck/buflint/buflint.go
Adding some helpers in `bufbreaking` and `buflint` to get the list of all categories and rules for `v1` and `v1beta1` configs. This is used to validate the rules on the server-side, so the full list of rules and categories need to be exposed from the internal layer.
Ref: #682
> Add helpers in `bufbreaking` and `buflint`

- .github/workflows/windows.yaml
- windows/test.ps1
This speeds up the windows workflow by:
- moving caches to D:\ where restoring cache is much faster
- not using chocolatey to install curl and zip (or anything else)
With these changes the windows workflow typically takes between 2 and 4 minutes. Previously it took around 9 minutes.
> Speed up the windows workflow

- private/pkg/testingextended/testingextended.go
It's useful to set go test's -timeout flag in different contexts, such
as during integration tests or when using verbose debugging or running
in a resource-constrained environment. Keeping such scenarios in mind,
it's additionally often useful to avoid internal timeouts during certain
tests by specifying a larger timeout duration. Unfortunately, this is
prone to error when the `go test` timeout exceeds the internal timeout,
which may not have been the intent of the test author, resulting in a
new, distinct and surprising failure.
Let's teach testingextended to expose `testing`'s global `timeout` flag
value so tests can refer to a duration that is guaranteed to exceed the
deadline of the test.
> testingextended: helper to get test timeout value

- private/buf/cmd/buf/command/beta/registry/repository/repositoryundeprecate/repositoryundeprecate.go
I left this off when adding undeprecate.
> Add missing NewErrorInterceptor to repository undeprecate

- CHANGELOG.md
- private/buf/bufgen/generator.go
- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/command/beta/registry/plugin/plugindeprecate/plugindeprecate.go
- private/buf/cmd/buf/command/beta/registry/plugin/plugindeprecate/usage.gen.go
- private/buf/cmd/buf/command/beta/registry/plugin/pluginundeprecate/pluginundeprecate.go
- private/buf/cmd/buf/command/beta/registry/plugin/pluginundeprecate/usage.gen.go
- private/buf/cmd/buf/command/beta/registry/template/templatedeprecate/templatedeprecate.go
- private/buf/cmd/buf/command/beta/registry/template/templatedeprecate/usage.gen.go
- private/buf/cmd/buf/command/beta/registry/template/templateundeprecate/templateundeprecate.go
- private/buf/cmd/buf/command/beta/registry/template/templateundeprecate/usage.gen.go
will also include warning message when user is using deprecated plugin/template in this PR
To deprecate a plugin: 
`buf beta registry plugin deprecate buf.build/owner/plugins/plugin [--message "please use buf.build/owner/plugins/newplugin"]`
To undeprecate a plugin:
`buf beta registry plugin undeprecate buf.build/owner/plugins/plugin`
When you run `buf generate` with a deprecated remote plugin in your `buf.gen.yaml`, you will get a warning message:
`WARN    Plugin "buf.build/owner/plugins/plugin" is deprecated: please use buf.build/owner/plugins/newplugin`
> CLI support for plugin and template deprecation

- private/bufpkg/bufmodule/bufmoduleref/validate.go
In preparation for #777, this removes extraneous validation methods that we no longer require on the client and server-side. We no longer want to store this information (and some of it will be stale soon, e.g. `branch`), so we need to make sure we are not validating against values we will not be storing in the future.
> Remove extraneous validation

- private/buf/cmd/buf/command/push/push.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref.go
This adds a `--track` option to `buf push`. When set, the module will be appended to the track(s) specified. Otherwise the module will be appended to the main track.
> Add buf push --track

- CHANGELOG.md
- private/bufpkg/buflock/buflock.go
- private/bufpkg/buflock/buflock_test.go
- private/bufpkg/buflock/lock_file.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref.go
This PR removes the writing of `branch`, `digest`, and `created_at` fields into the `buf.lock`.
This also means that we will not be reading those values out of future `buf.lock`, so those values will be the `nil`/zero values for the module pin sent to the server-side. This means, that if the server-side is still on the `b1` digest (which it currently is), a new commit will be written with a client that includes this change. If the server-side digest is migrated to `b3`, then this change does not present any issues.
> Remove `digest`, and `created_at` fields from the `buf.lock`

- private/pkg/testingextended/testingextended.go
This updates `GetTestTimeout` to return the time remaining until `t.Deadline()`. When there is no deadline it return 10 minutes.
This is needed because when running tests with goland, no `-test.timeout` is set by default.
> Set a default timeout in GetTestTimeout

- private/usage/usage.go
- private/usage/usage_unix.go
- private/usage/usage_windows.go
It seems that recently the name pattern used for Go's debug builds change, so our existing mitigation strategy is not sufficient. I have seen names in the shape of `/var/folders/ss/92w9dtp15l38qgbjgpvg4f580000gn/T/__debug_bin3790439195`, so this new check should handle both.
Since we're checking by name prefix of the last part of the executable, we no longer need to differentiate it between Windows and other platforms.
> Allow execution of debug builds

- .github/workflows/buf.yaml
We've been running our Github Actions on `0.56.0`, upgraading everything up to `v1.0.0-rc11`, our most recent version, to keep our dogfooding processes up-to-date.﻿
> Upgrade `buf` version to `v1.0.0-rc11` for Github Actions

- private/buf/cmd/buf/command/beta/registry/template/templateversion/templateversionlist/templateversionlist.go
This PR fixes the command description for the `buf beta registry template version list` command, which erroneously describes the command as listing _plugins_. Before:
"List versions for the specified plugin."
Now:
"List versions for the specified template."
> Fix command short description

- CHANGELOG.md
- private/bufpkg/bufmodule/bufmodule.go
Commits should be a part of the `b3` digest, otherwise changes where only dependencies are updated will not be detected.
Note this will create a cache invalidation when first run/upgraded since it's a digest change.
> Add dependency commits to `b3` digest

- CHANGELOG.md
- private/bufpkg/buflock/buflock.go
- private/bufpkg/buflock/buflock_test.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref.go
Now that we've merged and deployed a change to the server-side to return the full `ModulePin` structure for dependencies, we can safely remove the `branch` field from the `buf.lock` without breaking backwards compatibility for older clients.
It should be noted that if a user downgrades their client, they would need to clear their cache (since the digest has not changed, but there is client-side validation for the `branch` field in older clients), but otherwise this is backwards compatible.
Refs #777
> Remove `branch` from `buf.lock`

- CHANGELOG.md
- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
Check the token and username provided when calling `buf registry login`.
If the token is invalid, we return an error and if the user resolved from the token does not match the username provided, we return an error.
Fixes: #861
> Check user provided token during `buf registry login`

- CHANGELOG.md
- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/command/push/push.go
This unhides `buf push --track` and `buf beta registry track`
> Expose tracks commands

- private/pkg/thread/thread.go
We want context cancellation or timeout to always take precedence over
an unblocked semaphore, so we never start goroutines that can't
successfully complete their work. We're very close to that goal right
now, but there's a timing bug in our logic.
Select chooses pseudorandomly from the unblocked, non-default cases. No
matter what checks we do beforehand, code like this isn't quite correct:
```go
select {
case <-ctx.Done():
// abort
case <-semaphoreC:
// work
}
```
Under load, it's likely that a fair bit of time has elapsed between the
previous checks and this select; since the goroutine is blocked on the
channel reads, it gets parked and some other goroutine has a chance to
run. Once this goroutine is unblocked and runs, it's entirely possible
that _both_ the `ctx.Done()` and …
> pkg/thread: fix select precedence

- private/pkg/thread/thread.go
In modern production environments, NumCPU is a poor estimate of the
actual parallelism available: it does consult the population count of
the cpuset mask (if any), but doesn't account for cgroups v1 or v2. Both
are commonly used in containerized environments.
The intention of this code is (I think?) to prevent us from burning
memory on initial stacks for zillions of goroutines, so we should
just use GOMAXPROCS: by definition, it's the maximum number of
goroutines that can run in parallel.
> pkg/thread: use GOMAXPROCS instead of NumCPU

- go.mod
- private/pkg/thread/thread_test.go
It's difficult to test all the timing conditions in Parallelize, but we
can easily test the most basic use cases.
> pkg/thread: add a simple test

- private/buf/bufcli/bufcli.go
- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/command/breaking/breaking.go
- private/buf/cmd/buf/command/build/build.go
- private/buf/cmd/buf/command/export/export.go
- private/buf/cmd/buf/command/generate/generate.go
- private/buf/cmd/buf/command/lint/lint.go
- private/buf/cmd/buf/command/lsfiles/lsfiles.go
- private/buf/cmd/buf/command/mod/modopen/modopen.go
- private/buf/cmd/buf/command/mod/modprune/modprune.go
- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
- private/buf/cmd/buf/command/push/push.go
- private/pkg/app/appcmd/appcmd.go
This is basically a code cleanup pass. In [v1.0.0-rc1](https://github.com/bufbuild/buf/releases/tag/v1.0.0-rc1), we made all of these commands and flags error, so this PR functionally is a no-op, but it cleans up the codebase going forward. After about five months, we can move from custom errors to normal not found errors.
> Delete all already-deleted commands and flags

- private/buf/cmd/buf/command/alpha/protoc/errors.go
- private/buf/cmd/buf/command/generate/generate.go
Just a small nit. The build vs. compile distinction is likely to produce confusion. Fortunately, "compile" is barely used here in the CLI but it's nonetheless worthwhile to remove it.
> Remove compile term from public text

- private/buf/cmd/buf/command/breaking/breaking.go
This strikes me as more intuitive and also more in line with the `Short` description.
> Change `Use` text for `buf breaking`

- CHANGELOG.md
- private/buf/bufwork/workspace_builder.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/workspace_test.go
The behaviour of the `--config` flag for workspaces is not immediately apparent to users. If a config contains [build configurations](https://docs.buf.build/configuration/v1/buf-yaml#build), for example, then that does not apply seamlessly to all modules across the workspace, and the build will error. Since this behaviour is very brittle, we have made the decision to disable the `--config` flag altogether for workspaces.
> Disable config override for workspaces

- .golangci.yml
- make/go/dep_golangci_lint.mk
- private/pkg/rpc/headers.go
- private/pkg/rpc/rpcauth/rpcauth.go
This updates `golangic-lint` to `v1.44.0` and addresses some of the issues with the `forcetypeassert` plugin that were previously uncaught (they were caught in the upgrade).
There have been several new linters added in this release:
- [containdctx](https://github.com/sivchari/containedctx)
- [decorder](https://gitlab.com/bosi/decorder)
- [errchkjson](https://github.com/breml/errchkjson)
- [grouper](https://github.com/leonklingele/grouper)
- [maintidx](https://github.com/yagipy/maintidx)
I don't think we want to add any of them - the `errchkjson` one is interesting, but we actually encourage that we check all of our errors so it's not really useful in our case.
> Update golangci-lint to v1.44.0

- CHANGELOG.md
- README.md
- private/buf/bufcli/bufcli.go
- private/buf/bufcli/bufcli_test.go
- private/buf/bufgen/bufgen.go
- private/buf/bufgen/config.go
- private/buf/bufgen/generator.go
- private/buf/bufwire/module_config_reader.go
- private/buf/bufwork/bufwork.go
- private/buf/cmd/buf/command/breaking/breaking.go
- private/buf/cmd/buf/command/build/build.go
This is a nit and should _not_ set back the 1.0 release. But I think that now is a good time to effect standardization across CLI, docs, blog, etc. Happy to discuss if there are strong objections to this, but I do think that it's a good practice to introduce capitalization only for _products_, not technical terms.
> Change capitalization of image and managed mode

- private/bufpkg/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
- private/pkg/protosource/enum.go
- private/pkg/protosource/file.go
- private/pkg/protosource/message.go
- private/pkg/protosource/protosource.go
- Trim leading dots from Extendee, TypeName, InputType & OutputType for consistency when using protosource. 
I took a look if this could use `protosource.Message`'s on which we could get their `FullName()`, but I think that requires a much larger refactor (and probably discussion). To make it so that I don't have `strings.TrimPrefix` throughout the image filtering code, doing it here seems most clean.
- Add `Parent` to enums, as enums may be nested in messages.
I'll add the partial image PR on top of this soon (https://github.com/bufbuild/buf/pull/949), separating this out as it also touches other code like lint.
> Enum parents and leading dot consistency across protosource

- .golangci.yml
We have `govet` listed twice. This commit pipes the list through `sort
-u`, so we should have a nice clean list now.
> golangci-lint: remove duplicated linter

- CHANGELOG.md
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/mod/internal/internal.go
- private/bufpkg/bufconfig/get.go
- private/bufpkg/bufconfig/write.go
- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufmodule/module.go
In preparation for `v1`, we should be moving all our default configurations to `v1` instead of `v1beta1`.
> Default to `v1` config instead of `v1beta1`

- private/bufpkg/bufprotoplugin/cmd/protoc-gen-go-api/main.go
- private/bufpkg/bufprotoplugin/cmd/protoc-gen-go-apiclientgrpc/main.go
- private/pkg/protogenutil/protogenutil.go
This is to handle name collision of request and response fields in `protoc-gen-go-api` and `protoc-gen-go-apiclientgrpc`,
for example, if both request and response have fields `payload`, the response field is now named as `payloadResponse`. 
Alternatively, we can just name the field to `_`, as this will be safer to prevent other collision (e.g. there might be another field called `payloadResponse` already) but the interface generated will have unclear argument names.
> handle name collision of request and response fields in generation

- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
These need to be detectable in the API to decide if the error should be
returned to the user or wrapped.
> Add sentinel error definitions for user errors on image filter

- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
This PR adds logic to trim new lines and remove spaces from the user-supplied token.
In our docs for [CI authentication](https://docs.buf.build/bsr/authentication#ci-authentication) we have the following:
```
echo ${BUF_API_TOKEN} | buf registry --username ${BUF_USER} --token-stdin
```
Some users might be using `echo -n` and others might not. Before we added logic for validating tokens in https://github.com/bufbuild/buf/issues/861 the new line didn't matter, worst case you got an extra line in your .netrc file following the `password` field.
But now we're sending this token to the backend for validation, and `token\n` will result in an error:
```
Failure: invalid token provided
```
Again, we could tell users to `echo -n`, but to improve the user experience let's just trim the lines and …
> Remove space and new line from token

- private/gen/proto/go/buf/alpha/registry/v1alpha1/repository_commit.pb.go
- proto/buf/alpha/registry/v1alpha1/repository_commit.proto
This just adds a comment directly setting ListRepositoryCommitsByBranchRequest.page_token to a commit id.
> Clarify page_token in ListRepositoryCommitsByBranchRequest

- .github/workflows/buf.yaml
- .github/workflows/ci.yaml
- .github/workflows/previous.yaml.disabled
- .github/workflows/windows.yaml
- Dockerfile.buf
- Dockerfile.workspace
- go.mod
- go.sum
- make/buf/all.mk
- make/go/dep_buf.mk
- make/go/dep_git_ls_files_unstaged.mk
- make/go/dep_go_fuzz.mk
- make/go/dep_golangci_lint.mk
- make/go/dep_jq.mk
- make/go/dep_license_header.mk
- make/go/dep_protoc.mk
- make/go/dep_protoc_gen_go.mk
- make/go/dep_protoc_gen_go_grpc.mk
- make/go/go.mk
Docker images should be released first.
> Upgrade to Go 1.18

- CHANGELOG.md
- private/usage/usage.go
This is currently breaking our Homebrew build: https://github.com/bufbuild/buf/issues/1013
Once this is merged, we will make a `v1.1.1` release.
> Temporarily remove `check` from `init` in private usage

- private/buf/bufformat/formatter.go
- private/buf/bufformat/formatter_test.go
- private/buf/bufformat/testdata/proto2/enum/v1/enum.golden.proto
- private/buf/bufformat/testdata/proto2/enum/v1/enum_trailing_comment.golden.proto
- private/buf/bufformat/testdata/proto2/enum/v1/enum_trailing_comment.proto
- private/buf/bufformat/testdata/proto2/enum/v1/enum_value_trailing_comment.golden.proto
- private/buf/bufformat/testdata/proto2/enum/v1/enum_value_trailing_comment.proto
- private/buf/bufformat/testdata/proto2/extend/v1/empty.golden.proto
- private/buf/bufformat/testdata/proto2/message/v1/message.golden.proto
- private/buf/bufformat/testdata/proto2/message/v1/message_options.golden.proto
- private/buf/bufformat/testdata/proto2/message/v1/multiple_nested.golden.proto
- private/buf/bufformat/testdata/proto2/message/v1/nested.golden.proto
- private/buf/bufformat/testdata/proto2/option/v1/option.golden.proto
- private/buf/bufformat/testdata/proto2/option/v1/option_array.golden.proto
- private/buf/bufformat/testdata/proto2/option/v1/option_message_field.golden.proto
- private/buf/bufformat/testdata/proto2/option/v1/option_name.golden.proto
- private/buf/bufformat/testdata/proto2/option/v1/single_compact_option.golden.proto
- private/buf/bufformat/testdata/proto2/option/v1/single_compact_option.proto
- private/buf/bufformat/testdata/proto2/utf8/v1/utf8.golden.proto
- private/buf/bufformat/testdata/proto2/utf8/v1/utf8.proto
- private/buf/bufformat/testdata/proto3/all/v1/all.golden.proto
- private/buf/bufformat/testdata/proto3/header/v1/unused_import.golden.proto
- private/buf/bufformat/testdata/proto3/header/v1/unused_import.proto
- private/buf/bufformat/testdata/proto3/literal/v1/literal_comments.golden.proto
- private/buf/bufformat/testdata/proto3/literal/v1/special_literal.golden.proto
> Fix formatting edge cases

- Dockerfile.buf
Fixes [CVE-2022-0778](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0778)
Closes #1028
> Bump alpine from 3.15.1 to 3.15.2

- CHANGELOG.md
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/format/format.go
- private/pkg/app/appcmd/appcmdtesting/appcmdtesting.go
Fixes https://github.com/bufbuild/buf/issues/1030.
This makes it so that `buf format` exits with a non-zero exit code if files were not already formatted. Common invocations:
```
$ buf format -d --exit-code
$ buf format --exit-code >/dev/null
```
> Add --exit-code to buf format

- CHANGELOG.md
- private/buf/bufformat/formatter.go
- private/buf/bufformat/testdata/proto3/all/v1/all.golden.proto
- private/buf/bufformat/testdata/proto3/file/v1/option.golden.proto
- private/buf/bufformat/testdata/proto3/file/v1/option.proto
This updates the file option sorting function so that default file options are sorted before custom options. For example,
```protobuf
syntax = "proto3";
import "custom.proto";
option cc_enable_arenas = true;
option java_multiple_files = true;
option (file_option) = true;
```
> Format default file options before custom file options

- README.md
It's always on a new line, it hasn't provided any lift in followers, I think we should just delete it - it seems out of place.
> Delete Twitter badge

- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
If a user sends a SIGINT to `buf`, the top-level application context is
cancelled and signal masks are reset. However, during an interactive
login the context is not respected; for example, it takes _two_ SIGINTs
to interrupt the process.
Ideally we could just trigger an I/O timeout by setting the deadline on
stdin, but when stdin is connected to a terminal the underlying fd is in
blocking mode making it ineligible. As changing the mode of stdin is
dangerous, this change takes an alternate approach of simply returning
early.
Note that this does not gracefully handle the case where the terminal is
in no-echo mode, as is the case when prompting for a password
interactively.
> registry login: handle context cancel (SIGINT)

- private/bufpkg/bufprotoplugin/cmd/protoc-gen-go-apiclientconnect/main.go
- private/gen/proto/apiclientconnect/buf/alpha/registry/v1alpha1/registryv1alpha1apiclientconnect/registryv1alpha1apiclientconnect.pb.go
The `apiclientconnect` plugin did not check for nil on the `addressMapper` option, which caused usage in `buf/core` to fail due to it not using an address mapper.
This adds a nil check to the plugin generated code and if it is nil, the client construction simply uses the address passed in.  Otherwise, it maps the `addressMapper` function over the given address.
> Add nil check for address mapper to apiclientconnect plugin

- private/buf/bufcli/bufcli.go
This re-adds `NewConfig` and passes the `config.TLS` to the http client.
https://github.com/bufbuild/buf/commit/97f8a3e15a40d7ba14f4bd961e7f3479b4ce826d#diff-73cbaebe6766a371dfca1849d8942ec87a6e1e7b808634e5d97a3d146599770aL821-L824
> Add tls config to client

- .pre-commit-hooks.yaml
Addresses #1077 .
---
Define official pre-commit hooks so users can reference the buf hooks directly.
For `buf lint` and `buf format`, given a standard configuration (i.e. a `buf.yaml` or `buf.work.yaml` in the repo root), zero-arg invocations should function.
```yaml
repos:
- repo: https://github.com/bufbuild/buf
hooks:
- id: buf-lint
- id: buf-format
```
Breaking change detection requires a previous version to compare against, which typically is not included in the source repository. Thus, `buf breaking` needs additional configuration to function properly.
Users with `buf.yaml` or `buf.work.yaml` not in the repo root need to specify the directory in the `args` list. Similarly, any custom arguments should be specified in the `args` list. Multiple instances can be specified if there are …
> Define pre-commit hooks

- private/bufpkg/bufcheck/bufbreaking/bufbreakingconfig/bufbreakingconfig.go
- private/bufpkg/bufcheck/buflint/buflintconfig/buflintconfig.go
Currently, we create a deterministic JSON structure for breaking and
lint configs for the `b3` digest. However, we should not be sorting
in-place when creating these structures, since it mutates the underlying
configs. Instead, we should be creating a copy.
> Do not sort in place when converting breaking and lint configs to JSON

- private/buf/buffetch/internal/internal.go
- private/buf/bufformat/formatter.go
- private/buf/bufwork/bufwork.go
- private/buf/bufwork/workspace_builder.go
- private/buf/cmd/buf/command/alpha/protoc/flags_unix.go
- private/buf/cmd/buf/command/alpha/protoc/flags_windows.go
- private/bufpkg/bufanalysis/bufanalysis.go
- private/bufpkg/bufcheck/buflint/internal/buflintv1/buflintv1.go
- private/bufpkg/bufimage/bufimagemodify/bufimagemodify.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufstudioagent/bufstudioagent_test.go
- private/bufpkg/bufstudioagent/plain_post_handler.go
- private/gen/proto/api/buf/alpha/registry/v1alpha1/registryv1alpha1api/resolve.pb.go
- private/gen/proto/apiclientconnect/buf/alpha/registry/v1alpha1/registryv1alpha1apiclientconnect/resolve.pb.go
- private/gen/proto/connect/buf/alpha/registry/v1alpha1/registryv1alpha1connect/resolve.connect.go
- private/pkg/app/appproto/appproto.go
- private/pkg/app/appproto/appprotoexec/appprotoexec.go
- private/pkg/storage/diff.go
- private/pkg/stringutil/stringutil.go
- proto/buf/alpha/registry/v1alpha1/resolve.proto
https://groups.google.com/g/golang-announce/c/SNruPJUSFz0/m/8QKkkMpJAAAJ
- `gofmt` has changed to deal with comments, this now formats the comments.
- `io/ioutil` is now a failing check with `staticcheck` - `ioutil.ReadAll` was deprecated and replaced with `io.ReadAll` in 1.16.
Otherwise, we're Golang 1.19 ready!
> Update to pass make with Golang 1.19

- make/go/dep_protoc.mk
There are now binaries of protoc compiled for arm64 (which avoid the
requirement of using Rosetta).
> Support protoc on arm64

- private/pkg/licenseheader/licenseheader.go
> Add `bazel` extensions to license header

- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig.go
- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig_test.go
- private/bufpkg/bufplugin/bufpluginconfig/config.go
- private/bufpkg/bufplugin/bufpluginconfig/get.go
- private/bufpkg/bufplugin/bufpluginconfig/testdata/failure/invalid-empty-version.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/failure/invalid-multiple-languages.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/archive/buf.plugin.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/go/buf.plugin.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/npm/buf.plugin.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/options/buf.plugin.yaml
- private/bufpkg/bufplugin/bufpluginconfig/usage.gen.go
- private/bufpkg/bufplugin/bufpluginref/bufpluginref.go
- private/bufpkg/bufplugin/bufpluginref/bufpluginref_test.go
- private/bufpkg/bufplugin/bufpluginref/plugin_identity.go
- private/bufpkg/bufplugin/bufpluginref/usage.gen.go
This adds a simple version of the `buf.plugin.yaml`. Some fields (e.g. `deps`, better `opts`, etc) are not included for now, but they will be added later on.
```yaml
version: v1
name: buf.build/grpc/go
opts:
- paths=source_relative
runtime:
go:
min_version: v1.18
deps:
- "google.golang.org/grpc:v1.32.0"
```
This takes some inspiration from the [bufpluginconfig](https://github.com/bufbuild/buf/blob/main/private/bufpkg/bufpluginconfig/bufpluginconfig.go) package that already exists, but adapts some of the keys and internal implementation so that we separate the `ExternalConfig` from the internal `Config` representation. There are a couple things to consider with this one:
**Structured options**
Not all plugin options are expressed as key, value pairs. For example, `protoc-gen-java` has [an …
> Add user-facing buf.plugin.yaml

- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig.go
- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig_test.go
- private/bufpkg/bufplugin/bufpluginconfig/config.go
- private/bufpkg/bufplugin/bufpluginconfig/testdata/failure/invalid-multiple-languages.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/archive/buf.plugin.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/go/buf.plugin.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/npm/buf.plugin.yaml
This revises the `buf.plugin.yaml` according to the feedback in #1210. Specifically, this covers the following:
* Remove `archive` runtime config
* Simplify runtime configuration handling
* Use `modfile.GoVersionRE.MatchString`
* Cleanup `bufpluginconfig.Config` comment
* Use separate runtime configuration shapes (e.g. separate `go` and `npm` runtime keys).
Note that there's one `TODO` left in the implementation surrounding `npm` runtime dependency validation. For now, we permit any non-empty string for the version. There might be some good solutions for this to capture exactly what `npm` does [not] support, but that isn't handled for now - we'll need to follow-up here.
> Refactor and simplify buf.plugin.yaml configuration

- private/buf/cmd/buf/command/beta/plugin/pluginpush/pluginpush.go
- private/bufpkg/bufplugin/bufplugin.go
- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig.go
- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig_test.go
- private/bufpkg/bufplugin/bufpluginconfig/config.go
- private/bufpkg/bufplugin/bufpluginconfig/testdata/failure/invalid-empty-plugin-version.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/failure/invalid-empty-version.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/failure/invalid-multiple-languages.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/failure/invalid-plugin-version.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/go/buf.plugin.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/npm/buf.plugin.yaml
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/options/buf.plugin.yaml
- private/bufpkg/bufplugin/plugin.go
This adds the `plugin_version` key to the `buf.plugin.yaml` file. This requires that users specify the version of the underlying plugin implementation (e.g. the `protoc-gen-connect-go` binary has a version of `v0.2.0`).
> Add plugin_version to buf.plugin.yaml

- private/bufpkg/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
Change ENUM_ZERO_VALUE_SUFFIX to match the full value name, instead of only checking the suffix.
Previously no lint rule would catch a zero value with "stuff in the middle", eg `TYPE_NAME_OTHER_STUFF_UNSPECIFIED`.
> Change ENUM_ZERO_VALUE_SUFFIX to match the full value name

- private/bufpkg/bufplugin/bufplugindocker/docker.go
- private/bufpkg/bufplugin/bufplugindocker/docker_test.go
We should prefix 'plugins.' to the image tag when building locally and
publishing (to ensure we publish to the proper OCI registry subdomain).
> prefix 'plugins.' when building/publishing images

- private/bufpkg/bufplugin/bufplugindocker/docker_test.go
- private/bufpkg/bufplugin/bufplugindocker/registry_auth_config_test.go
Currently, the Docker tests are occassionally hitting a 10s delay on
shutdown when closing the buildkit session. This appears to be due to
incorrect logic when upgrading the connection from HTTP/1.1 to HTTP/2.
The Docker client API doesn't send the required HTTP2-Settings header
and so the h2c handler doesn't upgrade the connection properly.
Update the Docker engine implementation for tests to correctly upgrade
to a H2C connection, fixing the delay on close.
Update some additional tests in this package to support parallel
execution.
> fix connection upgrade for Docker tests

- CHANGELOG.md
- private/bufpkg/bufstudioagent/bufstudioagent_test.go
- private/bufpkg/bufstudioagent/plain_post_handler.go
Currently we are defaulting to the gRPC protocol in Studio Agent,
however, we are able to support `application/json` and `application/proto`
with the Connect protocol. This just refactors the client options so that
we are setting protocol and codec options based on the content-type.
> Support protocol and encoding client options based on content-type in Studio Agent

- private/buf/bufprint/bufprint.go
- private/buf/bufprint/curated_plugin_printer.go
- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
After a successful push of a curated plugin to the BSR, we should print
out details of the newly published plugin (in particular, the revision
will be useful as it is incremented on every update).
> BSR-320: print curated plugin status after push

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
When a plugin already exists with the same metadata and image digest in
the BSR, we should handle the error more gracefully (it doesn't really
indicate an error).
> BSR-322: gracefully handle plugin exists

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
- private/bufpkg/bufplugin/bufplugindocker/docker.go
In order to support building images on M1 for local development and testing, add a hidden `--target` CLI argument which can be used to override the default architecture.
> add hidden target argument for local arm64 dev

- private/bufpkg/bufapimodule/bufapimodule.go
- private/bufpkg/bufapimodule/module_resolver.go
Use GetRepositoryCommitByReference instead of GetModulePins for module resolver.
We expect the `resolveService` is only be used for dependency resolving, for something that looks up the commit by a reference we can use a more generic and straightforward endpoint `repositoryCommitService.GetRepositoryCommitByReference`.
> use GetRepositoryCommitByReference for module resolver

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
- private/bufpkg/bufplugin/bufplugindocker/docker.go
- private/bufpkg/bufplugin/bufplugindocker/docker_test.go
Update to use the digest returned from push (instead of build) as they
don't match and remote execution fails with the build image digest.
> BSR-355: use image push digest

- private/gen/proto/api/buf/alpha/registry/v1alpha1/registryv1alpha1api/webhook.pb.go
- private/gen/proto/apiclientconnect/buf/alpha/registry/v1alpha1/registryv1alpha1apiclientconnect/webhook.pb.go
- private/gen/proto/connect/buf/alpha/registry/v1alpha1/registryv1alpha1connect/webhook.connect.go
- private/gen/proto/go/buf/alpha/registry/v1alpha1/webhook.pb.go
- proto/buf/alpha/registry/v1alpha1/webhook.proto
The docs at https://connect.build/docs/protocol describe `application/proto`,
not `application/protobuf`.  Some minor spacing edits too.
> Fix content-type to application/proto in webhook docs

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
When creating plugins, start initial revisions at 1 instead of 0.
> BSR-374: start initial revision at 1

- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/command/beta/registry/webhook/webhookcreate/usage.gen.go
- private/buf/cmd/buf/command/beta/registry/webhook/webhookcreate/webhookcreate.go
Example usage:
```
buf beta registry webhook create \
--owner="admin-user" \
--repository="api" \
--callback_url="https://bufbuild.internal/buf.alpha.webhook.v1alpha1.EventService/Event" \
--event="WEBHOOK_EVENT_REPOSITORY_PUSH"
```
> Add webhook beta command in buf cli along with create webhooks

- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/command/beta/registry/webhook/webhookcreate/webhookcreate.go
- private/buf/cmd/buf/command/beta/registry/webhook/webhookdelete/usage.gen.go
- private/buf/cmd/buf/command/beta/registry/webhook/webhookdelete/webhookdelete.go
- private/buf/cmd/buf/command/beta/registry/webhook/webhooklist/usage.gen.go
- private/buf/cmd/buf/command/beta/registry/webhook/webhooklist/webhooklist.go
Create:
```
buf beta registry webhook create \ 
--owner="achiu" \
--repository="petapis" \
--callback-url="https://bufbuild.test/buf.alpha.webhook.v1alpha1.EventService/Event" \
--event="WEBHOOK_EVENT_REPOSITORY_PUSH" \
--remote bufbuild.test
```
Delete:
```
buf beta registry webhook delete --id="some_id" --remote bufbuild.test
```
Listing:
```
buf beta registry webhook list --owner="achiu" --repository="petapis" --remote bufbuild.test
```
> Add webhook delete and list commands to beta and fixup create

- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig.go
- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig_test.go
- private/bufpkg/bufplugin/bufpluginconfig/config.go
- private/bufpkg/bufplugin/bufpluginconfig/testdata/success/go/buf.plugin.yaml
- private/bufpkg/bufplugin/bufpluginref/bufpluginref.go
Remove double ':' from plugin reference and instead split out revision
to a separate field. This will coordinate updates planned for
buf.gen.yaml with buf.plugin.yaml and also allow for revision to be
unset.
> BSR-369: update plugin dependencies to a struct

- private/gen/proto/go/buf/alpha/registry/v1alpha1/plugin_curation.pb.go
- proto/buf/alpha/registry/v1alpha1/plugin_curation.proto
Update GetLatestCuratedPlugin to document that the version parameter is
optional.
> BSR-379: document version can be optional

- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref.go
- private/bufpkg/bufmodule/bufmoduleref/module_reference_test.go
- private/bufpkg/bufmodule/bufmoduleref/util.go
this make the `ModuleReferenceForString` support reference with slash (e.g. `buf.build/bufbuild/buf:test/draft`), as both tag and draft should support it
> ModuleReferenceForString support reference with slash

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
- private/bufpkg/bufplugin/bufplugindocker/bufplugindocker.go
In order to make it more flexible for plugin authoring, first check for
a `Dockerfile.plugin` and if not found fall back to looking for a
`Dockerfile`.
> allow Dockerfile.plugin or Dockerfile

- private/buf/bufcli/bufcli.go
- private/pkg/transport/http/httpclient/client.go
- private/pkg/transport/http/httpclient/httpclient.go
- private/pkg/transport/http/httpclient/httpclient_test.go
This merges the two http clients in `buf` into one client that handles all the concerns.
The previous `http2client` was created to be able to use cleartext because the `http2.Transport` struct was the only way to configure `AllowHTTP`.  Therefore, users needed to use the `http2client` if they wanted cleartext and the regular `httpclient` for everything else.  
This essentially takes what both clients were doing and combines them into one interface.  If a callsite requests H2C, then the client will use `http2.Transport` with `AllowHTTP`.  For all other client constructions, the regular `http` client is used.  
Finally, instead of returning a struct with a nested `http.Client`, this simply returns the client straightaway.  The previous implementation only seemed to have the wrapping struct …
> Merge http clients for ease of use

- private/bufpkg/bufmodule/bufmoduleref/module_reference_test.go
- private/bufpkg/bufmodule/bufmoduleref/util.go
this fix the issue of `ModuleReferenceForString` handling a remote with port (e.g. `localhost:8080`)
> fix ModuleReferenceForString with port in remote

- CHANGELOG.md
- private/buf/cmd/buf/command/beta/studioagent/studioagent.go
For CORS policies, the origin needs to be explicit, including the URL scheme.
Fixes #1310
> Default origin for Studio Agent should contian URL scheme

- private/buf/cmd/buf/buf.go
Make sure timeout has no timeout by default. Builder's timeout is inaccessible within each `NewCommand` function, so we need to declare it from the caller side.
> [bsr-360] No timeout for studio agent command

- CHANGELOG.md
- private/bufpkg/bufstudioagent/bufstudioagent_test.go
- private/bufpkg/bufstudioagent/plain_post_handler.go
Apparently, when doing [`conn.Close()`](https://github.com/bufbuild/buf/blob/bfa9bc47d59baf3d2487660044c7d92ffbc192f4/private/bufpkg/bufstudioagent/bufstudioagent_test.go#L194) in the test, to fake a server-closed connection, it's mapped sometimes as `connect.CodeUnavailable` instead of `connect.CodeUnknown`, that's what's causing the flakiness.
Dig into `connect-go`, and it's being returned [in the envelope](https://github.com/bufbuild/connect-go/blob/713199600fa7bc3a47957c910ddde9a85253036f/envelope.go#L178), by reading the error [from the request](https://github.com/bufbuild/connect-go/blob/713199600fa7bc3a47957c910ddde9a85253036f/duplex_http_call.go#L144).
The error that's being triggered is on the Connect's [`httpClient.Do`](https://github.com/bufbuild/connect-go/blob/713199600fa7bc3a …
> [bsr-383] Fix flaky studio agent test

- private/pkg/app/appflag/builder.go
Fixes https://linear.app/bufbuild/issue/BSR-380/sync-zap-loggers-before-exit
> Call logger.Sync on exit

- .github/workflows/ci.yaml
- .github/workflows/windows.yaml
- Dockerfile.buf
- Dockerfile.workspace
- make/buf/all.mk
Update to the latest security/bugfix release of Go 1.18.
> update to go 1.18.5

- make/go/dep_golangci_lint.mk
- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig.go
- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig_test.go
- private/bufpkg/bufplugin/bufpluginconfig/config.go
- private/bufpkg/bufplugin/bufpluginconfig/get.go
- private/bufpkg/bufplugin/bufplugindocker/docker.go
- private/bufpkg/bufstudioagent/bufstudioagent_test.go
- private/pkg/transport/http/httpclient/httpclient_test.go
Update the 'buf alpha plugin push' command to add an '--override-remote'
flag to allow building/publishing a plugin to another BSR instance
(without requiring changes to the 'buf.plugin.yaml' file).
> add --override-remote flag to plugin push

- private/pkg/transport/http/httpserver/httpserver.go
this helper allows adding middlewares to a Mapper inside of a Group,
which stops them interfering with other routers defined under parent
> add MapperWithMiddlewares helper

- private/pkg/observability/observability.go
- private/pkg/observability/wrapped_round_tripper.go
- private/pkg/transport/http/httpclient/client.go
- private/pkg/transport/http/httpclient/httpclient.go
In order to tag the HTTP clients we use in the BSR, we need to
add the ability to create custom tags and get the data from the
request context.
This has been tested on a local BSR cluster.
> Add support for metrics tags on httpclient

- CHANGELOG.md
- private/buf/bufformat/formatter.go
- private/buf/bufformat/formatter_test.go
- private/buf/bufformat/testdata/proto2/quotes/v1/quotes.golden.proto
- private/buf/bufformat/testdata/proto2/quotes/v1/quotes.proto
Fixes #1093
This adjusts the formatter logic to preserve single quotes for string literals that contain `(")` or `(\")` literals. In general, the formatter prefers double quotes, so if the string literal contains a mix of `(")` and `(')` literals, the string will be surrounded with `(")`.
> Preserve single quotes with buf format

- .golangci.yml
- private/buf/bufcli/bufcli.go
- private/bufpkg/bufmodule/bufmodulecache/bufmodulecache.go
- private/bufpkg/bufmodule/bufmodulecache/bufmodulecache_test.go
- private/bufpkg/bufmodule/bufmodulecache/module_cacher.go
- private/bufpkg/bufmodule/bufmodulecache/module_reader.go
This adds `bufcli.NewModuleReaderAndCreateCacheDirsWithExternalPaths` so that callers can preserve the external paths within the module cache. 
In general, this is _not_ something we want to do (hence the loud `WARNING` in the function comment), but it's required for some features (e.g. a language server that refers to files in the cache).
> Add option for cache to preserve external paths

- private/pkg/transport/http/httpserver/httpserver.go
- private/pkg/transport/http/httpserver/runner.go
- private/pkg/transport/http/httpserver/zap.go
pass a list of endpoints to ignore by path, the goal of this is to
stop logging requests to /health and /metrics
> add runner option to silence logging certain endpoints

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
- private/bufpkg/bufplugin/bufplugindocker/docker.go
Update plugin push command to allow for optional --build-arg arguments
to be passed to the build.
> allow specifying build arguments to plugin push

- private/bufpkg/bufplugin/bufplugin.go
- private/bufpkg/bufplugin/bufplugin_test.go
- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig.go
- private/bufpkg/bufplugin/bufpluginconfig/config.go
Expose new field, added in https://github.com/bufbuild/buf/pull/1342, to the buf plugin config file.
Example usage:
```yaml
[...]
registry:
npm:
rewrite_import_path_suffix: connectweb.js
deps:
- package: "@bufbuild/connect-web"
version: "0.1.0"
```
> Expose rewrite_import_path_suffix to plugin file

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
- private/bufpkg/bufplugin/bufplugindocker/docker.go
Currently, calling 'buf alpha plugin push' requires rebuilding a Docker
image from scratch (including replicating context, build args, caching
arguments, and authentication credentials). In some cases, we may wish
to simply re-use an image built with a previous 'docker build' command.
To support this behavior, add an '--image' argument which can refer to
an existing image in the Docker client to be tagged (with the
appropriate BSR tag) and pushed.
> allow pushing an existing image with plugin push

- private/bufpkg/bufplugin/bufplugindocker/docker.go
Now that we support command line flags like `--override-remote`, we
should remove this label as it doewsn't have much value.
> remove the remote docker label

- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig.go
- private/bufpkg/bufplugin/bufpluginconfig/bufpluginconfig_test.go
In order to ensure consistent comparison of plugins, ensure that we
always sort a slice of options after conversion from a map.
> ensure plugin options slice is sorted

- private/buf/bufformat/formatter.go
- private/buf/bufformat/testdata/proto2/option/v1/option_message_field.golden.proto
- private/buf/bufformat/testdata/proto2/quotes/v1/quotes.golden.proto
- private/buf/bufformat/testdata/proto2/quotes/v1/quotes.proto
Fixes #1370
This adjusts the change made to fix https://github.com/bufbuild/buf/issues/1093 (which has not yet been released), so that we always preserve the raw string specified in the original source.
Note that we don't need a new `CHANGELOG.md` entry here because it was already introduced in #1332.
> format: Handle special escaped characters

- private/pkg/storage/matcher.go
Adds a new `storage.Matcher` that matches on the `Base` of a path.
> Add a `Base` Matcher

- private/buf/bufgen/features.go
- private/buf/bufgen/generator.go
- private/bufpkg/bufimage/bufimage.go
Currently, the only feature that can be checked this way is support for proto3 optional fields.
But the protocol is apparently intended to make sure plugins implement future language changes before that language feature is actually used with that plugin.
More details [here](https://github.com/protocolbuffers/protobuf/blob/main/docs/implementing_proto3_presence.md#signaling-that-your-code-generator-supports-proto3-optional).
Fixes TCN-427
> implement protocol for negotiating supported features with plugin

- private/buf/bufgen/generator.go
Update the local generation to look up the plugin name from the PluginName() accessor (which looks at the Plugin, Name, and Remote in order). This fixes local generation when using the new config key.
> fix local generation using plugin key

- private/pkg/transport/http/httpserver/httpserver.go
- private/pkg/transport/http/httpserver/runner.go
The Run function only concerns itself with running a http server and does not attempt to perform any routing setup. The http.Handler that is passed is expected to be a chi.Mux or other complex router that will take care of routing for the server.
I've copied the RunnerOptions that matter for the server setup into RunOptions and split out server logic from the Run function into a `serve` function that can be called privately by the new Run function.
> add httpserver.Run function

- private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder_test.go
`require.NoError(t, err)` was already asserted and `err` has not mutated.
> bufmodulebuild: unncessary assert on err

- .golangci.yml
- make/go/dep_golangci_lint.mk
See the release notes at https://github.com/golangci/golangci-lint/releases/tag/v1.49.0 for the changes in linters.
I did not add `interfacebloat`, a strongly opinionated linter that fails when there's more than 10 methods on an interface. `contextcheck` was re-enabled in this version of golangci-lint and we should fix the issues it brings up, temporarily disabled it for now.
> Upgrade golangci-lint

- CHANGELOG.md
- private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder.go
- private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder_test.go
`bufmodulebuild.BuildForBucket` calls `bufmodule.NewModuleForBucket`
with a different bucket than the one passed to it. This mapped bucket
didn't include `buf.yaml`, hence the built `bufmodule.Module` didn't
have values for breaking or linting config.
`buf push` will now pass good lint and breaking config to the registry.
> bufmodulebuild: include the bucket's config

- go.mod
- go.sum
- private/pkg/observability/observability.go
- private/pkg/observability/observabilityotel/meter_provider_closer.go
This adds a closer for the `metric.MeterProvider` from Opentelemetry, similar to
what was done for the `trace.TracerProvider` in #1355
> Add closer for Opentelemetry `metric.MeterProvider`

- private/buf/cmd/buf/command/beta/convert/convert.go
v simple change
- Remove default input from "." in convert as it doesn't need to be run in a buf module
> Allow for buf beta convert to be used without input

- private/pkg/protosource/option_extension_descriptor.go
- private/pkg/protosource/protosource.go
I was looking through this code, just to get acquainted with it so I am prepared to talk to @seankimdev about potential upcoming changes, when I noticed this. It was a pretty easy fix, so I figured I'd go ahead and make the change.
Sadly, there are no tests in this package. I didn't add the first test because the process to create a `protosource.Message` appears non-trivial due to several layers between the underlying descriptor and the `protosource` layer. So I simply verified that no existing tests were broken by it. But this new check is the same as [the one that causes the panic](https://github.com/protocolbuffers/protobuf-go/blob/b0a944684d78a6b7c1f2bb6864fa910385d5b97a/internal/impl/message_reflect.go#L449-L452).
> avoid panic in OptionExtensionDescriptor

- private/buf/buffetch/buffetch.go
`ReadBucketCloserWithTerminateFileProvider` is actually a `ReadBucketCloser` with `TerminateFileProvider`. It's not a writer.
> buffetch: correct bucket type doc

- private/bufpkg/bufstudioagent/bufstudioagent_test.go
- private/bufpkg/bufstudioagent/plain_post_handler.go
Also unskips the test that was skipped due to this issue, which doesn't *seem* flaky now?
> Use connect.IsWireError for client error scenario

- private/buf/bufcli/bufcli.go
- private/buf/bufcli/bufcli_test.go
- private/buf/cmd/buf/command/push/push.go
- private/pkg/storage/storagemem/storagemem.go
Coverage for bufcli.ReadModuleWithWorkspacesDisabled
----------------------------------------------------
ReadModuleWithWorkspacesDisabled didn't have coverage and I intend to do some minor refactoring soon. Now's a great time to document its behavior.
ReadModuleWithWorkspacesDisabled took a `appflag.Container`, but that's a very large interface to create and inject. I didn't see any obvious test fixture to provide it., so instead of building that I reduced signature to its minimal interface: a logger and an app.EnvStdinContainer.
IMHO, it's pretty odd to depend on a large interface type from a different package. I'll leave that yak shave for another day.
storagemem.NewReadWriteBucketWithOptions
------------------------------
It wasn't possible to initialize an in-memory storage bucket …
> bufcli: add test, storagemem: NewReadWriteBucket2

- private/buf/cmd/buf/internal/internaltesting/internaltesting.go
This function is not used. NewEnvFunc is the prefered form in cli tests.
Ref: TCN-687
> Remove unused internaltesting.NewEnv.

- private/buf/cmd/buf/command/push/push.go
It's possible to succeed but have a missing LocalModulePin in the response. Check for this and report an error.
> push: error if response's pin is missing

- private/buf/bufcli/bufcli.go
- private/bufpkg/buftransport/buftransport.go
Plain HTTP is useful for testing but the registry provider always used HTTPS even when the TLS config was nil.
> bufcli: support HTTP registries

- private/buf/bufcli/bufcli.go
- private/buf/bufcli/bufcli_test.go
- private/buf/cmd/buf/command/push/push.go
BucketAndConfigForSource assumes ReadModuleWithWorkspacesDisabled's fetching and validating a module's content into a bucket.
Renames ReadModuleWithWorkspacesDisabled to ReadModule as workspaces are no longer involved. ReadModule becomes shorthand for constructing a builder and building a module.
> bufcli: BucketAndConfigForSource

- private/pkg/app/appproto/appprotoexec/appprotoexec_go18.go
It never occured to me that running `make` would not catch this kind of mistake. Entirely on me.
> Fix CI breakage on Go 1.18.

- private/pkg/manifest/module_test.go
Fixes [this failure](https://github.com/bufbuild/buf/actions/runs/3440666825/jobs/5739385649#step:5:212). It is an `append` issue :facepalm: ... TIL that [sometimes `append` modifies the underlying array in the first param](https://pkg.go.dev/builtin#append), so `t.Parallel()` was messing the shared blobs state.
> The append built-in function appends elements to the end of a slice. **If it has sufficient capacity, the destination is resliced to accommodate the new elements.** If it does not, a new underlying array will be allocated. Append returns the updated slice.
> [bsr-721] Generate a new blobs array per test

- private/buf/bufcli/bufcli.go
- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
Also adds some functions to `bufcli` that will eventually _replace_ the `NewRegistryProvider*` functions.
Updates usage of the `AuthnService` to use a plain Connect client stub.
Fixes BSR-802
> use plain Connect client stub for AuthnService

- private/buf/bufcli/bufcli.go
- private/buf/cmd/buf/command/beta/registry/repository/repositorycreate/repositorycreate.go
- private/buf/cmd/buf/command/beta/registry/repository/repositorydelete/repositorydelete.go
- private/buf/cmd/buf/command/beta/registry/repository/repositorydeprecate/repositorydeprecate.go
- private/buf/cmd/buf/command/beta/registry/repository/repositoryget/repositoryget.go
- private/buf/cmd/buf/command/beta/registry/repository/repositorylist/repositorylist.go
- private/buf/cmd/buf/command/beta/registry/repository/repositoryundeprecate/repositoryundeprecate.go
- private/buf/cmd/buf/command/beta/registry/repository/repositoryupdate/repositoryupdate.go
- private/buf/cmd/buf/command/beta/registry/tag/tagcreate/tagcreate.go
- private/buf/cmd/buf/command/beta/registry/tag/taglist/taglist.go
- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
- private/bufpkg/bufmodule/bufmodulecache/bufmodulecache.go
- private/bufpkg/bufmodule/bufmodulecache/bufmodulecache_test.go
- private/bufpkg/bufmodule/bufmodulecache/module_reader.go
This change had a usage of the provider in a test (via a fake/mock). So I added a new type, bespoke to that usage, so that we can still provide a fake stub in the test.
Other than that, everything in here is pretty mechanical.
Fixes BSR-803
> update repository service and repository tag service clients to use plain Connect clients

- private/pkg/manifest/module.go
- private/pkg/manifest/module_test.go
Checking for blob equality doesn't really depend on the blob's implementation. It's a check if the digest and content are identical, both of which are exposed in the Digest and Open methods.
BlobEqual implements exactly this. It's a little tricky to read and compare content from two streams. They can throw errors at any point. Each read can return a different sized block. Reads can return an error with data. I hope I covered these edge cases and made sure to test them (100% coverage)!
> manifest: make Blob.EqualContent a pkg func

- .golangci.yml
This field must still be supported even if it's deprecated.
> lint: ignore unused field in module reader

- private/bufpkg/bufapimodule/module_reader.go
- private/bufpkg/bufapimodule/module_reader_test.go
- private/pkg/manifest/module.go
- private/pkg/manifest/module_test.go
- private/pkg/manifest/storage.go
This updates bufapimodule.ModuleReader to build modules from manifest and blob content returned in DownloadService.Download's response. manifest.NewBucketFromManifestBlobs exposes this logic for other users.
This also adds manifest.NewBlobFromProto, which is the inverse mapper of manifest.AsProtoBlob.
> module reader: build from a manifest and blobs

- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
remote not documented. feedback provided by customer.
> Problem was that the CLI does not list the domain as a possible parameter
>In contrast to the online docs:
```sh
$ buf registry login [domain] --username USERNAME
```
> Add <domain> argument to docs for buf registry login

- private/buf/bufformat/formatter.go
- private/buf/bufformat/testdata/proto2/field/v1/option.golden.proto
- private/buf/bufformat/testdata/proto2/field/v1/option.proto
The logic added in 1.9 was attempting to "fix" indentation for multi-line comments that were attached to an element that was moved. For example, if there's a trailing comment attached to a semicolon and the semicolon was moved as part of the re-format, the comment may need to be re-indented accordingly.
However, this re-indenting was too aggressive and turns out to be destructive for comments that have _intentional_ interior indentation.
The fix is to leave interior indentation alone by only re-indenting based on the _least_ indented line and leaving other lines in the comment indented relative to that. (Not sure if that sentence makes sense. Maybe reading the code will help clear it up?)
I'm not going to lie: I know the code in here (including some of the new code in this change) is …
> buf format: preserve interior indentation in multi-line comments

- .golangci.yml
Switch from `goimports` to `gci`, which actually enforces the import
grouping style required by Buf's style guide.
> Enforce import grouping

- .golangci.yml
- private/bufpkg/bufapimodule/module_resolver.go
- private/bufpkg/bufapimodule/module_resolver_test.go
bufapimodule.moduleResolver.GetModulePin would panic if the response's RepositoryCommit is nil. This handles such a response with an error about the empty response. This also adds test coverage for GetModulePin.
Fixes: TCN-808
> apimodule: test resolver and fix nil exception

- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/bufimageutil/image_index.go
This addresses a TODO about using the `protosource` model. The assumption in that TODO was that it was heavy-weight. 
So this PR first adds a benchmark (see first commit), to evaluate if the change actually improves performance.
The second commit is the change that addresses the TODO (which did have an impact on performance). It adds more information to the `imageIndex` so that the descriptor protos can be used, instead of having to first wrap the whole hierarchy in `protosource` types.
The third commit is another change that IMO makes the code easier to read, but also improves performance a little further by keeping accumulator variables in a new `transitiveClosure` struct, instead of each recursive call having to repeatedly concatenate slices. This is also a pre-factor for addressing …
> improvements in filtering image

- private/buf/bufcli/bufcli.go
- private/buf/bufcli/bufcli_test.go
- private/buf/bufwire/file_lister.go
- private/buf/bufwire/module_config_reader.go
- private/buf/bufwork/workspace_builder.go
- private/buf/cmd/buf/command/push/push.go
- private/buf/cmd/buf/command/push/push_test.go
- private/bufpkg/bufcheck/bufbreaking/bufbreaking_test.go
- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufimage/bufimagebuild/bufimagebuildtesting/bufimagebuildtesting.go
- private/bufpkg/bufimage/bufimagebuild/builder_test.go
- private/bufpkg/bufmodule/bufmodulebuild/bufmodulebuild.go
- private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder.go
- private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder_test.go
This is an exercise in frustration to push only the set of blobs needed to build a module. The bug's cause was building a module did not expose the bucket used to build the module with, hence the manifest consumed the source bucket containing module-unrelated files.
bufmodulebuild tries to abstract away building but had, and still has, many rough edges. Some of note are:
- Build configuration is in the bucket, but the build section of configuration is not read from the bucket.
- Build configuration cannot be written to `buf.yaml`.
- Incorrect build configuration in a bucket can make a bucket appear buildable when it is not.
- Some build configuration is not in the build section nor in the bucket, instead being hard coded as options.
- BuildForBucket would take options directly, even …
> Push a minimal set of blobs.

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
- private/bufpkg/bufplugin/bufplugindocker/docker.go
- private/bufpkg/bufplugin/bufplugindocker/docker_test.go
This sets an UpstreamClient User-Agent on our docker client which gets injected in the outgoing request.
https://github.com/moby/moby/blob/a4cbaa958d03b54da713162c8a23574430dacfa8/dockerversion/useragent.go#L70-L78
On the OCI registry side we can inspect the incoming request, which will look something like this:
```
docker/20.10.21 go/go1.18.7 git-commit/3056208 kernel/5.15.49-linuxkit os/linux arch/arm64 UpstreamClient(buf-cli-1.11.0-dev)
```
And parse out the `UpstreamClient` portion.
> Add UpstreamClientUserAgent to dockerclient

- .github/workflows/release.yaml
Post 1.11.0 release, https://github.com/bufbuild/buf/pull/1687 added a superfluous v to the `NEXT_VERSION`. This PR removes the prepended value from `NEXT_VERSION`
> TCN-908 remove superfluous v

- private/buf/bufcli/bufcli.go
We should not be starting traces/spans from the CLI. This should be instrumented starting from the edge of our system.
> Do not start spans from the CLI

- private/bufpkg/bufstudioagent/buffer_codec.go
- private/bufpkg/bufstudioagent/bufstudioagent_test.go
- private/bufpkg/bufstudioagent/plain_post_handler.go
See https://github.com/bufbuild/buf/pull/1703 for the background here - this, plus #1703, will make it so that all of our marshalling/unmarshalling of Protobuf payloads goes through one common/consistent/vetted location.
> Use protoencoding for marshalling and unmarshalling

- private/pkg/command/command.go
- private/pkg/command/runner.go
If we're using `private/pkg/command` to run a command silently, sending
stdout and stderr to `io.Discard` is needlessly expensive: it creates a
pipe and spawns a goroutine to copy from the pipe to the writer, which
then throws the data away. If we leave stdout and stderr as nil,
`os/exec` instead connects the process directly to `/dev/null`, which is
functionally identical and cheaper.
See [the os/exec.Command docs](https://pkg.go.dev/os/exec#Cmd:~:text=Otherwise%2C%20during%20the%20execution%20of%20the%20command%20a%20separate%20goroutine) for details.
> Make silent runners faster

- private/buf/bufcurl/reflection_resolver.go
- private/buf/cmd/buf/command/curl/curl.go
- private/pkg/stringutil/stringutil.go
- private/pkg/stringutil/stringutil_test.go
This changes the definition of `buf curl --reflect-protocol` slightly to make it such that this flag no longer has an `auto` value. Instead, this flag is defined as "use a specific reflection protocol. if no protocol is set, we will choose". This means there is no special value needed to be understood by our users - the default value for `--reflect-protocol` is no value.
As part of this change, this changes the `ReflectProtocol` type to be an enum in line with the rest of the codebase and our code standards (although we should make it more clear in our code standards, its a little obscure to be fair). We prefer `int` enums over `strings` because they do not allow people to do things such as cast user-provided flag values to their type directly :-) enums should be just that, and parsing …
> Remove auto value from reflect protocol and make unset the default

- .pre-commit-hooks.yaml
This adds an option to run `buf generate` when `.proto` files change. Users may need to override the `entry` with additional flags and/or specify the hook more than once with variations, but it should work fine.
> Add buf generate pre-commit hook

- .github/workflows/pr-title-linter.yaml
- .github/workflows/pr-title.yaml
We have had inconsistent PR titles across our various repositories - some start with capital letters, some don't, some end in periods, some don't. No one way is the right way, but from day one I did PR titles with capital letters and no periods at the end, and one way is better than no way, so @akshayjshah had the idea that we should just enforce this as part of linting with this action. Trying this on bufbuild/buf, and it it works, we'll add to our other repositories as well.
> Add PR title linter

- private/buf/cmd/buf/command/curl/curl.go
> Fix typo in --http2-prior-knowledge help text

- .github/workflows/release.yaml
- README.md
`make updatehomebrewbadge` in release step didnt pass a `VERSION` so it never updated.
> Fix `updatehomebrewbadge` in post-release action

- CHANGELOG.md
- private/buf/cmd/buf/buf.go
Removes `buf beta convert` alias to `buf convert` 
```diff
Beta commands. Unstable and likely to change.
Usage:
buf beta [flags]
buf beta [command]
Available Commands:
-  convert         Convert a message from binary to JSON or vice versa
migrate-v1beta1 Migrate any v1beta1 configuration files in the directory to the latest version.
registry        Manage assets on the Buf Schema Registry.
studio-agent    Run an HTTP(S) server as the Studio agent.
```
> Remove buf beta convert

- private/bufpkg/bufconnect/errors.go
- private/bufpkg/bufconnect/errors_test.go
- private/bufpkg/bufconnect/interceptors.go
Per Go Code Standards in Notion, custom error type names should be suffixed in `Error`
> Rename ErrAuth to AuthError

- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/bufimageutil/testdata/any/a.proto
- private/bufpkg/bufimage/bufimageutil/testdata/any/b.proto
- private/bufpkg/bufimage/bufimageutil/testdata/any/c1.proto
- private/bufpkg/bufimage/bufimageutil/testdata/any/c1.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/any/c2.proto
- private/bufpkg/bufimage/bufimageutil/testdata/any/c2.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/any/c3.proto
- private/bufpkg/bufimage/bufimageutil/testdata/any/c3.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/any/c4.proto
- private/bufpkg/bufimage/bufimageutil/testdata/any/c4.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/any/d.proto
- private/bufpkg/bufimage/bufimageutil/testdata/any/d.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/any/e.proto
- private/bufpkg/bufimage/bufimageutil/testdata/any/e.txtar
This adds code to explore messages that appear in option values, recursing through any nested structure to find instances of `google.protobuf.Any`. If it finds an instance and it refers to a known message type, add that as an edge to the graph.
If you check out the new testdata file `d.proto` with message `NormalMessageSyntaxValidType`: it does _not_ import the referred message type and uses the normal syntax instead of the extended syntax. But when we filter the image, we end up synthesizing the import because we recognize the type.
The testdata file `e.proto` includes a reference to a bogus, non-existing type. In this case, everything still works, but there is no edge it can add to the graph. (Consumers of the Any will, of course, be unhappy...)
The Any messages in the test outputs are …
> When filtering image, include type references in Any messages in option values

- private/pkg/git/cmd/git-ls-files-unstaged/main.go
- private/pkg/git/git.go
- private/pkg/git/lister.go
- private/pkg/licenseheader/cmd/license-header/main.go
This PR does a few things:
- This pulls out the logic from `git-ls-files-unstaged` into the `git` package, so it can be reused.
- This uses @akshayjshah's logic in our OSS Makefile instead of the pre-existing logic, as there was a rare bug in the existing logic.
- This makes it so that if you call `license-header` with no arguments, `license-header` will by default do the equivalent of `git-ls-files-unstaged | xargs license-header`.
- This adds a `--ignore` flag to license-header that can replicate what we used `grep -e` for.
The result is we can make it so that our tools can just call `license-header` as opposed to doing other complicated logic with `git-ls-files, comm, git-ls-files-unstaged`.
I've QA'ed this manually and extensively, no worse than what was there before.
A few notes:
- …
> Pull out logic from git-ls-files-unstaged, refactor to use better logic, and add logic to license-header

- private/buf/cmd/buf/command/export/export.go
Currently `buf export` says that it accepts `bin` when it does not. 
`buf export` doesn't accept `bin` or `json` meaning that it accepts a `source` and not an `input`.
This is a diff of the help text:
```diff
- Export the files from the input location to an output location.
+ Export the files from the source location to an output location.
The first argument is the source or module to export.
- The first argument must be one of format [bin,dir,git,json,mod,protofile,tar,zip].
+ The first argument must be one of format [dir,git,mod,protofile,tar,zip].
If no argument is specified, defaults to ".".
Examples:
+ Export proto files in <source> to an output directory.
-     $ buf export <input> --output=<output-dir>
+     $ buf export <source> --output=<output-dir>
- input can be of the format …
```
> Fix export help text

- private/bufpkg/bufimage/bufimagemodify/php_metadata_namespace.go
The `php_metadata_namespace` file option should `44` based on `descriptor.proto`.
> Managed mode php_metadata_namespace file option field should be 44

- private/buf/bufgen/bufgen.go
- private/buf/bufgen/config.go
- private/buf/bufgen/generator.go
- private/pkg/app/appproto/appprotoexec/appprotoexec.go
- private/pkg/app/appproto/appprotoexec/generator.go
Fixes #1462.
Added field `protoc_path` in `buf.gen.yaml` to allow specifying `protoc` path for built-in plugins as mentioned [here](https://github.com/bufbuild/buf/issues/1462).
> Add protoc_path in buf.gen.yaml

- private/pkg/storage/storagearchive/storagearchive.go
- private/pkg/storage/storagetesting/storagetesting.go
The ability to limit file size was added in #1408. But the mapper may exclude large files that will not be copied into the reader, so only check the file size after mapping occurs.
> Untar check file size after mapping

- private/buf/cmd/buf/command/format/format.go
`buf format` does not take an image as it would need lossless source knowledge which does not exist for images
```
buf build -o foo.bin & buf format foo.bin
Failure: format was "bin" but must be one of [dir,git,mod,protofile,tar,targz,zip]
```
> Update format to use source instead of input

- make/buf/all.mk
- private/buf/cmd/buf/command/generate/generate.go
When updating `CHANGELOG.md`, I noticed that we have `buf build --type` and `buf generate --include-types`, both of which filter based on type. There are two issues:
- We don't pluralize string slice flags - a single value is valid, and a single value is what you specify on the command line, ie `--types foo` doesn't make sense, but `--type foo` does. This would mean renaming from `--include-types` to `--include-type`.
- `--include-.*` is a boolean flag everywhere else in `buf`, and we should be consistent across commands where possible, so this means renaming from `--include-type` to `--type`.
This deprecates `--include-types` and continues to handle it properly per our compatibility guarantee, but hides the flag, and prints a deprecation warning if it is used.
This also moves the names …
> Replace buf generate --include-types with buf generate --type

- Dockerfile.buf
- make/buf/scripts/brew.sh
- make/buf/scripts/release.bash
We do not use `debug.BuildSettings` anywhere and this is causing issues with our release.
> Set -buildvcs=false for all builds of binaries

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
- private/bufpkg/bufplugin/bufplugindocker/docker.go
- private/bufpkg/bufplugin/bufplugindocker/docker_test.go
Update Docker client to negotiate the client version and also fix typo in error handling.
> Enable version negotiation with Docker client

- private/pkg/normalpath/normalpath_windows.go
This uses a sentinel value in checking the path equality in `normalpath` for Windows.
This lets us handles different volumes in the Windows paths.
This change has been tested on a Windows machine with Go 1.20.
> Handle walking different volumes for Windows in normalpath

- private/pkg/app/appproto/appprotoexec/protoc_proxy_handler.go
- private/pkg/app/appproto/appprotoexec/version.go
- private/pkg/app/appproto/appprotoexec/version_test.go
Fixes https://github.com/bufbuild/buf/issues/1806.
This also adjusts some of the function names to be clearer as to what they do.
Manually QA'ed.
> Error if js is attempted to be used as a builtin plugin for protoc v21 and above

- private/buf/bufcli/bufcli.go
- private/buf/cmd/buf/command/beta/migratev1beta1/migratev1beta1.go
- private/buf/cmd/buf/command/breaking/breaking.go
- private/buf/cmd/buf/command/generate/generate.go
- private/buf/cmd/buf/command/mod/modopen/modopen.go
- private/buf/cmd/buf/command/mod/modprune/modprune.go
- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
Adds full stops in long descriptions. 
Changes the phrase 
> If no argument is specified, defaults to ".".
to 
> Defaults to "." if no argument is specified.
to Avoid the ugly looking period next to the quoted period `".".`
> Add full stops to long descriptions

- private/bufpkg/bufmodule/bufmodulestat/bufmodulestat.go
- private/bufpkg/bufmodule/bufmodulestat/file_walker.go
- private/bufpkg/bufmodule/bufmodulestat/usage.gen.go
This is for `protostat` on a `bufmodule.Module` basis. I will likely use this in `buf alpha stats`, and @mfridman wanted it too.
> Add bufmodulestat package

- private/buf/cmd/buf/command/mod/modinit/modinit.go
This being an `appcmd.NewInvalidArgumentError` prints the usage as well, which doesn't really make sense in this case.
> Make existing file error not an invalid argument error

- private/bufpkg/bufimage/bufimagetesting/bufimagetesting_test.go
- private/bufpkg/bufimage/util.go
- private/bufpkg/bufimage/util_test.go
- private/pkg/protodescriptor/protodescriptor.go
This way, if a field is ever added to the descriptors and then serialized by a newer version of `buf`, an older version of `buf` won't mangle it and inadvertently drop those newer fields.
The place in `protodescriptor` is the code path used for converting an image file to a descriptor proto. And the place in `bufimage` is for the other direction.
> Preserve unknown fields when converting between `FileDescriptorProto` and `ImageFile`

- private/pkg/manifest/digest.go
- private/pkg/manifest/manifest.go
- private/pkg/manifest/module.go
- private/pkg/manifest/storage.go
The package overview has been expanded to cover interaction of most important types: Manifest, Digest, Blob, and BlobSet.
Some method docs have been rewritten for clarity.
> More pkg/manifest documentation

- CHANGELOG.md
- private/buf/bufformat/formatter.go
- private/buf/bufformat/testdata/proto3/header/v1/header-block.golden.proto
- private/buf/bufformat/testdata/proto3/header/v1/header-block.proto
> Fix formatting of C-style block comments that use prefix symbols on each line

- CHANGELOG.md
- private/buf/cmd/buf/command/beta/studioagent/studioagent.go
- private/bufpkg/bufstudioagent/bufstudioagent.go
- private/bufpkg/bufstudioagent/bufstudioagent_test.go
This PR adds a `--private-network` boolean flag that allows the Studio agent to handle
preflight requests from Studio in private networks that set the `Access-Control-Request-Private-Network`
header set.
We still want to preserve the default behaviour of rejecting preflight requests if the flag has not been set.
> Handle private network preflight requests in Studio agent with flag `--private-network`

- .github/workflows/release.yaml
We had chained a number of jobs meaning that if one failed, they all failed. This PR changes that behaviour by having the following steps depend on post-release and then run independently.
- trigger npm publish
- trigger homebrew-buf release
- trigger vim-buf release
- trigger docs.buf.build release
- trigger buf-setup-action release
i achieved this by posting the `VERSION` as an output of the `post-release` job like [this](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs)
> Trigger adjacent jobs in release process

- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref_test.go
If 'buf mod update' runs and resolves to the same module identity and commit, it should error out if the digest doesn't match what is recorded in the buf.lock file. While unlikely, this may indicate that a module has changed since last resolved against the BSR.
> Update 'buf mod update' to check digest changes

- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
🤦 Caught this while on-call. It happened in production when the BSR was handling an `ImageService.GetImage` request. I think this means use of `-type` param with `buf build` and `buf generate` will crash if the schema contains maps whose values are not message types 😢. So we'll probably want to create a patch release of the Buf CLI, too.
Fixes BSR-1543
> Fix panic in image filtering

- private/buf/bufcurl/reflection_resolver.go
I just happened to notice these while reviewing some of the code in here.
> Teeny-tiny updates in buf curl

- CHANGELOG.md
- private/buf/bufgen/config.go
- private/buf/bufgen/config_test.go
- private/buf/bufgen/testdata/v1beta1/gen_success4_nopath.yaml
When migrating a v1beta1 external config to a plugin config, we should only set the new path slice if the path in the config is non-empty. Otherwise, we'll try to exec an empty command by initializing the slice to `{""}`.
Fixes #1850.
> Only assign plugin path if set in config

- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
This warning used to assume that remotes would end with `buf.team`, but private remotes can have any name.
> Update no module name warning

- private/buf/cmd/buf/command/breaking/breaking.go
- private/buf/cmd/buf/command/export/export.go
- private/buf/cmd/buf/command/format/format.go
- private/buf/cmd/buf/command/generate/generate.go
- private/buf/cmd/buf/command/lint/lint.go
- private/buf/cmd/buf/command/lsfiles/lsfiles.go
- private/buf/cmd/buf/command/mod/internal/internal.go
This was asked in the buf slack channel, especially around the `buf format` command as the term "config" is ambiguous to if it configures the behaviour of the command or the entire buf module. 
Also, I think it might actually be more appropriate to have this as an inherited flag, this would make it more clear what was being configured. This might not play nicely with commands that do not need a module input at all (buf curl for example).
```diff
$ buf format --help
Flags:
-      --config string          The buf.yaml file or data to use for configuration
-d, --diff                   Display diffs instead of rewriting files
--disable-symlinks       Do not follow symlinks when reading sources or configuration from the local filesystem
By default, symlinks are followed in this CLI, but never …
```
> Specify that the --config flag is for a buf.yaml file

- .github/workflows/release.yaml
docs.buf.build has moved to buf.build, this PR updates the release trigger accordingly
> Update release to point to new docs location

- private/buf/cmd/buf/command/alpha/plugin/pluginpush/pluginpush.go
Remove visibility as a required flag, will re-introduce this once this command is promoted to `beta` (from `alpha`) and the backend implementation is complete.
> Set default for curated plugin visibility

- private/pkg/app/appcmd/webpages.go
Changes:
- Addition of SlugPrefix and OutputDir fields to the webpagesConfig struct to allow for better customization of the generated markdown output.
- Modification of the generateMarkdownTree function to create the required directories and files for each command and its subcommands, organizing the output in a more structured manner.
- Refactoring of the generateMarkdownPage function to make the generated markdown files follow a more standardized format, including slug, sidebar position, and sidebar label.
- Addition of the websiteSlug and sidebarLabel functions to handle the generation of the slug and sidebar label for each command.
<details>
<summary>tree structure</summary>
```
.
└── buf
├── beta
│   ├── _category.json
│   ├── index.md
│   ├── migrate-v1beta1.md
│   ├── price.md
│   …
```
> Webpages multi page output

- .github/workflows/buf.yaml
- .github/workflows/ci.yaml
- .github/workflows/codeql.yaml
- .github/workflows/previous.yaml
- .github/workflows/release.yaml
Update to ubuntu-latest in all workflows (we're about 50/50 right now). Setup Go in the CodeQL workflow to attempt to fix a warning. Use consistent syntax for specifying versions in workflows.
> Update actions workflows to latest Ubuntu

- private/bufpkg/bufmodule/bufmodulecache/cas_module_cacher.go
- private/pkg/manifest/manifest.go
- private/pkg/manifest/manifest_test.go
- private/pkg/manifest/module.go
- private/pkg/manifest/module_test.go
- private/pkg/manifest/storage.go
Range function for the manifest entries, so we can reduce the appearances of `.Paths()` usages like:
```go
for _, path := range m.Paths() {
digest, ok := m.DigestFor(path)
if !ok {
// this will never happen
return nil, fmt.Errorf("digest not found for path: %s", path)
}
// do something with path and digest...
}
```
into:
```go
m.Range(func(path string, digest manifest.Digest) error {
// do something with path and digest...
})
```
> Manifest.Range: iterate entries (path, digest)

- private/buf/cmd/buf/command/curl/curl.go
Before:
```
> buf curl http://localhost:30485/buf.knit.demo.swapi.film.v1.FilmService/GetFilms
Failure: failed to resolve symbol "buf.knit.demo.swapi.film.v1.FilmService": unknown: HTTP status 505 HTTP Version Not Supported
```
After:
```
> buf curl http://localhost:30485/buf.knit.demo.swapi.film.v1.FilmService/GetFilms
Failure: --reflect cannot be used with plain-text URLs (http) unless --http2-prior-knowledge flag is set
```
> Better error message from `buf curl` when trying to use reflection over plain-text HTTP

- CHANGELOG.md
- private/buf/cmd/buf/command/beta/price/price.go
For this repository:
```
Current BSR pricing:
- Teams: $0.50 per type (discounted to $0.40 if you sign up before October 15, 2023)
- Pro: $1.00 per type (discounted to $0.80 if you sign up before October 15, 2023)
Pricing data last updated on April 4, 2023.
Make sure you are on the latest version of the Buf CLI to get the most updated pricing
information, and see buf.build/pricing if in doubt - this command runs completely locally
and does not interact with our servers.
Your sources have:
- 489 messages
- 30 enums
- 172 methods
This adds up to 691 types.
Based on this, these sources will cost:
- $345.50/month for Teams
- $691.00/month for Pro
If you sign up before October 15, 2023, these sources will cost:
- $276.40/month for Teams
- $552.80/month for Pro
```
> Update buf beta price

- private/buf/cmd/buf/command/build/build.go
- private/buf/cmd/buf/command/generate/generate.go
Per @jhump, packages and methods are supported now. We could do more to clean up this flag doc, but this at least makes it accurate.
> Update --type flag docs

- .github/workflows/release.yaml
We have a Maven package which ships the Buf CLI (that is in turn used by the buf-gradle-plugin). When releasing a new version of Buf, we should call a workflow to open a PR to update the version of the Maven package as well.
> Update Maven package version as part of release

- private/buf/bufgen/generator.go
- private/bufpkg/bufimage/bufimagemodify/bufimagemodify.go
- private/bufpkg/bufimage/bufimagemodify/java_multiple_files.go
- private/bufpkg/bufimage/bufimagemodify/java_multiple_files_test.go
Currently, the JavaMultipleFiles image modifier will skip setting the value if it already matches the desired value (with `GetJavaMultipleFiles()`), however in some cases we want to preserve any settings specified in the source .proto files, and only overwrite it if unset.
> Allow preserving java_multiple_files setting

- private/buf/bufgen/generator.go
- private/bufpkg/bufimage/bufimagemodify/bufimagemodify.go
- private/bufpkg/bufimage/bufimagemodify/java_outer_classname.go
- private/bufpkg/bufimage/bufimagemodify/java_outer_classname_test.go
In some cases, we need to preserve the user specified setting for `java_outer_classname`. This is useful to allow compilation of code that relies on specific values and gives users more control over generated code/remote packages.
> Allow preserving java_outer_classname setting

- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
Change the error message so that it does not leak the username associated with the token, which is a security risk.
> Do not expose username during login

- CHANGELOG.md
- private/buf/cmd/buf/command/curl/curl.go
- private/pkg/netrc/netrc.go
This adds support for `-u`/`--user`, `-n`/`--netrc`, and `--netrc-file` flags to `buf curl`. These flags work the same way in this context as the flags of the same name in `curl`.
Resolves #1997.
> Add support to "buf curl" for --user and --netrc credentials flags

- .github/workflows/windows.yaml
Right now, we're caching GOMODCACHE and GOCACHE in two places - our own cache rule and in actions/setup-go. Remove our custom caching and just use the built-in caching in setup-go.
> Only cache Go artifacts once

- private/pkg/app/applog/applog_test.go
I would like to contribute to the buf project. I have noticed this functionality did not have a unit test provided. I have added a 2 new tests for the NewLogger() functionality and hope my contribution can impact the overall test coverage of the buf project. Thank you.
> Adding unit tests for NewLogger

- CHANGELOG.md
- private/buf/bufcli/bufcli.go
Also slight wording changes.
Also makes flags in `bufcli` not have trailing periods like the rest of our flags, to be consistent (although we might want to make the opposite choice in a refactor sometime).
> Fix changelog formatting and flags

- private/pkg/thread/thread.go
- private/pkg/thread/thread_test.go
Found a panic in a test, caused because of a DX assumption. From users perspective, doing:
```go
foo := make([]Foo, someLen)
// jobs preparation... each job fills one item in []foo
if err := thread.Parallelize(
ctx,
jobs,
thread.ParallelizeWithCancel(cancelGetBlobs), // if one job fails, stop all jobs
); err != nil {
return nil, err
}
// at this point the user could assume that if no errors happened, then []foo was successfully
// populated... well, if the ctx was cancelled, some/all items in []foo might be empty/nil.
// Even if the ctx was cancelled not by an error trying to fill []foo, but upstream from
// another caller.
```
~I will test in a dependent repo before making this ready for review.~ Tested.
> Throw ctx cancelled error in `thread.Parallelize`

- private/bufpkg/bufapimodule/module_resolver.go
- private/bufpkg/bufapimodule/module_resolver_test.go
Calls to buf export are failing with the tamper proofing feature enabled. We need to update to use the manifest digest from the response instead of the b3 digest.
Verified that buf export works both with and without the feature enabled.
> Fix buf export with tamper proofing enabled

- private/bufpkg/buflock/buflock.go
- private/bufpkg/buflock/buflock_test.go
Update the code that reads a buf.lock file from disk to only ignore previous b1/b3 module digests. If the lock file has an invalid manifest digest, we want to error early.
Fixes #2110.
> Ignore b1/b3 buf.lock digests only

- CHANGELOG.md
- private/buf/bufcurl/invoker.go
- private/buf/bufprint/bufprint.go
- private/buf/cmd/buf/command/curl/curl.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/pkg/protoencoding/json_marshaler.go
- private/pkg/protoencoding/protoencoding.go
- private/pkg/prototesting/prototesting.go
Fixes https://github.com/bufbuild/buf/issues/2130.
The actual flag name we could revisit, and this just hacks it into the code, but it's pretty easy and makes sense to me.
> Add emit-defaults flag to buf curl

- private/buf/cmd/buf/command/beta/registry/plugin/pluginpush/pluginpush.go
Small improvement to the error string we surface to unauthenticated users trying to interact with the OCI registry.
Instead of:
```
Failure: GET https://{remote}/v2/{name}/tags/list?n=1000: unexpected status code 401 Unauthorized
```
It's now:
```
Failure: you are not authenticated. For details, visit https://buf.build/docs/bsr/authentication
```
> Improve error message in plugin push command

- private/bufpkg/bufmodule/bufmodulecache/cas_module_reader_test.go
Test for https://github.com/bufbuild/buf/pull/2152
> Test cached module identity

- private/buf/bufsync/bufsync.go
- private/buf/bufsync/syncable_module.go
- private/buf/bufsync/syncer.go
- private/buf/cmd/buf/command/alpha/repo/reposync/reposync.go
When we sync a local module to a remote, we need to know the remote identity. This is found in the local `buf.yaml`, but that value can change over a module's history. `sync` needs a stable remote identity that it can sync to, so we are making the identity override required.
The UX of this command will be re-evaluated later before we go to beta.
> Remote module identity required for sync

- CHANGELOG.md
- private/buf/bufcli/bufcli.go
- private/bufpkg/bufconnect/bufconnect.go
- private/bufpkg/bufconnect/interceptors.go
- private/bufpkg/bufconnect/interceptors_test.go
This PR adds a connect interceptor to log arbitrary server warnings.
The CLI will recognize the `buf-warning-bin` header, which is expected to be a base64-encoded message. It uses the applog container so users can ignore these messages with `--no-warn`. Do we want this behaviour, or should we always print the warning regardless of user preferences? Probably not.
There's one edge case in that a single command may call multiple RPC's, and if multiple RPC's return warnings they will all be printed. We could add some ctx-based print once logic, but I suspect if multiple RPC's return warnings, those errors will be different anyway, so it's unlikely we'll want to print only the first one.
> Add connect interceptor to log server warnings

- private/buf/bufsync/bufsync.go
- private/buf/bufsync/syncable_module.go
- private/buf/bufsync/syncer.go
- private/buf/cmd/buf/command/alpha/repo/reposync/reposync.go
- private/pkg/git/git.go
- private/pkg/git/object_reader.go
There are some important considerations:
- Sync is resumed _after_ the last known commit for a particular branch.
- Repositories that previously called `buf push` can still take advantage of resumption with `buf sync` if the BSR can find a sync point. The BSR currently looks for a tag on the BSR commit that _looks like_ a Git commit hash. In some cases this may not be correct, and users will have to manually create a new tag with the correct Git commit hash.
- Rebasing is not supported and currently fails the entire sync in a partial state.
- Sync points _must_ be encountered, otherwise sync fails after completion.
> Resume sync from last sync point

- private/pkg/dag/dag.go
- private/pkg/dag/dag_test.go
This PR adds a bunch of improvements to the `private/pkg/dag` package.
- Renames `ForEachEdge` to `Walk`, which is more standard.
- Changes `Walk` to no longer require the user to specify a single source node (a node with no incoming edges).
- Makes the DAG handle multiple sources correctly.
- Adds `DOTString` which prints out the DAG in DOT format https://graphviz.org/doc/info/lang.html.
- Adds a bunch of testing, especially of cases with multiple sources.
- Various cleanups and context comments added as well.
> DAG improvements

- private/buf/bufcli/bufcli.go
- private/buf/bufcli/bufcli_test.go
- private/buf/bufwire/bufwire.go
- private/buf/bufwire/file_lister.go
- private/buf/bufwire/image_config_reader.go
- private/buf/cmd/buf/command/alpha/protoc/protoc.go
- private/buf/cmd/buf/command/export/export.go
- private/bufpkg/bufcheck/bufbreaking/bufbreaking_test.go
- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufimage/bufimagebuild/bufimagebuild.go
- private/bufpkg/bufimage/bufimagebuild/bufimagebuildtesting/bufimagebuildtesting.go
- private/bufpkg/bufimage/bufimagebuild/builder.go
- private/bufpkg/bufimage/bufimagebuild/builder_test.go
- private/bufpkg/bufimage/bufimagemodify/bufimagemodify_test.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufmodule/bufmoduleconfig/config_test.go
- private/bufpkg/bufmodule/bufmoduleprotocompile/bufmoduleprotocompile.go
- private/bufpkg/bufmodule/bufmoduleprotocompile/path_resolver.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref_test.go
- private/bufpkg/bufmodule/bufmoduletesting/bufmoduletesting.go
- private/bufpkg/bufmodule/bufmoduletesting/test_module_reader.go
- private/bufpkg/bufmodule/module_test.go
- private/bufpkg/bufwkt/cmd/wkt-go-data/main.go
- private/pkg/storage/storagemem/storagemem.go
A very common operation we want to do throughout our codebases is go from a `Module` to an `Image`. However, you can't - the question would be, why not?
The answer is that we have an intermediate state, a `ModuleFileSet`, that "flattens" a `Module` from what amounts to a set of .proto files and a lock file, to a set of combined .proto files that represent both the module's .proto files and the dependencies' .proto files. This is what we pass to i.e. `protocompile`. Currently, to compile a `Module`, you first need to make a `ModuleFileSet`, and then pass the `ModuleFileSet` to the `bufimagebuild.Builder`.
This can make some kind of sense in the abstract, but in practice, 99.9% of our usage of `bufimagebuild.Image` is someone creating a `ModuleFileSetBuilder` right before, creating a …
> Make bufimagebuild.Builder take a Module instead of a ModuleFileSet

- private/buf/bufwire/image_config_reader.go
- private/bufpkg/bufimage/bufimagebuild/bufimagebuild.go
- private/bufpkg/bufimage/bufimagebuild/builder.go
- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufmodule/module.go
Pulled from https://github.com/bufbuild/buf/pull/2151
@unmultimedio was in favor of this https://github.com/bufbuild/buf/pull/2151#discussion_r1218221725 this naming says what is actually going on here. In neither case are we saying "these are the dependencies" or "use these dependencies", we're saying "these are the declared dependencies from buf.yaml" and "these are the dependencies we expect, warn otherwise".
> Change DeclaredDependencies functions to be prefixed with Expected and Declared

- private/bufpkg/bufconnect/interceptors.go
- private/bufpkg/bufconnect/interceptors_test.go
In https://github.com/bufbuild/buf/pull/2171 we added server warnings in the happy path (reading the warning message from the response header), this PR updates that implementation to also log server warnings from errors.
> Update interceptor to log server warnings on error

- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufmodule/module.go
- private/bufpkg/bufmodule/module_file_set.go
- private/bufpkg/bufmodule/targeting_module.go
In service of https://github.com/bufbuild/buf/pull/2151. This exposes these two previously-private functions. In our code, wherever we build Modules, we end up providing these values, and they are very useful to have on a `bufmodule.Module` if you need them.
> Expose ModuleIdentity and Commit functions on Module

- private/buf/bufwire/bufwire.go
- private/buf/bufwire/image_config_reader.go
- private/buf/bufwire/module_config_reader.go
- private/buf/bufwire/module_config_set.go
- private/buf/bufwork/bufwork.go
- private/buf/bufwork/workspace_builder.go
- private/buf/cmd/buf/command/beta/price/price.go
- private/buf/cmd/buf/command/beta/stats/stats.go
- private/buf/cmd/buf/command/export/export.go
- private/buf/cmd/buf/command/format/format.go
This changes `ModuleConfigReader` to return the new `ModuleConfigSet` interface, which has a `Workspace` function, and deletes `ModuleConfig.Workspace()`. This has the effect of returning 0 or 1 workspaces for the `ModuleConfigs` returned from the `ModuleConfigReader`.
There is no valid case where you can have an input to `ModuleConfigReader` that results in multiple logical workspaces, and this is by design - if you are building a set of `Modules`, this is because they came from a (single) workspace.
During this change, I believe a bug is fixed for where `--config` overrides were being applied to all `Modules` within a `Workspace`, even though the config override was only meant to apply to a single `Module`.
There's tons of cleanup work to do after this, and understanding we need to …
> Change ModuleConfigReader to return an interface with a single Workspace

- private/bufpkg/bufimage/bufimage.go
- private/bufpkg/bufimage/bufimagebuild/bufimagebuild.go
- private/bufpkg/bufimage/bufimagebuild/builder.go
- private/bufpkg/bufimage/image.go
- private/bufpkg/bufimage/image_module_dependency.go
- private/bufpkg/bufimage/util.go
This adds the `bufimage.ImageModuleDependency` interface and `bufimage.ImageModuleDependencies` function, that returns the dependencies of a given image. This can be calculated based on the image, and can be used to determine what dependencies are direct vs transitive, based on the information currently in a `buf.module.v1alpha1.Module`. Having this information will let us implement `buf graph`, display dependency information on the BSR, etc.
`bufimage.ImageModuleDependency` is basically a union of `ModuleIdentity` and an optional `commit`, as well as an `IsDirect` function that returns whether or not the dependency is a direct dependency.
Some TODOs around the codebase were added in the process. Our import warnings in `bufimagebuild` should be able to use this.
> Add bufimage.ImageModuleDependencies

- private/pkg/dag/dag.go
- private/pkg/dag/dag_test.go
- Add `NumNodes` to return the number of nodes.
- Add `NumEdges` to return the number of edges.
- Rename `Walk` to `WalkEdges`
- Fix a bug where `WalkEdges` incorrectly returned an error when there were only nodes in the graph with no edges.
- Add `WalkNodes` that walks the nodes. This allows access to nodes with no edges.
- Update `DOTString` to print nodes without edges.
- Add testing.
> Improve private/buf/dag

- private/buf/cmd/buf/imports_test.go
- private/buf/cmd/buf/testdata/imports/success/workspace/valid_explicit_deps/buf.work.yaml
- private/buf/cmd/buf/testdata/imports/success/workspace/valid_explicit_deps/mod-a/a/v1/a.proto
- private/buf/cmd/buf/testdata/imports/success/workspace/valid_explicit_deps/mod-a/buf.yaml
- private/buf/cmd/buf/testdata/imports/success/workspace/valid_explicit_deps/mod-b/b/v1/b.proto
- private/buf/cmd/buf/testdata/imports/success/workspace/valid_explicit_deps/mod-b/buf.yaml
- private/bufpkg/bufgraph/builder.go
Pass expected direct dependencies to the build func. Fixes #2238
> Fix warning for buf beta graph

- private/bufpkg/bufplugin/bufplugindocker/docker_test.go
- private/bufpkg/bufplugin/bufplugindocker/testdata/success/Dockerfile
The build is failing for me locally with the latest version of Docker Desktop for Mac. It appears to be related to not having PATH set when executing the Docker build (failing with a `sw_vers` error).
> Fix test failure on recent Docker mac builds

- .github/workflows/windows.yaml
The built-in setup-go caching doesn't appear to use restore-keys, so if there are any changes to go.sum then the cache is bypassed. Update this to support restoring a cache even if the go.sum file changes.
> Switch to explicit actions/cache usage

- .github/workflows/buf-shadow-sync.yaml
- .github/workflows/buf-sync-shadow.yaml
This PR adds a workflow with the same rules as `buf.yaml`, to sync the repo in a private shadow repo under buftest org. This is with the purpose of dogfooding `buf sync` command.
> Dogfooding `buf sync` operations

- .pre-commit-hooks.yaml
The motivation is to be able to use `buf mod update` and `buf mod prune` as a pre-commit hook upon changes in the buf module and lock files. We currently have to do it with a repo local hook with system language.
> Add `buf mod` commands to pre-commit hooks

- private/pkg/storage/storagegit/bucket.go
- private/pkg/storage/storagegit/storagegit_test.go
- All paths should have `storageutil.Validate{Path,Prefix}` called on them at the entrypoint.
- `ExternalPath` being used potentially incorrectly here, it's a gray area, changing to `Path` for now.
- A few other normalization fixes.
> Fix path handling in storagegit

- private/buf/bufconvert/bufconvert.go
By fixing the constants.
Prev help output:
New output:
> Specify 'binpb' instead of 'bin' in the convert cmd help

- private/pkg/app/appproto/appproto.go
- private/pkg/app/appproto/response_writer.go
Drive-by PR when looking at something else.
> Move appproto private functions to the only file that uses them

- private/buf/cmd/buf/command/alpha/repo/reposync/reposync.go
- Use `StringSliceVar` as other flags in the codebase.
- Improve flag documentation.
> Fix modules flag type and docs

- private/buf/cmd/buf/command/beta/studioagent/studioagent.go
- private/pkg/cert/certclient/certclient.go
- private/pkg/cert/certclient/util.go
We have options to use http clients both for system certs or with user defined certs - but there are cases where we may want both.
> Add system + local option to http client TLS

- CHANGELOG.md
- private/buf/bufcurl/tls.go
- private/buf/cmd/buf/command/curl/curl.go
Previously, `buf curl` would complain if you tried to use `--http2-prior-knowledge` with secure "https" URLs.
Now, the flag is accepted and the client will _only_ use HTTP/2. This basically removes "http/1.1" from the set of supported protocols during ALPN, and if the server does not support ALPN (i.e. does not pick a protocol), it defaults to HTTP/2 (whereas it was previously defaulting to HTTP 1.1).
This can be used to work with secure servers that expect HTTP/2 but don't correctly implement ALPN to select "h2". This could be the case when using _network_ load balancers that terminate TLS (layer 4, instead of layer 7).
I tested this locally against a server using the grpc-go runtime (it does not use "net/http" and _only_ supports HTTP/2). I hacked the runtime so that it did _not_ use …
> The curl sub-command should support `--http2-prior-knowledge` with "https" URLs

- private/buf/bufsync/bufsync.go
- private/buf/bufsync/commits_to_sync_test.go
- private/buf/bufsync/syncer.go
- private/buf/cmd/buf/command/alpha/repo/reposync/reposync.go
Accept an **optional** module identity override for the module flag. This is useful when syncing a repository, to set a target module identity, regardless of what HEAD content has.
This will be useful for dog fooding the sync command on our own repos, or other community repositories with valid Buf modules, in case we don't want or can't write to the git history, but still want to sync all activity across all branches.
Before:
```sh
buf alpha repo sync \
--module my/proto/dir
```
Now:
```sh
buf alpha repo sync \
--module my/proto/dir
--module other/proto/dir:buf.build/acme/foo
```
> Buf sync: support module identity overrides

- CHANGELOG.md
- private/buf/bufsync/rebuild_module_test.go
- private/buf/bufsync/syncer.go
Missing nil-check catched when syncing `bufbuild/buf`.
> Fix rename module when no module identity

- CHANGELOG.md
- private/buf/bufconvert/bufconvert.go
- private/buf/buffetch/ref_parser.go
- private/buf/bufwire/proto_encoding_reader.go
- private/buf/bufwire/proto_encoding_writer.go
- private/buf/cmd/buf/command/convert/convert.go
Also fixes a naming inconsistency in `bufconvert` where `Textpb` was used instead of `Txtpb`.
> Fix issue where txtpb was not properly recognized

- .github/workflows/buf-shadow-sync.yaml
We can enable all branches now that `main` synced once: https://github.com/bufbuild/buf/actions/runs/5822579536
> Enable all branches sync

- private/buf/cmd/buf/command/lint/lint.go
- private/buf/cmd/protoc-gen-buf-lint/lint.go
- private/bufpkg/bufcheck/buflint/buflint.go
- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
- private/bufpkg/bufcheck/buflint/internal/buflintcheck/util.go
- private/bufpkg/bufimage/bufimage.go
- private/bufpkg/bufimage/image_file.go
- private/bufpkg/bufimage/util.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref.go
- private/bufpkg/bufmodule/bufmoduleref/file_info.go
- private/pkg/protosource/protosource.go
Our linters should not consider imports when reporting lint errors. For almost all of our linters, this means that we do not need access to the import descriptors when performing lint checks. However, this is not the case for a couple:
- `PACKAGE_NO_IMPORT_CYCLE` - this should report an import cycle even if it involves imports. It is a bug that we were not reporting this up until this point.
- Our upcoming linters for `protovalidate` - some require access to import descriptors.
This moves the import filtering to below the `buflint.Handler` level. The vast majority of our linters remain the same, and so do the helpers they call, however we have one helper, `newFilesWithImportsCheckFunc`, that passes import `protosource.Files` to the lint checker. When this is used, errors should still not …
> Pass imports to buflint.Handler and filter imports internally

- private/pkg/protoversion/package_version.go
- private/pkg/protoversion/protoversion.go
- private/pkg/protoversion/protoversion_test.go
Needed for an external case where we need to be able to parse `v0`'s.
> Add WithAllowV0 to PackageVersion construction

- private/gen/proto/connect/buf/alpha/registry/v1alpha1/registryv1alpha1connect/repository_branch.connect.go
- proto/buf/alpha/registry/v1alpha1/repository_branch.proto
Update the docs for the `GetCurrentDefaultBranch` rpc as it now correctly returns the branch mapped to the repository's default branch.
> Update docs for GetCurrentDefaultBranch

- private/buf/bufsync/prepare_sync_test.go
- private/buf/bufsync/syncer.go
Make sure that in a branch scope, each module directory has a unique module target.
> Validate no duplicate module targets across directories

- private/buf/bufcurl/verbose_transport.go
- private/buf/cmd/buf/command/curl/curl.go
According to [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent), it looks like I should add extensions to the user agent to the end, not the beginning. So this fixes the order to better comply with the way browsers construct user agent strings.
This also fixes a small bug: previously, the default Connect user-agent would be used for reflection requests, unless overridden with a `--reflect-header` argument. Now it uses the same user-agent as the other requests, which comes from the `--user-agent` argument and, lacking that, is the default Connect user-agent string plus `buf/<version>`. For example: `connect-go/1.11.1 (go1.20.1) buf/1.26.2-dev`.
> Fix user-agent used by `buf curl`

- private/buf/bufcli/errors.go
- private/buf/cmd/buf/command/mod/modprune/modprune.go
- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
Extends error handling for invalid remotes to include `permission_denied` (is it safe to drop the code check?). Connect errors were being unwrapped back to simple form removing the message, so avoid unwrapping if not handled in the connect check. 
Before: 
```diff
-Failure: 403 Forbidden
+Failure: 403 Forbidden. Are you sure "github.com" (derived from module name "github.com/tmc/buf-fhir-example") is a Buf Schema Registry?
```
Issue: https://bufbuild.slack.com/archives/CRZ680FUH/p1695882656754589
> Improve error message for invalid remotes

- .github/workflows/release.yaml
There was a [breaking change](https://github.com/tibdex/github-app-token/releases/tag/v2.0.0) in the `v2.0.0` release of `tibdex/github-app-token` that removes the `repository` key. Instead, an array of `repositories` are accepted. This change updates our release action configurations.
> Update `repository` to `repositories` in release action

- CHANGELOG.md
- private/buf/bufwire/module_config_reader.go
- private/buf/bufwork/workspace_builder.go
- private/buf/cmd/buf/testdata/workspace/success/breaking/a/proto/a/v1/a.proto
- private/buf/cmd/buf/testdata/workspace/success/breaking/a/proto/buf.yaml
- private/buf/cmd/buf/testdata/workspace/success/breaking/buf.work.yaml
- private/buf/cmd/buf/testdata/workspace/success/dir/a/proto/a/v1/a.proto
- private/buf/cmd/buf/testdata/workspace/success/dir/a/proto/buf.yaml
- private/buf/cmd/buf/testdata/workspace/success/dir/buf.work.yaml
- private/buf/cmd/buf/testdata/workspace/success/dir_buf_work/a/proto/a/v1/a.proto
- private/buf/cmd/buf/testdata/workspace/success/dir_buf_work/a/proto/buf.yaml
- private/buf/cmd/buf/testdata/workspace/success/dir_buf_work/buf.work
- private/buf/cmd/buf/workspace_test.go
- private/buf/cmd/buf/workspace_unix_test.go
- private/bufpkg/bufgraph/bufgraph_test.go
- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufmodule/bufmodulebuild/bufmodulebuild.go
- private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder.go
- private/bufpkg/bufmodule/bufmodulebuild/module_file_set_builder.go
- private/bufpkg/bufmodule/bufmodulebuild/util.go
- private/bufpkg/bufmodule/module.go
Fixes https://github.com/bufbuild/buf/issues/2480
This fixes the problem where in some occasions dependencies from workspace are not loaded correctly when `--path` is passed. For example, `buf build workspacedir/a --path workspacedir/a/foo.proto` when `workspacedir/b` and `workspacedir/c` also exist. In `module_file_set_builder.go` module b and module c would be hashed based on their `TargetFileInfos`, which are both empty slices due to the `--path` filter. Same hash means only one of them gets added to the list of potential dependencies.
In this PR, workspace modules are distinguished by their directories relative to the workspace directory. This is accomplished by adding `WorkspaceDirectory` to interface `bufmodule.Module`.
> Workspace directory

- .github/workflows/release.yaml
The argument needs to be JSON, so the string element in the array needs to be wrapped in `"`. See the [Github docs](https://docs.github.com/en/actions/learn-github-actions/variables), but doing `"${{ github.repository }}"` is valid.
> Fix usage of `tibdex/github-app-token` in Release workflow

- CHANGELOG.md
- private/pkg/storage/storagearchive/storagearchive.go
This commit introduces a workaround for an issue with .tar archives created with libarchive on Darwin/macOS. When encountering a file that has extended attributes, such as the com.apple.provenance attribute, it will add a corresponding AppleDouble file with the prefix "._" in the same directory. Because these files have the same filename otherwise, the buf tool will see these when they correspond to proto files and subsequently fail to parse them as protobuf IDL.
Due to the fact that libarchive is used by default with the version of tar that ships with macOS, and the provenance extended attribute is set by macOS under many conditions when SIP is enabled, archives with these files are likely to occur on macOS.
.zip archives created by libarchive do not seem to have this issue. However, …
> Add workaround for macOS archive xattrs

- private/pkg/transport/http/httpserver/httpserver.go
As written, the duration value is calculated when the defer function is registered. We should update it to be calculated when the defer is executed instead.
> Fix shutdown_finished duration field

- private/buf/cmd/buf/command/export/export.go
- private/bufpkg/bufanalysis/bufanalysistesting/bufanalysistesting.go
- private/bufpkg/bufimage/bufimage.go
- private/bufpkg/bufimage/image_file.go
- private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder_test.go
- private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder_unix_test.go
- private/bufpkg/bufmodule/bufmodulebuild/module_include_builder_test.go
- private/bufpkg/bufmodule/bufmoduleprotocompile/bufmoduleprotocompile.go
- private/bufpkg/bufmodule/bufmoduleprotocompile/path_resolver.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref.go
- private/bufpkg/bufmodule/bufmoduleref/file_info.go
- private/bufpkg/bufmodule/bufmoduletesting/bufmoduletesting_unix.go
- private/bufpkg/bufmodule/bufmoduletesting/bufmoduletesting_windows.go
- private/bufpkg/bufmodule/module.go
- private/bufpkg/bufmodule/module_file_set.go
- private/bufpkg/bufmodule/targeting_module.go
- private/bufpkg/bufmodule/targeting_module_test.go
As usual, works everywhere except `buf export`. Perhaps we can come up with a workaround in `buf export` (likely by tracking the dependency files outside of `ModuleFileSet`)? There's a TODO there, otherwise this is good to go.
> Remove IsImport from bufmoduleref.FileInfo and move to bufimage.ImageFile

- private/gen/proto/go/buf/alpha/registry/v1alpha1/repository_branch.pb.go
- proto/buf/alpha/registry/v1alpha1/repository_branch.proto
The git information is populated by the most recent commit in the branch history, not only from the branch latest commit.
> Fix branch docs

- private/buf/buffetch/internal/reader.go
- private/buf/bufgen/provider_test.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/beta/registry/plugin/pluginpush/pluginpush.go
- private/buf/cmd/buf/command/generate/generate_test.go
- private/buf/cmd/buf/imports_test.go
- private/buf/cmd/buf/workspace_unix_test.go
- private/bufpkg/bufapimodule/module_reader.go
- private/bufpkg/bufapimodule/module_resolver.go
- private/bufpkg/buflock/lock_file.go
- private/bufpkg/bufmodule/bufmodule.go
- private/bufpkg/bufmodule/bufmodulebuild/module_bucket_builder.go
- private/bufpkg/bufmodule/bufmodulecache/cas_module_cacher.go
- private/bufpkg/bufmodule/bufmoduleprotocompile/path_resolver.go
- private/bufpkg/bufmodule/bufmoduleref/bufmoduleref.go
- private/bufpkg/bufmodule/bufmoduletesting/test_module_reader.go
- private/bufpkg/bufmodule/multi_module_read_bucket.go
- private/bufpkg/bufmodule/nop_module_reader.go
- private/bufpkg/bufmodule/nop_module_resolver.go
- private/bufpkg/bufmodule/targeting_module.go
- private/bufpkg/bufmodule/util.go
- private/pkg/app/appproto/response_writer.go
- private/pkg/git/git_test.go
- private/pkg/storage/errors.go
- private/pkg/storage/map.go
- private/pkg/storage/multi.go
- private/pkg/storage/storagegit/bucket.go
- private/pkg/storage/storagemem/bucket.go
- private/pkg/storage/storageos/bucket.go
- private/pkg/storage/storagetesting/storagetesting.go
This converts the `storage` package to use `*fs.PathError` and `fs.ErrNotExist` instead of a custom `storage.NewErrNotExist` and `storage.IsNotExist`. This leans into the standard library, using the same `errors` as other codebases. This makes it easier to express not-exist errors in `Bucket` derivatives.
`*fs.PathError` is expected to have a value for `Op` - the stdlib annoyingly does not handle an empty value for `Op` in its printout of `Error()`:
```go
func (e *PathError) Error() string { return e.Op + " " + e.Path + ": " + e.Err.Error() }
```
We might want to file an issue for it to do so by not printing the leading space. Regardless, for now, we lean into this and set the `Op` to either `read` or `stat`, depending on what is most appropriate. This is somewhat congruent with what the …
> Convert storage to use fs.ErrNotExist and fs.PathErrors

- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufcheck/buflint/internal/buflintvalidate/field.go
- private/bufpkg/bufcheck/buflint/testdata/protovalidate_rules/oneof.proto
This adds a check in `PROTOVALIDATE` rules in `buf lint` that checks oneof fields do not have `(buf.validate.field).required`.
> Add check for required on oneof fields in buf lint

- private/buf/bufcli/bufcli.go
- private/buf/cmd/buf/buf.go
We've recently updated the language around this concept in the BSR - update it on the CLI as well.
Because this is an alpha command, I didn't bother to forward the old invocation to the new one, but I'm happy to add that. Also happy to add a CHANGELOG entry, but it doesn't look like we've typically mentioned changes to `alpha` commands in the past, with the exception of the removal of `alpha registry token create`.
There's a few other spots where we mention remote packages in comments or as field names in protos, but I don't think we want to include updates to those in the scope of this work?
> Change `buf alpha package` -> `buf alpha sdk`

- private/buf/bufsync/backfill_tags_test.go
- private/buf/bufsync/bufsync.go
- private/buf/bufsync/bufsync_test.go
- private/buf/bufsync/clock.go
- private/buf/bufsync/commits_to_sync_test.go
- private/buf/bufsync/prepare_sync_test.go
- private/buf/bufsync/syncer.go
- private/buf/cmd/buf/command/alpha/repo/reposync/reposync.go
- private/buf/cmd/buf/command/alpha/repo/reposync/sync_handler.go
- private/pkg/git/git.go
- private/pkg/git/repository.go
- private/pkg/git/repository_test.go
This also improves the testing to be blackbox; we invoke sync and assert on the end-state.
> Extract all `bufsync.*Func`s into a `bufsync.Handler`

- .github/workflows/create-release-pr.yaml
- make/buf/scripts/createreleasepr.bash
The checkout action needs a token for `git push` to work.
Also reverts the `git config` change.
> Fix permission issue from checkout action

- private/buf/bufsync/bufsync.go
- private/buf/bufsync/bufsync_test.go
- private/buf/bufsync/syncer.go
- private/buf/cmd/buf/command/alpha/repo/reposync/sync_handler.go
We never passed more than one hash in.
> Change `CheckSyncedGitCommits` to `IsGitCommitSynced`

- .github/workflows/back-to-development.yaml
- .github/workflows/build-and-draft-release.yaml
In `build-and-draft-release`, a GitHub App token is now used for creating the release, to be consistent with the other steps.
Also use a token to checkout the repository in `back-to-development`.
> Fix token usage in all release workflows

- private/buf/bufsync/syncer.go
- private/buf/bufwire/module_config_reader.go
- private/buf/bufwork/config.go
- private/buf/cmd/buf/command/beta/studioagent/studioagent.go
- private/buf/cmd/buf/command/breaking/breaking.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingcheck/bufbreakingcheck.go
- private/bufpkg/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
- private/bufpkg/bufcheck/internal/version_spec.go
- private/bufpkg/bufimage/util.go
- private/bufpkg/bufmodule/bufmoduleconfig/config.go
- private/bufpkg/bufmodule/targeting_module.go
- private/pkg/bandeps/state.go
- private/pkg/git/lister.go
- private/pkg/normalpath/normalpath.go
- private/pkg/normalpath/normalpath_unix_test.go
- private/pkg/normalpath/normalpath_windows_test.go
- private/pkg/slicesextended/slicesextended.go
- private/pkg/slicesextended/slicesextended_test.go
- private/pkg/slicesextended/usage.gen.go
- private/pkg/storage/storagetesting/storagetesting.go
- private/pkg/stringutil/stringutil.go
- private/pkg/stringutil/stringutil_test.go
- private/pkg/syncextended/syncextended.go
- private/pkg/syncextended/usage.gen.go
Some additional helpers in the existing `.*extended` style (`.*extended` packages extend stdlib packages). These use generics, which were not previously available when `stringutil` was created.
> Add slicesextended and syncextended

- private/pkg/storage/bucket.go
- private/pkg/storage/storagetesting/storagetesting.go
This also adds a test to the test suite to verify this property for all of our `storage.ReadBucket` implementations.
> Clarify that storage.ReadBucket.Walk should work when a path is given as a prefix

- private/buf/bufsync/bufsync.go
- private/buf/bufsync/bufsync_test.go
- private/buf/bufsync/syncer.go
- private/buf/cmd/buf/command/alpha/repo/reposync/sync_handler.go
This is preparation for protected branches being asserted server side.
> Move protected branch determination to handler

- private/buf/bufcurl/invoker.go
- private/pkg/protoencoding/json_unmarshaler.go
- private/pkg/protoencoding/protoencoding.go
Currently, `buf curl` transcodes the response from the binary format to JSON. However, if the response includes any unrecognized fields, they are just discarded since JSON does not emit unrecognized field data.
So this provides a cue to user's that such data might be in the response and getting dropped (which suggests an incomplete or out-of-date schema) by logging the presence of unrecognized bytes when the `-v` flag is used.
While in here, I noticed that this was allowing unrecognized fields in the JSON request provided to `buf curl`, which seems wrong since a likely issue with formulating a request will be a typo in a field name, which would just be ignored instead of validated. I was tempted to fix this by simply using `protojson` directly. I don't really understand the value of …
> Print count of unrecognized bytes in "buf curl"

- CHANGELOG.md
- private/buf/cmd/buf/command/curl/curl.go
- private/pkg/protoencoding/protoencoding.go
- private/pkg/protoencoding/resolver.go
This enables the use of multiple `--schema` flags, and it also enables using both `--reflect` and `--schema`. By default, if a `--schema` flag is present, reflection is not used. But if one also explicitly specifies `--reflect`, then both will be used.
The value is that sometimes an RPC response may include extensions or messages inside `google.protobuf.Any` values that are not defined in the same schema that defines the RPC service. For reflection, this is usually less of an issue. But it can still be an issue if the RPC server also does not know about an extension or message inside an `Any`, which can happen when the data actually originates in some other server before being returned by the RPC handling server.
When not using reflection, the value is even greater, since it is quite …
> Allow buf curl to use multiple schemas when resolving elements

- CHANGELOG.md
- private/bufpkg/bufcheck/buflint/internal/buflintvalidate/field.go
- private/bufpkg/bufcheck/buflint/testdata/protovalidate_rules/oneof.proto
Fixes https://github.com/bufbuild/buf/issues/2589.
This PR fixes the bug where `buf lint` incorrectly report error on proto3 optional fields.
> Fix buf lint mistaking proto3 optional fields for oneof fields

- private/pkg/storage/bucket.go
- private/pkg/storage/storageos/bucket.go
Use an interface so these can only be built by the `storage` package, clean up docs, clean up meaning of 0.
> Clean up storage.PutOptions

- private/buf/bufcli/bufcli.go
- private/bufpkg/bufapimodule/bufapimodule.go
- private/bufpkg/bufapimodule/module_reader.go
- private/bufpkg/bufapimodule/module_reader_test.go
`bufmoduleapi.ModuleReader` is also used in the elsewhere, where this reader does not need to print warning when a module is deprecated (the CLI is the only place where we print a warning). This also means other repos can keep calling `NewModuleReader(someDownloadClientFactory)`.
> Make logger and repository service client optional in api module reader

- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufcheck/buflint/internal/buflintvalidate/field.go
- private/bufpkg/bufcheck/buflint/testdata/protovalidate_rules/string.proto
This PR updates `PROTOVALIDATE` rule to stop checking whether `not_contains` contains `prefix`/`suffix`/`contains`, which does not imply invalid rules.
For example, `not_contains: "foo_bar", contains: "foo"` is valid because string `foo_` passes this check.
> Remove checking not_contains containing prefix/suffix/contains in buf lint for protovalidate

- .github/workflows/windows.yaml
Sometimes the existing workflow [runs quickly](https://github.com/bufbuild/buf/actions/runs/6896243827/job/18761936996) - sometimes it runs [incredibly slowly](https://github.com/bufbuild/buf/actions/runs/6905941659/job/18789829770).
This seems to come down to a disk I/O issue. The cache tarball will get downloaded very quickly, but then it will take minutes to untar. It's unclear why. I suspect there is something in particular wrong with the home directory in the Windows runner. In addition, `go test` itself seems to have unreliable performance characteristics.
Merely just moving the Go cache and path into the GitHub Actions `_temp` dir seems to vastly improve consistency. I ran the workflow multiple times to collect some runs:
- [**Attempt …
> Improve CI performance for Windows

- private/pkg/cache/cache.go
- private/pkg/cache/usage.gen.go
- private/pkg/dag/dag_test.go
- private/pkg/dag/dagtest/dagtest.go
- private/pkg/dag/dagtest/usage.gen.go
- private/pkg/slicesextended/slicesextended.go
- private/pkg/storage/bucket.go
- Add `slicesextended.Copy` to easily copy slices.
- Add `private/pkg/cache` that implements a simple cache that utilizes double-locking.
- Add `private/pkg/dag/dagtest` which has function `RequireGraphEqual` to test graphs.
- Add comment about `storage.ObjectInfo` stating that it is cachable.
> Add functionality to private/pkg

- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufcheck/buflint/internal/buflintvalidate/field.go
- private/bufpkg/bufcheck/buflint/testdata/protovalidate_rules/map.proto
- private/bufpkg/bufcheck/buflint/testdata/protovalidate_rules/repeated.proto
This PR fixes an issue where `buf lint` crashes when map rules are defined on a non-map field:
```
int32 not_a_map = 14 [
(buf.validate.field).map.values.int32.lt = 10,
(buf.validate.field).map.values.int32.gt = 1
];
```
The fix is to return early if type mismatches.
> Return early if map type mismatch in buf lint protovalidate

- private/buf/bufsync/syncer.go
- private/buf/bufwork/config.go
- private/buf/cmd/buf/command/breaking/breaking.go
- private/bufpkg/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
- private/bufpkg/bufcheck/internal/version_spec.go
- private/pkg/normalpath/normalpath.go
- private/pkg/slicesextended/slicesextended.go
- private/pkg/stringutil/stringutil.go
This unlocks more cases where `MapToSlice` is useful. This change is compatible with all existing usage of this function.
Should I rename it to something like `MapToSortedKeySlice`?
> Make MapToSlice accept maps with generic values, not just struct{}

- private/bufpkg/bufimage/image.go
Have the module identity and the file paths in the error message.
> Improve err message for different commit on image builder

- private/buf/bufwire/module_config_reader.go
- private/buf/cmd/buf/command/beta/studioagent/studioagent.go
- private/bufpkg/bufimage/util.go
- private/bufpkg/bufmodule/bufmoduleconfig/config.go
- private/bufpkg/bufmodule/targeting_module.go
- private/pkg/bandeps/state.go
- private/pkg/git/lister.go
- private/pkg/normalpath/normalpath_unix_test.go
- private/pkg/normalpath/normalpath_windows_test.go
- private/pkg/slicesext/slicesext.go
- private/pkg/slicesext/slicesext_test.go
- private/pkg/stringutil/stringutil.go
- Rename `ToMap` to `ToStructMap`.
- Add `ToValuesMap` that maps `[]V` to a `map[K]V` based on a `func(V)K`. Think `moduleFullNameToModuleRef := slicesext.ToValuesMap(moduleRefs, func(moduleRef ModuleRef) string { return moduleRef.ModuleFullName().String })`
- Add `Duplicates` to return duplicates in a slice. To be used in validation.
> Add functionality to slicesext

- private/pkg/stringutil/stringutil.go
Now that we have fully migrated to the equivalents in `slicesext`.
> Delete deprecated stringutil functions

- go.mod
- go.sum
This release includes a fix to a [panic bug](https://github.com/bufbuild/protocompile/issues/196). This would mainly impact `buf format`, which directly uses the `parser` sub-package. Most other usages, which go through the `protocompile.Compiler` type, wouldn't actually panic, but would return an ugly error describing the panic.
> Update to latest protocompile release

- private/bufpkg/bufcas/manifest.go
Adds a method to retrieve the `FileNode` by path on a `Manifest`. Currently if trying to retrieve the `FileNode` one must call `FileNodes()` and iterate over all to lookup by path.
> Add GetFileNode to bufcas.Manifest

- private/pkg/git/gittest/gittest.go
Depending on the version of local Git, repositories may be initialised with a different
default branch name for Git. This ensures that we are consistently using the `defaultBranch`
name passed in for the test.
> Pass in default branch name for `gittest` scaffold

- private/bufpkg/bufconfig/generate_managed_config.go
- private/bufpkg/bufconfig/generate_plugin_config.go
- private/bufpkg/bufconfig/generate_type_config.go
- private/bufpkg/bufimage/bufimagemodify/bufimagemodify_test.go
This PR:
* adds public constructors for `GeneratePluginConfig` and `GenerateTypeConfig`, so that other repos can create generation configs.
* renames the following:
`NewDisableRule` --> `NewManagedDisableRule`
`NewFileOptionOverrideRule` --> `NewManagedOverrideRuleForFileOption`
`NewFieldOptionOverrideRule` --> `NewManagedOverrideRuleForFieldOption`
`make testbufnew` passes
> Add public constructors for generation related configs.

- private/bufpkg/bufconfig/buf_yaml_file.go
- private/bufpkg/bufconfig/check_config.go
In buf.yaml v2, we want paths for `ignore` and `ignore_only` in `lint` and `breaking` to be relative to the workspace root, but paths in a `CheckConfig` should be relative to module roots, i.e. they are import paths. This PR adds this transformation for read and write.
> Parse lint and breaking ignore paths in buf.yaml v2

- private/buf/bufgen/generator.go
- private/bufpkg/bufimage/bufimagemodify/bufimagemodify.go
- private/bufpkg/bufimage/bufimagemodify/bufimagemodify_test.go
- private/bufpkg/bufimage/bufimagemodify/field_option.go
- private/bufpkg/bufimage/bufimagemodify/file_option.go
This PR makes two changes that unblocks other repos that depend on `bufimagemodify`:
* Add `ModifyXYZ` to `bufimagemodify` to allow modifying only some options.
- Technically this can be done by exposing some `GetDisablesForOtherOptions` and the caller can call `GetDisablesForOtherOptions(fileOpionA, fileOpionB)` to modify only A and B, but this operates on the assumption that no new file options will be added to the list of file options in managed mode.
* Add option `ModifyPreserveExisting` (this was a flag in v1, but not used by the CLI), which tells Modify[XYZ] not to modify an option if it's already set in the proto file.
TODO: Testing in this package needs to be revamped, especially after these functions are added.
> Update bufimagemodify exports

- README.md
This makes a few small changes to the README
* Adjust the one sentence description of the CLI to better match the repository tagline.
* Add a transition phrase to make the list of features read more naturally.
* Remove first bullet point, which appears to be a duplicate of the last bullet point in the list.
* Remove the features anchor. Both because it is unnecessary, and also because it might be interfering with the description Google is choosing when rendering search results.
See also: https://github.com/bufbuild/buf/pull/2672
> Improve description of Buf in README.md

- README.md
This change attempts to improve the description text in Google search results.
Before this change, text from the badge links shows up in the description:
Other similar repositories do not have this problem:
[connect-es](https://github.com/connectrpc/connect-es)
[connect-go](https://github.com/connectrpc/connect-go)
The above repos mostly don't use the short link syntax here so this PR tests the hypothesis that using short links contributes to the undesirable display.
[protovalidate](https://github.com/bufbuild/protovalidate) is a counter example where it does use short links but still renders correctly
It isn't clear whether this is the actual problem or not, but worth trying. If this doesn't help, we could revert this change, but I would also advocate for keeping it because I think it is …
> Inline badge links

- private/buf/cmd/buf/command/generate/generate.go
- private/bufpkg/bufconfig/buf_gen_yaml_file.go
- private/bufpkg/bufconfig/input_config.go
Externally, `include_paths` key in `inputs` in buf.gen.yaml v2 is changed to `paths`.
Internally (in Go code), we now refer to it as `targetPaths` whenever possible, instead of `includePaths`.
> Change include_paths option to paths

- private/buf/cmd/buf/command/generate/generate_test.go
- private/buf/cmd/buf/command/generate/testdata/v2/duplicate_plugins/a.proto
- private/buf/cmd/buf/command/generate/testdata/v2/duplicate_plugins/buf.gen.yaml
- private/buf/cmd/buf/command/generate/testdata/v2/simple/a/v1/a.proto
- private/buf/cmd/buf/command/generate/testdata/v2/simple/buf.gen.yaml
- private/buf/cmd/buf/command/generate/testdata/v2/simple/buf.yaml
This adds `v2` generate configs and modules to our
`buf generate` integration tests.
> Add `v2` generate configs and modules to `generate` integration tests

- .dockerignore
- .gitignore
- make/buf/all.mk
Switching back and forth between `main` and `bufmod` makes this a constant annoyance. Just doing this for now so there's no issues.
> Ignore private/buf/buftesting/cache

- make/buf/all.mk
Update the bufbuild/registry dependency to pin it to the commit prior to landing the refactor branch. This will allow main to continue to upgrade dependencies until the changes to incorporate the refactor branch are landed.
> Pin bufbuild/registry dependency to prior commit

- private/buf/bufgen/generator.go
We had a warning message where if the user has
managed mode options set but `enabled: false`: #1552.
This warning was originally implemented when reading
the config, which required the config reader to have access
to a logger.
Instead of passing around a logger to the config reader, we can
instead print this message when the `Generate` is called, since
the `generator` has access to a logger.
> Re-introduce managed mode enabled warning

- private/bufpkg/bufmodule/module_data.go
We were recursing back into `checkDigest`, which is wrapped in a `sync.OnceValues`, resulting in a deadlock.
> Fix deadlock on ModuleData methods

- private/buf/bufcurl/invoker.go
- private/buf/bufcurl/invoker_test.go
- private/buf/bufcurl/testdata/test.proto
- private/buf/bufcurl/testdata/testdata.txt
When `-v` is used, the command shows the amount of unrecognized data in the response. When it counts that data, a bug in one of the `case` expressions allowed it to fall into the wrong case (for a map whose values are _not_ messages). This would then result in a panic:
```
panic: type mismatch: cannot convert map to message
```
The panic actually happens whether or not the user includes a `-v` option, since this part of the code calculates and prints the value unconditionally. (If `-v` is _not_ specified, the "print" step is effectively a no-op.)
This branch fixes that panic and adds a test. The test uses a message with fields of every possible type (including groups) to make sure that all types are correctly handled without panic. The test reproduces the panic issue, and confirms the …
> Fix panic in `buf curl` that can happen with some map fields

- make/buf/all.mk
- make/buf/scripts/bufmodtodos.bash
- make/buf/scripts/newtodos.bash
This is a script for collecting all `TODO`s on `bufmod` that are
not on `main`. Sample output:
```
private/bufpkg/bufmodule/remote_dep.go: 44 // TODO: This needs a LOT of testing.
private/pkg/connectclient/connectclient.go: 21 // TODO: eliminate config, just make the below MakeOptions, add httpClient as a parameter to Make
private/pkg/dag/graph.go: 45 // TODO: It really stinks that we have to use the constructor. We have what amounts
private/pkg/slicesext/slicesext.go: 146 // TODO: Delete this in favor of slices.Clone.
private/pkg/slicesext/slicesext.go: 166 // TODO: Make ToStructMap use this logic, remove ToStructMapOmitEmpty, to match other functions.
private/pkg/slicesext/slicesext.go: 315 // TODO: Replace with slices.Sort when we only support Go versions >= 1.21. …
```
> Create a script to collect all bufmod TODOs

- go.mod
- go.sum
- private/buf/bufformat/formatter.go
This removes an AST node type that is no longer used (and was never actually allowed in the language... a mistake in protocompile). See https://github.com/bufbuild/protocompile/pull/229 for more details.
> Update protocompile to v0.8.0

- private/buf/bufctl/controller.go
- private/buf/buffetch/internal/reader.go
- private/buf/bufworkspace/option.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/generate/generate_windows_test.go
Overall, this PR resolves the TODOs that were set for duplicated path
separators in errors returned from Windows by addressing the following:
- `%q` when setting the error for excluded paths escaped the Windows file paths, which uses a separator that is already escaped, so this created "duplicated" backslashes
- found a buf in `buffetch` where we are not handling the root path component correctly
> Resolve TODOs for Windows duplicated path separator tests

- .golangci.yml
- private/buf/bufsync/syncer.go
- private/buf/cmd/buf/command/beta/graph/graph.go
- private/bufpkg/bufimage/bufimagemodify/java_multiple_files.go
- private/pkg/protosource/file.go
Seems like a reasonable check; removes some unnecessary extra code.
Some of these codepaths don't exist in `bufmod`, but happy to port over this check and fixes there as well.
> Enable govet nilness check and fix infractions

- private/buf/cmd/buf/command/mod/modprune/modprune.go
- private/buf/cmd/buf/command/mod/modupdate/modupdate.go
On an unknown remote ModuleIdentity may be nil. Use the fallback logic to select the correct dependency and derive the related module identity. Fixes #2725
A dial error for an invalid host will now correctly return the error formatted with a prompt to check the registry:
```
Failure: dial tcp: lookup private.registry: no such host. Are you sure "private.registry" (derived from module name "private.registry/org/dependency") is a Buf Schema Registry?
```
> Fix InvalidRemoteErr panic

- private/buf/cmd/buf/command/push/push.go
- private/bufpkg/bufconfig/buf_lock_file.go
- private/bufpkg/bufimage/util.go
- private/bufpkg/bufmodule/bufmoduletesting/cmd/buf-commit-id-to-dashless/commitidtodashless.go
- private/bufpkg/bufmodule/bufmoduletesting/cmd/buf-new-commit-id/newcommitid.go
- private/pkg/uuidutil/uuidutil.go
- private/pkg/uuidutil/uuidutil_test.go
Update the ToDashless function to not return an error, simplifying call sites. The error checking will only fail if there is a major issue in the uuid module and would be caught by existing unit tests in uuidutil_test.go.
> Simplify uuidutil.ToDashless to not return an error

- .github/workflows/buf-binary-size.yaml
- make/buf/all.mk
- make/buf/scripts/binarysize.bash
I constantly want access to the binary size for each commit. This is quick and dirty - a better option would be to print out the binary size for the latest commit on `main` as well, the latest release, and give more information (os/arch).
> Add make bufbinarysize and buf-binary-size GitHub Actions job

- .github/workflows/ci.yaml
Uses the official Docker action for generating tag names based on GitHub metadata. This should do the following:
- `latest` tag: Now should only be updated when there is a release tag. This is handled by the `flavor` argument.
- Added `edge` tag that matches the latest commit on main, similar to official Docker images.
- Added semver tags. A tag of v1.2.3 should result in pushes to `1`, `1.2` and `1.2.3` allowing users to track the latest v1 or latest patch release of a minor release.
~~I'm not sure how to actually test this, right now. I may need to set up a separate Docker repo on my fork.~~ Done, works.
P.S.: Merging into `main` first because we want to probably stop updating the `latest` tag ASAP.
P.P.S.: Just so it is clear, the way that Docker handles it indeed expects the semver …
> Improvements to Docker tagging set up

- .github/workflows/ci.yaml
Update the Docker build to specify standard opencontainers labels on images using hte docker/metadata-action.
> Add standard opencontainers labels to images

- private/buf/buffetch/buffetch.go
- private/buf/buffetch/message_ref.go
- private/buf/buffetch/ref_parser.go
- private/buf/bufwire/proto_encoding_reader.go
- private/buf/cmd/buf/command/convert/convert.go
Reverts https://github.com/bufbuild/buf/pull/2633. We want to limit this to just `buf convert --from` - there's no usecase otherwise (no need to validate `--to`, and `Images` do not use protovalidate).
> Revert "Add support for #validate=true to message refs (#2633)"

- private/pkg/protosource/option_extension_descriptor.go
- private/pkg/protosource/protosource.go
Pulling changes to `protosource` from https://github.com/bufbuild/buf/pull/2752 into its own PR.
> Add ForEachPresentOption method to optionExtensionDescriptor

- private/bufpkg/bufmodule/bufmoduleapi/registry.go
`GetGraphForModuleKeys` was attempting to determine a primary and secondary registry, but it was doing so by requiring that the Registry is unique across all deps. Instead, it should simply extract the unique registries.
> Fix `GetGraphForModuleKeys` requiring unique Registries

- private/buf/cmd/buf/command/push/push.go
`flags.Draft` and `flags.Branch` may be empty string, and they were being added to the labels name. Instead, I conditionally add them.
I also chose to detect empty strings in `flags.Labels` and `flags.Tags`, via `--label ''` or `--tag ''`.
> Prevent pushing with empty Label/Tag names

- private/bufpkg/bufimage/bufimage.go
- private/bufpkg/bufimage/image_test.go
This was to make it simpler and a little cheaper to make a deep copy of an image.
> Add bufimage.CloneImage

- go.mod
- go.sum
Update to the latest protovalidate-go, which includes support for the new ignore enum constraints.
> Update to protovalidate-go v0.6.0

- private/bufpkg/bufmodule/bufmoduleapi/universal_proto_content.go
We were using the `buf.yaml` file instead of the `buf.lock` file, resulting in duplicate file errors when calculating the B4 digest.
> Fix wrong v1/v1beta proto file in `newUniversalProtoContentForV1Beta1 `

- private/bufpkg/bufmodule/bufmoduleapi/universal_proto_content.go
- private/bufpkg/bufmodule/bufmoduleapi/universal_proto_file.go
For v1beta1/v1 modules, the registry _may_ return these files if it has them. The CLI should only use them to calculate digests if they are present.
> Fix panic on `buf.yaml` or `buf.lock` unset

- private/buf/buffetch/internal/read_bucket_closer.go
- private/buf/buffetch/internal/read_write_bucket.go
- private/buf/buffetch/internal/reader.go
- private/buf/buftarget/bucket_targeting.go
- private/buf/bufworkspace/workspace_dep_manager_provider.go
- private/buf/bufworkspace/workspace_targeting.go
- private/buf/bufworkspace/workspace_test.go
- private/buf/cmd/buf/buf_test.go
We were not defaulting to `v1` module behavior in `WorkspaceDepManager`
when we do not find a `v2` workspace before this. Now, if no `v2` workspace
was found for `WorkspaceDepManager`, we treat the `subDirPath` as a `v1` module
by default.
Also, this renamed `InputDirPath` to `SubDirPath` for clarity.
Lastly, this puts in a quick fix for the a `buf config init` test, since the shape of the
default config has changed.
> Fix `WorkspaceDepManager` to handle v1 module default behavior and rename `InputDirPath` to `SubDirPath`

- CHANGELOG.md
- private/buf/cmd/buf/command/build/build.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
This adds a flag that controls whether source-retention options are included in the output image or descriptor set from `buf build`.
I compared the output to `protoc` and did notice one small discrepancy: the code I wrote in `protocompile` leaves an empty `options` field if it happens to remove all options (i.e. if they were all source-retention). But `protoc` clears that field if it ends up empty. I can go make a small PR to `protocompile`, but I don't think the difference really matters or is worth holding any of this up.
(Never mind the unrecognized field 8042: I didn't use `--as-file-descriptor-set` with `buf build` when creating these files. So the right-hand column is actually an image, so it has that extra `ImageFile` field which is interpreted as an unrecognized field of …
> Add --exclude-source-retention-options flag to 'buf build'

- private/pkg/syncext/syncext.go
Backport upstream fix to syncext package to allow functions and their transitive allocations to be GC'd after the function is invoked.
> Set function to nil after running to allow GC

- private/bufpkg/bufmodule/module_set.go
Update to use DuplicateProtoPathError instead of a custom error. This allows callers to determine the specific errors to return to users and is consistent with how we return this same error in proto_file_tracker.go.
> Use DuplicateProtoPathError instead of custom error

- private/buf/bufmigrate/bufmigrate.go
This returns the path of the failing config file that cannot be read when
`buf config migrate` attempts to automatically gather workspace and
module configs by walking the input bucket. This gives the user clarity
on where the failing file is so they can either address it and/or set flags
for `buf config migrate`.
> Improve bufmigrate error

- private/bufpkg/bufcheck/buflint/internal/buflintvalidate/cel.go
- private/bufpkg/bufcheck/buflint/testdata/protovalidate_rules/cel_field.proto
This PR fixes linting for repeated fields with CEL expressions. Adds a new test case for lists (and maps) to ensure a valid expression passes. Small fix to set the type 'this' to the list element type.
Before:
```
testdata/protovalidate_rules/cel_field.proto:126:9:(buf.validate.field).repeated.items.cel.expression on field "allow_cidr" fails to compile: found no matching overload for 'isIpPrefix' applied to 'list(string).(int, bool)'
| this.isIpPrefix(4, true)
| ...............^
```
> Fix lint for repeated protovalidate CEL expression

- private/buf/bufpluginexec/bufpluginexec.go
With `v2` `buf.gen.yaml` the plugin name is already parsed with
`protoc-gen-<plugin name>` when this error is returned, so we no
longer need to prefix the plugin name with `protoc-gen` in the
error message.
> Clean up protoc-gen plugin error message

- .golangci.yml
- private/pkg/protoencoding/detrand.go
- private/pkg/protoencoding/detrand_test.go
- private/pkg/protoencoding/json_marshaler.go
- private/pkg/protoencoding/txtpb_marshaler.go
- private/pkg/protoencoding/yaml_marshaler.go
I've officially had it. The final straw was that prototext was borked and there's no `json.Compact` equivalent for prototext. Making `detrand.Disable` an internal-only function was always a bad idea, and now even Google is working around it in major libraries: https://github.com/google/starlark-go/blob/ee8ed142361c69d52fe8e9fb5e311d2a0a7c02de/lib/proto/proto.go#L774
I'm not linking to the issue on protobuf-go as to not link this issue in, but ask internally if you want to know the issue here.
If `detrand.Disable` is renamed, we will get a build-time error:
```
github.com/bufbuild/buf/private/pkg/protoencoding.init.0: relocation target google.golang.org/protobuf/internal/detrand.DisableMisspelled not defined
```
And if they rename it, it will break Google's own code. I think this is …
> Call detrand.Disable once and for all

- private/buf/cmd/buf/command/beta/registry/commit/commitlist/commitlist.go
- private/buf/cmd/buf/command/beta/registry/draft/draftdelete/draftdelete.go
Update the CLI to remove references to the "main" branch. The BSR is updated to allow empty references in ListRepositoryCommitsByReference to indicate the default branch. The DeleteRepositoryDraftCommit API already performs server-side validation to prevent deletion of the default branch.
> Remove references to the "main" branch

- private/buf/buffetch/internal/read_bucket_closer.go
- private/buf/buffetch/internal/reader.go
- private/buf/buffetch/internal/reader_test.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/testdata/failarchive/fail/buf.yaml
- private/buf/cmd/buf/testdata/failarchive/fail/buf/buf.proto
In order to treat archive and git refs the same way we treat dir
and proto file refs, we are handling `inputSubDirPath` already
in workspace targeting. This means that we should not actually
be remapping archive and git memory buckets if no controlling
workspace is found.
This was found in our bug bash when testing against an archive
with a `v1` module rooted at the input sub dir path. Added a test
case for this.
> Fix memory read bucket mapping when no controlling workspace is found

- private/buf/bufmigrate/migrate_builder.go
- private/buf/bufmigrate/migrator.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/config/configinit/configinit.go
- private/buf/cmd/buf/testdata/lint_ignore_disabled/buf.yaml
- private/buf/cmd/buf/testdata/lint_ignore_disabled/proto/a.proto
- private/buf/cmd/buf/testdata/lint_ignore_disabled/vendor/b.proto
- private/bufpkg/bufcheck/bufbreaking/bufbreaking.go
- private/bufpkg/bufcheck/bufbreaking/handler.go
- private/bufpkg/bufcheck/buflint/buflint.go
- private/bufpkg/bufcheck/buflint/handler.go
- private/bufpkg/bufconfig/buf_yaml_file.go
- private/bufpkg/bufconfig/buf_yaml_file_test.go
- private/bufpkg/bufconfig/check_config.go
Up until now, we have made it an error to do the following in your `buf.yaml` configuration:
```yaml
version: v1
lint:
ignore:
- .
```
This being an error made sense - this is saying that you'd like to ignore lint for all paths in the module. If you didn't want to lint the module, then...don't lint it.
However, this did not take into account workspaces. We have never provided a way for someone to ignore a module within a workspace for linting. Even pre-v2-configuration, this might be something you'd want to do:
```yaml
version: v1
directories:
- proto/module1
- proto/module2
- vendor
```
You may commonly want to not lint `vendor` while still being able to run `buf lint` for the entire workspace.
In v2, this really comes into the fore. We should provide a way for people to ignore a single …
> Allow disabling lint or breaking for an entire module via a configuration ignore

- go.mod
- go.sum
- private/bufpkg/bufplugin/bufplugindocker/docker.go
Run `make upgrade` and correct the deprecated docker options. Fixes https://github.com/bufbuild/buf/actions/runs/8418346210/job/23048666017
Closes #2840, closes #2839
> Make upgrade

- .golangci.yml
A previous commit in makego had this defined in the wrong place - it needs to be created under 'issues', not 'run'.
> Update exclude-dirs-use-default setting

- .dockerignore
- .gitignore
- make/buf/all.mk
- private/buf/bufgen/generator.go
- private/buf/cmd/buf/command/generate/generate_test.go
- private/buf/cmd/buf/command/generate/internal/protoc-gen-top-level-type-names-yaml/main.go
- private/buf/cmd/buf/command/generate/internal/protoc-gen-top-level-type-names-yaml/usage.gen.go
- private/buf/cmd/buf/command/generate/testdata/v2/local_plugin/a/v1/a.proto
- private/buf/cmd/buf/command/generate/testdata/v2/local_plugin/buf.basic.gen.yaml
- private/buf/cmd/buf/command/generate/testdata/v2/local_plugin/buf.yaml
- private/bufpkg/bufconfig/buf_gen_yaml_file.go
- private/bufpkg/bufconfig/generate_config_test.go
- private/bufpkg/bufconfig/generate_plugin_config.go
- windows/test.bash
This renames the `plugins.binary` key to `plugins.local` for `v2` `buf.gen.yamls`.
This also adds some test helpers to help test `buf generate`. A new test plugin `protoc-gen-top-level-type-names-yaml` is added that will list all the enums, message, and services at the top-level of the input in a `types.yaml` file. For example, if the `out` is `gen`, `gen/types.yaml` would contain (for an input with these types):
```yaml
enums:
- foo.v1.EnumOne
- foo.v1.EnumTwo
messages:
- foo.v1.MessageOne
services:
- foo.v1.ServiceOne
```
A test is added like this:
```go
func TestGenerateV2LocalPluginBasic(t *testing.T) {
t.Parallel()
tempDirPath := t.TempDir()
input := filepath.Join("testdata", "v2", "local_plugin")
template := filepath.Join("testdata", "v2", "local_plugin", "buf.basic.gen.yaml") …
```
> Rename plugin.binary to plugin.local for v2 buf.gen.yaml

- private/buf/cmd/buf/command/generate/generate_test.go
- private/buf/cmd/buf/command/generate/internal/protoc-gen-top-level-type-names-yaml/main.go
This modifies `protoc-gen-top-level-type-names-yaml` to output yaml files for each `.proto` file, instead of a single `types.yaml` file. This makes the plugin more inline with other common `protoc` plugins, and allows us to test `strategy: directory` properly.
The file `a/v1/a.proto` will result in `${OUT}/a/v1/a.top-level-type-names.yaml`.
> Modify protoc-gen-top-level-type-names-yaml to output per-proto-file yaml files

- private/buf/buffetch/internal/errors.go
- private/buf/buffetch/internal/internal.go
- private/buf/buffetch/internal/ref_parser.go
- private/buf/buffetch/ref_parser_test.go
- private/bufpkg/bufconfig/buf_gen_yaml_file.go
- private/bufpkg/bufconfig/input_config.go
This is intended to fix an issue that is commonly encountered when users try to pin an input to a particular commit of a git repo. The most intuitive parameter to use is `ref`, with a full commit hash. But the way that actually works is to clone the given `branch` (or repo's default branch if no `branch` param specified), only up to 50 commits deep (can be overridden/increased with `depth` param). This is a problem because, as more commits are added to the repo, the `ref` eventually falls out of the 50-commit depth of the branch's history.
It turns out, that one can use a full commit hash with the `tag` param instead. This pins to a commit perfectly. But `tag` is not an intuitive name for a parameter that accepts a commit hash.
So this PR simply allows users to use `commit` as a …
> Add 'commit' as an alias for 'tag' param in inputs that refer to git repos

- private/bufpkg/bufimage/bufimagemodify/field_option.go
- private/bufpkg/bufimage/bufimagemodify/override.go
Fix for a disable rule targeting a `field_option` being applied to a `file_option` and vice versa. For example the following `buf.gen.yaml` file:
```yaml
version: v2
managed:
enabled: true
disable:
- module: buf.build/emcfarlane/foo
field_option: jstype
override:
- file_option: go_package_prefix
module: buf.build/emcfarlane/foo
value: github.com/emcfarlane/foo
plugins:
- local: protoc-gen-go
out: gen
opt: 
- paths=source_relative
inputs:
- module: buf.build/emcfarlane/foo
```
The disable rule should not affect the `file_option: go_package_prefix`.
> Fix generate v2 disable rules exclusions

- private/bufpkg/bufconfig/buf_gen_yaml_file_test.go
- private/bufpkg/bufconfig/generate_managed_config.go
Field options were previously discarded resulting in the override being applied to all fields. Error on setting `field` for `file_option`.
> Fix field validation for file_option

- private/bufpkg/bufconfig/buf_gen_yaml_file.go
- private/bufpkg/bufconfig/buf_gen_yaml_file_test.go
- private/bufpkg/bufconfig/generate_plugin_config.go
For `buf.gen.yaml` v2 enforce plugins `out` as a required field with a non default empty string.
> Fix plugins field validation for out

- .golangci.yml
- go.mod
- go.sum
- private/bufpkg/bufimage/bufimageutil/testdata/options/a.proto
- private/bufpkg/bufimage/bufimageutil/testdata/options/all-exclude-options.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/options/all-with-Files.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/options/all.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/options/pkg.Foo.txtar
- private/bufpkg/bufimage/build_image.go
- private/pkg/protodescriptor/protodescriptor.go
This allows us to start implementing and testing logic for editions (which is mostly confined to protosource and bufbreaking), before actually having the CLI provide editions support to users. The idea is that users won't be able to use editions with the CLI until everything is updated to work correctly, but we need a way to enable the support until then, for testing any in-progress editions-specific work.
We have to use "shenanigans" with `go:linkname` because support isn't yet complete and enabled in protocompile, but it's complete "enough" for what we need to do in the CLI (or at least it will be after https://github.com/bufbuild/protocompile/pull/264 lands, and a new release is cut). Unfortunately, protocompile won't be "done-done" with editions support until we can get protobuf-go's …
> Provide mechanism to start implementing and testing editions-specific functionality

- private/bufpkg/bufconfig/buf_work_yaml_file.go
An invalid `buf.work.yaml` version will raise a system error on read:
`Failure: it looks like you have found a bug in buf. Please file an issue at https://github.com/bufbuild/buf/issues and provide the command you ran, as well as the following message: v2 is not supported`
Downgrade the error to report a decode issue:
`Failure: decode buf.work.yaml: v2 is not supported for buf.work.yaml files`
Other system errors for version are all on write, keep current system error behaviour.
> Fix error message for invalid buf.work.yaml versions

- private/buf/bufworkspace/workspace_targeting.go
For a v1 module config we expect to always receive `buf.yaml` as a v1 or v1beta1 source. Currently an invalid version will raise a system error:
`Failure: it looks like you have found a bug in buf. Please file an issue at https://github.com/bufbuild/buf/issues and provide the command you ran, as well as the following message: buf.yaml at proto did not have version v1beta1 or v1`
Downgrade the error to report version mismatch for config:
`Failure: buf.yaml at proto did not have version v1beta1 or v1`
> Fix error message for buf.yaml invalid version

- private/buf/bufmigrate/migrator.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/config/internal/internal.go
- private/buf/cmd/buf/command/mod/internal/internal.go
- private/bufpkg/bufcheck/bufbreaking/bufbreaking.go
- private/bufpkg/bufcheck/bufbreaking/handler.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingbuild/bufbreakingbuild.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingcheck/bufbreakingcheck.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingv2/bufbreakingv2.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingv2/vars.go
- private/bufpkg/bufcheck/bufcheck.go
- private/bufpkg/bufcheck/buflint/buflint.go
- private/bufpkg/bufcheck/buflint/handler.go
- private/bufpkg/bufcheck/buflint/internal/buflintbuild/buflintbuild.go
- private/bufpkg/bufcheck/internal/config.go
- private/bufpkg/bufcheck/internal/internaltesting/internaltesting.go
- private/bufpkg/bufcheck/internal/rule.go
- private/bufpkg/bufcheck/internal/rule_builder.go
- private/bufpkg/bufcheck/internal/runner.go
- private/bufpkg/bufcheck/internal/version_spec.go
- private/bufpkg/bufprotosource/bufprotosource.go
- private/bufpkg/bufprotosource/file.go
- private/bufpkg/bufprotosource/paths.go
This allows `Rules` to be deprecated and specify the IDs of their replacement `Rules`. If a Rule is deprecated:
- It is no longer printed via the `ls-rules` commands unless `--include-deprecated` is set.
- Any usage of the `Rule` is assumed to be the same as setting all its replacement `Rules`.
- If the deprecated `Rule` has no replacement `Rules`, the `Rule` becomes a no-op.
This is needed for editions work.
> Add concept of deprecated bufcheck Rules and make FILE_SAME_PHP_GENERIC_SERVICES the first deprecated Rule

- private/bufpkg/bufmodule/added_module.go
- private/bufpkg/bufmodule/module.go
- private/bufpkg/bufmodule/module_data.go
- private/bufpkg/bufmodule/module_key_provider.go
- private/bufpkg/bufmodule/module_set_builder.go
When a remote module is added to the workspace, the b5 digest of it should not be calculated based on the state of other modules in the workspace (which may point to later commits). Instead, the digest should be used from the ModuleKey for the remote module (if the key references a b5 digest) or it should be fetched from the CommitProvider.
> Fix b5 digest calculation for remote modules

- private/buf/cmd/buf/command/push/push.go
- private/bufpkg/bufmodule/bufmoduleapi/uploader.go
- private/bufpkg/bufmodule/uploader.go
This change allows users to push using `--tag`, `--branch`, or `--draft` with
`v2` workspaces.
Since `--branch` and `--draft` is no longer disallowed when pushing more than
one content module, we can now treat them as a single label.
For `--tag`, we push to all the tags as well as the default label of each module.
We disallow the use of `--tag` if the modules being pushed do not all have the
same default label.
> Support `--tag`, `--branch`, and `--draft` with v2 workspaces

- private/buf/cmd/buf/command/dep/internal/internal.go
Update the error message shown with 'buf dep update' if there are unused dependencies.
> Improve dep update error message

- .golangci.yml
- private/buf/bufgen/features.go
- private/buf/bufgen/features_test.go
- private/buf/bufgen/generator.go
- private/bufpkg/bufprotoplugin/bufprotoplugin.go
- private/pkg/protodescriptor/protodescriptor.go
This adds support for the new "supports editions" feature in `plugin.proto` and also updates code generation to use the plugin's min and max supported edition (when that new feature is supported).
This also makes the result, if the plugin does not support a feature, an _error_ instead of just a _warning_.
Currently, the structure of the code is that it writes all of the details about inadequate support to `stderr` and then returns an error. Perhaps it should pack all of those details about inadequate support _into_ the error that it returns? Looking for feedback on that, as well as on the format of the output when a plugin has inadequate support.
> Update code generation to enforce supported features for editions

- private/bufpkg/bufmodule/bufmodule_test.go
- private/bufpkg/bufmodule/module_dep.go
- private/bufpkg/bufmodule/module_set.go
This fixes an issue where we were ignoring the use of `buf.build/protocolbuffers/wellknowntypes`
as a  configured dependency by always skipping WKT import paths and then resolving the WKT
import at compile time.
This instead only skips the WKT path if it is not found in our module set, and otherwise adds
the module containing the WKT path as a dependency.
> Allow using WKT module as a dependency

- go.mod
- go.sum
- private/buf/bufctl/controller.go
- private/buf/cmd/buf/command/curl/curl.go
- private/bufpkg/bufimage/bufimage.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/build_image.go
- private/bufpkg/bufimage/image.go
For another arc of work (related to #2913), I was benchmarking the creation of resolvers and their use in re-parsing unrecognized fields (i.e. custom options) when loading images from a binary-encoded descriptor protos.
I happened to be using the _full_ `googleapis/googleapis` for the benchmark (nearly 5000 files), which really tickles the inefficiency of this resolver, since its look-ups were linear _with the number of files_.
So now, we use the compiler's symbol table as an index, to dead-reckon which file a symbol or extension is in. That improved the benchmarks drastically; using this resolver is now more efficient than creating and using a `*protoregistry.Types` (and less memory needed, too, since there are no additional data structures to create beyond the compiler's data …
> Improve efficiency of resolver backed by protocompile output

- private/buf/cmd/buf/command/push/push.go
- private/bufpkg/bufmodule/bufmoduleapi/uploader.go
- private/bufpkg/bufmodule/uploader.go
This PR adds the `--source-control-url` flag to `buf push`.
The `--source-control-url` flag allows the user to set a URL specific to the contents
of the modules pushed (e.g. the specific commit to browse in source control).
While the API allows for each module content to have a different source control URL,
similar to labels, we are setting a single source control URL for all module contents pushed.
> Add `--source-control-url` flag for buf push

- private/buf/cmd/buf/command/push/push.go
- private/bufpkg/bufmodule/bufmoduleapi/uploader.go
- private/bufpkg/bufmodule/uploader.go
This adds the `--create-default-label` flag to `buf push`, which allows
the user to set a default label name for a module they are creating with `--create`.
We do not allow this to be set if `--create` is not set, however, the user does
not need to set this if they are using `--create`. If this is not set during `--create`,
then the module will have a default label of "main".
> Add `--create-default-label` flag to `buf push`

- private/bufpkg/bufcheck/bufbreaking/bufbreaking_test.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingcheck/bufbreakingcheck.go
- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
- private/bufpkg/bufcheck/buflint/testdata/comments/a.proto
- private/bufpkg/bufcheck/buflint/testdata/comments/b.proto
- private/bufpkg/bufprotosource/field.go
- private/bufpkg/bufprotosource/location_store.go
- private/bufpkg/bufprotosource/message.go
This fixes the location reported for synthetic map entries and map entry fields. I ran into this because I needed to test the UTF8 validation feature in editions with maps with string keys and values.
Now that these messages and fields can report locations, this tickled an issue in the tests for the "comments" linter - now that it no longer returns a nil location, the linter wanted to find comments there. So I've updated that linter to ignore them. For consistency, I've also added ignore code for other generated elements that won't have comments: group fields and proto3-optional oneofs. The latter isn't strictly necessary since the location for synthetic oneofs currently returns nil. But for groups, it would complain that the field had no comments, even if there were a comment there, …
> Fix location of map entries in bufprotosource

- private/pkg/protoencoding/resolver.go
The `dynamicpb.NewTypes` function is fairly recent and is a perfect fit for `protoencoding.NewResolver`. This makes creation of the resolver a little more efficient since we don't have to redundantly register all types in `*protoregistry.Types` instance.
> Use dynamicpb.NewTypes in protoencoding.NewResolver

- private/bufpkg/bufprotosource/bufprotosource.go
Oops, I forgot to add this before merging #2934. My bad. This corrects that omission.
> Fix missing comment in bufprotosource

- go.mod
- go.sum
Release notes:
https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.34.1
> Use just-released v1.34.1 of protobuf-go

- private/buf/cmd/buf/command/build/build.go
- private/buf/cmd/buf/command/lsfiles/lsfiles.go
Small fix for the flag help message grammar on the build flag `--config` and change lsfiles `--config` flag to be consistent with others.
> Fix config flag message grammar for build

- CHANGELOG.md
These are change-log worthy, but I failed to make note of them in recent PRs.
Is this too wordy?
(Some of this is duplicated in change log updates in #2963. I was hoping to merge this first, just to update the change-log to reflect changes already merged into the dev branch. After that, I'll reconcile that other branch with whatever wordsmithing we land on here.)
> Update changelog to reflect recent work in buf breaking and buf lint

- .golangci.yml
- CHANGELOG.md
- private/buf/cmd/buf/buf_test.go
- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufcheck/buflint/internal/buflintbuild/buflintbuild.go
- private/bufpkg/bufcheck/buflint/internal/buflintcheck/buflintcheck.go
- private/bufpkg/bufcheck/buflint/internal/buflintv2/buflintv2.go
- private/bufpkg/bufcheck/buflint/internal/buflintv2/vars.go
- private/bufpkg/bufcheck/buflint/testdata/field_not_required/a.proto
- private/bufpkg/bufcheck/buflint/testdata/field_not_required/b.proto
- private/bufpkg/bufcheck/buflint/testdata/field_not_required/buf.yaml
This adds a new lint rule to disallow use of required fields.
Since this could break existing codebases that use `buf lint` and also use required fields, this is being added just to the v2 config.
> Add lint rule to prevent use of "required"

- .github/workflows/previous.yaml
- private/buf/bufcurl/tls.go
- private/buf/bufcurl/tls_version_name_go120.go
- private/buf/bufcurl/tls_version_name_go121.go
Ensure we run the previous build workflow on all supported older versions of Go. Fix use of newer tls.VersionName function introduced in Go 1.21 behind a build constraint.
> Update previous workflow to build 1.20.x

- go.mod
- go.sum
I was doing manual QA of buf breaking with an Editions file and ran into something strange, related to the C++ string type and Java UTF8 validation checks.
The issue turned out to be a bug in the helper function in `protocompile` that resolves custom features. This pulls in a fix to that function.
> Update protocompile to bring in a fix for buf breaking issue

- private/buf/bufformat/formatter.go
- private/buf/bufformat/formatter_test.go
- private/buf/bufformat/testdata/editions/editions.golden.proto
- private/buf/bufformat/testdata/editions/editions.proto
Thanks @stefanvanburen for noticing this!
The formatter needed to be updated to be aware of the `edition` AST node (which appears instead of `syntax` in Editions files) and also needed updates to reserved names, which use identifiers instead of string literals in Editions.
> Update buf format to work correctly with editions

- CHANGELOG.md
- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/command/beta/registry/label/labelarchive/labelarchive.go
- private/buf/cmd/buf/command/beta/registry/label/labelarchive/usage.gen.go
- private/buf/cmd/buf/command/beta/registry/label/labelunarchive/labelunarchive.go
- private/buf/cmd/buf/command/beta/registry/label/labelunarchive/usage.gen.go
This adds two very simple `beta registry` commands for managing
labels. `buf beta registry label archive` allows the user to archive a
specified label, `<registry>/<owner>/<module>/<label>`, and
`buf beta registry label unarchive` allows the user to unarchive a
specified label in the same format.
> Add `buf beta registry label` archive and unarchive commands

- private/buf/cmd/buf/buf_test.go
- private/bufpkg/bufcheck/bufbreaking/bufbreaking_test.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingcheck/bufbreakingcheck.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingv1/vars.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingv1beta1/vars.go
- private/bufpkg/bufcheck/bufbreaking/internal/bufbreakingv2/vars.go
While writing docs up for these I realized a couple of things:
1. They really needed to be included in the `WIRE_JSON` category (for likely obvious reasons).
2. It is backwards-compatible to go from "best effort" to "allow", just not vice versa.
> Tweak configuration of JSON format rules for buf breaking

- CHANGELOG.md
- data/template/buf.go.gen.yaml
- private/buf/buffetch/internal/reader.go
- private/buf/cmd/buf/workspace_test.go
- private/buf/cmd/buf/workspace_unix_test.go
In CLI versions pre-1.32.0, for archive and git refs, we would map
the root of the bucket of archive and git refs to the `subDirPath`,
which is inconsistent with the behavior for dir refs (which maps
target paths and target exclude paths to the execution context).
In 1.32.0, we made changes to handle subDirPath, target paths,
and target exclude paths in a unified way, however this is not
backwards compatible with pre-1.32.0 versions. So, in order
to be backwards compatible, we need to remap the target
paths and target exclude paths.
I explored an option to check of the subDirPath contains
the target paths and target exclude paths before remapping,
however this is brittle, since we could hit an edge case with
directories that have the same name nested:
```
.
└── proto
└── foo
└── foo
``` …
> Map target paths and target exclude paths for archive/git refs

- CHANGELOG.md
- private/buf/cmd/internal/internal.go
- private/buf/cmd/protoc-gen-buf-breaking/breaking.go
- private/buf/cmd/protoc-gen-buf-lint/lint.go
- private/buf/cmd/protoc-gen-buf-lint/lint_test.go
- private/buf/cmd/protoc-gen-buf-lint/testdata/fail/v2.yaml
Add `module` config option to protoc plugins. With v2 config the plugins only work if they find a module in the current directory. With this change users can provide the module that they are running the plugin against. Module accepts both the directory path and module full name.
> Add `module` config option to protoc plugins

- private/buf/cmd/buf/command/generate/generate.go
This PR updates the long description for the generate command (`buf generate --help`) to reflect the v2 configuration of `buf.gen.yaml`, including:
* updated plugin configs
* updated managed mode configs
* inputs configs
> Update buf generate long description

- private/pkg/git/git.go
Fix resolving of annotated tags on push with `--git-metadata` flag by fetching from the remote and then using `--points-at` to discover each ref and tag. Currently only lightweight tags are resolved as the commit sha for annotated tags doesn't directly point to the commit.
> Support annotated tags for push git metadata

- private/buf/cmd/buf/command/format/format.go
Similar to the `--help` for `buf generate`, `buf convert` and `buf export`. Should make the [generated docs](https://buf.build/docs/reference/cli/buf/format) also look better.
> Indent `buf format` help examples

- CHANGELOG.md
- private/buf/cmd/buf/command/push/push.go
This allows the user to override the behaviour of `--source-control-url`
and `--create-default-label` with their own values when using `--git-metadata`
flag with `buf push`.
The previous behaviour disallowed the user to set these values themselves
if the `--git-metadata` flag was set.
> Allow user to override --source-control-url and --create-default-label when using --git-metadata

- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufcheck/buflint/internal/buflintcheck/util.go
- private/bufpkg/bufcheck/buflint/internal/buflintvalidate/adder.go
- private/bufpkg/bufcheck/internal/helper.go
This is a proposal for an alternative to #3050. There are actually numerous places in the buf lint and breaking change rules where a location is provided for some element within a descriptor -- like a name, number, option, etc. But the descriptor's `source_code_info` only retains comments for complete declarations. So those other rules are subject to the same potential issue, and the fix is to include the descriptor's location as an ignore location in each of them.
Instead of updating every such rule, this change instead opts to address it more systematically, by _always_ using the descriptor's location as an ignore location (no need to explicitly pass it from every rule). So this undoes the two changes in the protovalidate checks as they are superseded by the change to the check helper …
> Include descriptor's location in set of ignore locations

- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
- private/bufpkg/bufimage/util.go
We had said months ago that we wanted to do this so that protoplugin could utilize this for a testing framework. I did the port, but never updated buf. This completes it, and I think after this we can delete `options.StripSourceRetentionOptionsFromFile` from `protocompile`.
> Complete move of StripSourceRetentionOptions to protoplugin

- CHANGELOG.md
I realized that recent changes (#3058 and #3031) may be change-log-worthy, so I've added entries for them.
> Add changelog entries for recent buf format changes

- CHANGELOG.md
- private/bufpkg/bufmodule/module_read_bucket.go
- private/bufpkg/bufprotosource/bufprotosource_test.go
- private/bufpkg/bufprotosource/file.go
- private/bufpkg/bufprotosource/testdata/nested/foo.proto
- private/pkg/slicesext/slicesext.go
There are usages of `append` where the result is not assigned back to the variable. After going through them, most of do not break. In fact, it only breaks things when one slice is stored as a variable or a struct's field, and a prefix of this slice is appended to.
This PR fixes problematic appends in `populateMessage`, which breaks in certain cases (see the test case added).
It also fixes the append in `WalkFileInfos`.
> Fix append calls that should have copied the slice

- CHANGELOG.md
- private/buf/bufgen/features.go
- private/buf/bufgen/features_test.go
- private/bufpkg/bufprotoplugin/bufprotoplugin.go
This works around an issue with some pre-v27.0 releases of protoc and the code generators there in (such as Java, C++, Python, etc).
Some of the languages advertised support for features, but in an experimental way, that did _not_ include the minimum and maximum edition fields being set. With v1.32.0+ of buf, code gen always fails because the min/max editions are missing. This changes the validation so that it only occurs when an actual input file uses editions. So if editions aren't used at all, the plugin's output will be used without any error messages.
> Only validate min/max editions in code gen response when input uses editions

- CHANGELOG.md
- private/buf/cmd/buf/command/push/push.go
- private/bufpkg/bufmodule/bufmoduleapi/registry.go
- private/bufpkg/bufmodule/bufmoduleapi/uploader.go
- private/bufpkg/bufmodule/uploader.go
This PR adds the flag `--exclude-unnamed` for `push`. On `push`, this flag will allow for unnamed modules to be present in the `buf.yaml` config. Modules are filtered by name before pushing to the remote. Local only modules, modules without a name, are excluded. All dependencies for a named module must have a valid name.
As an example the following config will work with `buf push --exclude-unnamed` as long as the module `foo` does not depend on `bar`:
```yaml
version: v2
modules:
- path: foo
name: buf.build/example/foo
- path: bar
```
> Add exclude unnamed flag for push

- CHANGELOG.md
- private/bufpkg/bufprotoplugin/bufprotoplugin_test.go
- private/bufpkg/bufprotoplugin/response_writer.go
On missing an insertion point, fail with a user facing error and avoid panic'ing due to an invalid slice when the insertion point file is empty.
Fixes #1649
From the issue, `buf` will now correctly return an error like:
```
Failure: plugin prost-crate: could not find insertion point "features" in "Cargo.toml"
```
> Fix missing insertion point error handling

- .golangci.yml
- buf.yaml
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/config/configlsmodules/configlsmodules.go
- private/buf/cmd/buf/testdata/lsmodules/extraconfigv1/buf.work.yaml
- private/buf/cmd/buf/testdata/lsmodules/extraconfigv1/buf.yaml
- private/buf/cmd/buf/testdata/lsmodules/extraconfigv2/buf.work.yaml
- private/buf/cmd/buf/testdata/lsmodules/extraconfigv2/buf.yaml
- private/buf/cmd/buf/testdata/lsmodules/workspaceinvalid/buf.work.yaml
- private/buf/cmd/buf/testdata/lsmodules/workspaceinvalid/proto/buf.yaml
- private/buf/cmd/buf/testdata/lsmodules/workspacev1/a_v1/buf.yaml
- private/buf/cmd/buf/testdata/lsmodules/workspacev1/b_no_name_v1/buf.yaml
- private/buf/cmd/buf/testdata/lsmodules/workspacev1/buf.work.yaml
- private/buf/cmd/buf/testdata/lsmodules/workspacev1/c_v1beta1/buf.yaml
- private/buf/cmd/buf/testdata/lsmodules/workspacev1/f_no_name_v1beta1/buf.yaml
- private/buf/cmd/buf/testdata/lsmodules/workspacev1/not_pointed_by_workspace/buf.yaml
- private/buf/cmd/buf/testdata/lsmodules/workspacev2/buf.yaml
This PR
* adds test for `buf config ls-modules`
* update the command to error when both `./buf.yaml` and `./buf.work.yaml` exist
> Add tests for buf config ls-modules

- private/bufpkg/bufprotoplugin/bufprotoplugin.go
- private/bufpkg/bufprotoplugin/bufprotoplugin_test.go
- private/bufpkg/bufprotoplugin/response_writer.go
Small improvements on creating insertion points. Removes the need to trim the resulting file for newlines. Removes a buffer allocation to build each insertion.
> Improve insertion point behaviour

- private/buf/cmd/buf/command/push/push.go
- private/pkg/git/git.go
- private/pkg/git/remote.go
Git commands often need to shell out to other commands, and so running consistently with the environment set (in particular PATH) fixes issues running in certain environments.
Additionally, wrap a few errors to make it easier to determine the reason for failures with the --git-metadata flag.
> Set environment when running git commands

- private/buf/bufworkspace/workspace_targeting.go
- private/buf/cmd/buf/testdata/workspace/fail/v2/overlap/buf.yaml
- private/buf/cmd/buf/testdata/workspace/fail/v2/overlap/proto/buf/buf.proto
- private/buf/cmd/buf/workspace_test.go
In the past, if the an overlap is found between `moduleDirPath` and `inputPath`,
but `inputPath` does not exist (e.g. `moduleDirPath == "."` and `inputPath == "fake-path"`)
then it would return the error:
```
failed to build input "fake-path" because it is contained by module at path "." specified in your configuration, you must provide the workspace or module as the input, and filter to this path using --path"
```
Which isn't particularly clear, since `fake-path` doesn't exist. Added a check to return a
nicer error to the user by checking `inputPath`. Also included test cases for `v1` and `v2`
workspaces.
> Return a more user-friendly error in workspace targeting for overlaps

- private/buf/bufstudioagent/bufstudioagent_test.go
Tests `TestPlainPostHandlerTLS/invalid_upstream` and `TestPlainPostHandlerH2C/invalid_upstream` are [flaky](https://github.com/bufbuild/buf/actions/runs/9599996622/job/26475130640?pr=3102), because the listener only calls `Accept` once, and when it accepts a connection from something other than the agent, the listener calls it a day, leaving the agent hanging.
This PR makes the listener repeatedly accept new connections until it has accepted a connection from the agent.
Running `go test -count=1 -timeout=20s -race github.com/bufbuild/buf/private/buf/bufstudioagent` on main on my laptop would fail (with timeout) this test within the first 5 times, and trying it on this branch, it doesn't fail (tried 100 times and it hasn't failed).
TLDR: random ports can make connection with the listener …
> Fix studio agent flaky test

- private/buf/bufctl/controller.go
- private/buf/buffetch/buffetch.go
- private/buf/cmd/buf/buf_test.go
- private/bufpkg/bufconfig/buf_yaml_file.go
- private/bufpkg/bufconfig/lint_config.go
This PR exposes the top-level lint and breaking configs for `buf.yaml` files.
For `v1` `buf.yaml` files, there is only ever one `ModuleConfig`, so the
corresponding lint and breaking configs are used.
For `v2` `buf.yaml` files, if a top-level lint and/or breaking config exists, then
we return those.
Otherwise, `TopLevelLintConfig()`/`TopLevelBreakingConfig` will return `nil`.
We use the top-level lint/breaking configs, if possible, with image inputs, since we
cannot determine which specific `v2` module config to use with images. In
the case where there is no top-level config, we fall back to defaults.
Fixes #3080
> Set top-level `LintConfig` and `BreakingConfig` and use for image inputs

- private/buf/cmd/buf/buf.go
Users interacting with a remote BSR may see an auth error when using the env variable BUF_TOKEN. This is reported as:
`Failure: the BUF_TOKEN environment variable is set, but is not valid.`
To help users identify which remote was used, we now report the remote in the error message:
`Failure: the BUF_TOKEN environment variable is not valid for buf.build.`
This can help clarify which remote was used. As an example this can be caused when a modules dependencies are on a different BSR instance then the parent module.
> Improve auth error for BSR remotes

- CHANGELOG.md
- private/buf/bufgen/bufgen.go
- private/buf/bufgen/generator.go
- private/buf/cmd/buf/command/generate/generate.go
- private/buf/cmd/buf/command/generate/generate_test.go
- private/bufpkg/bufprotoplugin/bufprotopluginos/bufprotopluginos.go
- private/bufpkg/bufprotoplugin/bufprotopluginos/cleaner.go
Fixes https://github.com/bufbuild/buf/issues/2437.
> Add buf generate --clean flag

- .github/workflows/buf-ci.yaml
Bumps to the latest release, no changes in behaviour.
> Bump buf-action CI from 0.1 to 0.2

- CHANGELOG.md
- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
This removes the requirement to provide your username when calling `buf registry login`. On login the token is validated by fetching the current user. The username is used only to validate that the current token is associated with the user but is otherwise redundant. The flag has now been marked deprecated and is hidden.
The output of the login command is also updated to be more user friendly prompting the user to visit the web UI to create a token if they do not have one. On successful login the user is informed that they are logged in as the current user.
Token via prompt:
```
$ buf registry login
Enter the BSR token created at https://buf.build/settings/user.
Token:
Logged in as emcfarlane. Credentials saved to /Users/edward/.netrc.
```
Token via stdin:
```
$ echo ${BUF_TOKEN} | buf …
```
> Remove username prompt on buf registry login

- private/bufpkg/bufcheck/buflint/buflint_test.go
- private/bufpkg/bufcheck/buflint/internal/buflintvalidate/cel.go
- private/bufpkg/bufcheck/buflint/internal/buflintvalidate/field.go
- private/bufpkg/bufcheck/buflint/testdata/protovalidate/proto/cel_field.proto
This fixes https://github.com/bufbuild/buf/issues/3161.
`buf lint` for protovalidate should work correctly for both
```
repeated int32 ints = 1 [(buf.validate.field).repeated.items.cel = {
id: "..."
message: "..."
expression: "this > 2"
}];
```
and 
```
repeated int32 ints = 1 [(buf.validate.field).cel = {
id: "..."
message: "..."
expression: "size(this) > 2"
}];
```
This PR fixes the bug in second case where `buf lint` thought `this` is an `int32`, while it should be a _list_ of `int32`.
> Fix repeated field resolution in CEL for buf lint protovalidate rule

- private/bufpkg/bufremoteplugin/bufremoteplugin.go
- private/bufpkg/bufremoteplugin/dotnet_target_framework.go
- private/bufpkg/bufremoteplugin/dotnet_target_platform_test.go
The mapping functions for target frameworks are useful in other places, so export them for use.
> Export target framework conversion functions

- CHANGELOG.md
- private/buf/bufgen/bufgen.go
- private/buf/bufgen/generator.go
- private/buf/cmd/buf/command/generate/generate.go
- private/buf/cmd/buf/command/generate/generate_test.go
- private/bufpkg/bufconfig/buf_gen_yaml_file.go
- private/bufpkg/bufconfig/buf_gen_yaml_file_test.go
- private/bufpkg/bufconfig/generate_config.go
- private/bufpkg/bufconfig/generate_plugin_config.go
This PR targets branch `add-buf-gen-yaml-clean` and moves `clean` to `buf.gen.yaml`'s top level, from the plugin level.
> Move clean config option to the top level of generation config

- make/buf/all.mk
- make/buf/dockerfiles/Dockerfile.release
- make/buf/scripts/release.bash
This installs `zip` with `apt-get` in `release.bash`, when it's run inside a docker image.
> Install zip before using it in the release process

- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
- private/buf/cmd/buf/command/registry/registrylogout/registrylogout.go
- private/pkg/netext/netext.go
- private/pkg/netext/netext_test.go
We don't do explicit validation of the domain in 'buf registry login', which leads to some confusing error messages. Update the command to validate the domain with netext.ValidateHostname and update ValidateHostname to not accept URLs (it previously didn't look up the port number so it didn't perform proper validation).
> Validate domain in buf registry login and logout

- CHANGELOG.md
- private/buf/bufworkspace/workspace_targeting.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/testdata/successnobufyaml/buf/buf.proto
When calling our fallback logic checking for workspaces, we
check in the target paths to see if a valid workspace/module
is found. However, we should only be checking directories and
not target paths, such as `--path path/to/my.proto` (we want to
check `path/to`).
Tests have been added for both the relative and absolute directory
inputs without `buf.yaml` files.
Fixes #3183
> Only check directories in workspace targeting fallback logic

- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/config/configinit/configinit.go
- private/bufpkg/bufconfig/buf_yaml_file.go
- private/bufpkg/bufconfig/buf_yaml_file_test.go
This adds a comment at the top of the `buf.yaml` file generated from
`buf config init` with a link to our public docs to make it easier for users
who are onboarding to get more information on `buf.yaml` configs.
Running `buf config init` generates a `buf.yaml` with the following contents:
```
version: v2
lint:
use:
- DEFAULT
breaking:
use:
- FILE
```
The comment is preserved when round-tripping `buf.yaml`.
Fixes #3180
> Add a comment with link to docs for `buf config init`

- CHANGELOG.md
- private/buf/bufcurl/bufcurl.go
- private/buf/bufcurl/headers.go
- private/buf/bufcurl/reflection_resolver.go
- private/buf/bufcurl/resolver.go
- private/buf/cmd/buf/command/curl/curl.go
This adds `--list-services` and `--list-methods` flags which change the behavior of `buf curl`, causing it to list known services or methods, instead of invoking an RPC.
> Add --list-services and --list-methods flags to buf curl

- private/buf/bufworkspace/workspace_targeting.go
- private/pkg/storage/storageos/bucket.go
- private/pkg/storage/storageos/storageos_test.go
This PR fixes a bug of the storage bucket where it does not return an `fs.ErrNotExist` error when it should.
It happens when both conditions met:
* The bucket is created with an absolute path, i.e. `provider.NewReadWriteBucket("/absPath")`
* `bucket.Get(ctx, "existing.file/foo")` is called, where `existing.file` exists as a regular file.
Fixes https://github.com/bufbuild/buf/issues/3185
> Fix storage OS bucket not returning ErrNotExist correctly

- private/buf/cmd/buf/command/generate/generate.go
- private/buf/cmd/buf/command/lsfiles/lsfiles.go
- private/buf/cmd/buf/command/push/push.go
Continuation of https://github.com/bufbuild/buf/pull/3200, lowercases the remaining deprecated flags.
> Fix deprecated flag casing for flags

- CHANGELOG.md
- private/pkg/git/cloner.go
- private/pkg/git/git_test.go
Remove refspec annotation for tags. Annotated tags cannot be mapped to a local ref.
Fixes #3197
> Fix git checkout for annotated tags

- .github/workflows/buf-ci.yaml
Removes the `username` config for v0.3, upgrades to v1.
> Bump buf-action CI from v0.2 to v1

- private/buf/cmd/buf/buf_test.go
- private/bufpkg/bufcheck/buflint/internal/buflintbuild/buflintbuild.go
- private/bufpkg/bufcheck/internal/rule_builder.go
We have allowed the purpose strings for rules to be based on configuration. However, for our 100+ rules, we only used this in two places, and both of those places don't really need it. Making purpose strings static can result in the new plugin API being massively simplified.
> Remove all dynamic purpose strings based on configuration

- private/bufpkg/bufprotosource/bufprotosource.go
- private/bufpkg/bufprotosource/file.go
- private/bufpkg/bufprotosource/location.go
- private/bufpkg/bufprotosource/merge_comment_location.go
Just some slight changes.
- Name change to make the field clearer.
- `protodesc.Resolver` is all that we need, whereas `protoencoding.Resolver` has a bunch more methods.
> Change Path to SourcePath and reduce protoencoding.Resolver to protodesc.Resolver in bufprotosource

- private/buf/bufwkt/cmd/wkt-go-data/main.go
- private/bufpkg/bufcheck/bufbreaking/handler.go
- private/bufpkg/bufcheck/buflint/handler.go
- private/bufpkg/bufimage/build_image_test.go
- private/bufpkg/bufprotosource/bufprotosource.go
- private/bufpkg/bufprotosource/bufprotosource_test.go
- private/bufpkg/bufprotosource/file.go
- private/bufpkg/bufprotosource/files.go
This narrows the scope required to build `[]File` from `bufimage.Image` to [F InputFile]([]InputFile)`, where `InputFile` is a new, minimal interface with only the items that `bufprotosource` needs.
Note that this will result in a breakage in three locations in core, but just `s/image/image.Files(), image.Resolver()/` in those three `NewFiles` calls and all should work.
> Remove extraneous deps within bufprotosource

- private/buf/bufworkspace/workspace_targeting.go
- private/bufpkg/bufmodule/module_read_bucket.go
For large repositories, buckets can be slow to iterate over. Use memory backed buckets to reduce file access for both doc and license files. This can speed up builds by up to 2/3 on large repositories by avoiding iterating over os storage buckets. As an example running build of a single proto file in a large workspace of 96k files takes 1.60s with `v1.36.0`, 1.06s with `v1.31.0` and 0.56s with this change.
This is a simpler approach to #3230 but can be used in conjunction with it.
> Cache doc and license storage buckets

- private/buf/bufcli/rules.go
- private/buf/cmd/buf/command/config/internal/internal.go
- private/buf/cmd/buf/command/mod/internal/internal.go
- private/bufpkg/bufcheck/bufcheck.go
- private/bufpkg/bufcheck/internal/rule.go
This updates `bufcheck.Rule` to match `bufplugin/check.Rule` by removing `json.Marshaler`. It also cleans up `bufcheck.PrintRules` which was never in style with the rest of the codebase (it was one of the first functions written in bufbuild/buf, and it was done so hastily, without functional options). It also does some separation of concerns by moving flag-specific logic to `bufcli`.
> Update bufcheck.Rules logic to match upcoming bufplugin Rules

- CHANGELOG.md
- private/bufpkg/bufremoteplugin/bufremoteplugindocker/docker.go
- private/bufpkg/bufremoteplugin/bufremoteplugindocker/docker_test.go
This PR adds logic to retrieve the docker image digest from the status field following a successful push. There are some cases where the `Aux` field is not used, and instead, we have to parse it out of the `Status` field.
I've mentioned it in the comment, but adding it here for brevity, the string we're parsing from is:
https://github.com/moby/moby/blob/1c282d1f1b90ff188a1b46f48548ac3151ca2ddf/daemon/containerd/image_push.go#L126-L133
For a bit more context, I've opened an issue upstream https://github.com/moby/moby/issues/48331, but afaics there isn't a better way.
Without this change, I was getting failures pushing a plugin against images built with [containerd image store](https://docs.docker.com/desktop/containerd/) feature enabled. The plugin was pushed, but we failed to parse out …
> Parse docker image digest from Status if Aux not available

- private/bufpkg/bufconfig/generate_config.go
- private/bufpkg/bufconfig/generate_config_test.go
- private/bufpkg/bufconfig/generate_managed_config.go
- private/bufpkg/bufconfig/generate_plugin_config.go
Primarily needed because we're about to have `PluginConfig` in addition to `GeneratePluginConfig`, but also did a bunch of cleanups as it went to make it all consistent with each other.
> Make generate config types/files/variables consistent with naming

- private/buf/bufgen/generator.go
- private/bufpkg/bufprotoplugin/generator.go
- private/pkg/bandeps/checker.go
- private/pkg/thread/thread.go
`thread.ParallelizeWithCancel` would call a provided `context.CancelFunc` if any given job failed. However:
- All we wanted to do was make sure a cancel was sent to `ctx` on any job failure.
- Every time we called `thread.ParallelizeWithCancel`, we created the `CancelFunc` right before it:
```go
// This is every call we made.
ctx, cancel := context.WithCancel(ctx)
defer cancel()
return thread.Parallelize(ctx, jobs, thread.ParallelizeWithCancel(cancel))
```
This was confusing and unnecessary - all we need to do is create a `CancelFunc` within `Parallelize` if we want this behavior.
This PR updates the option to do just this, along with a rename in line with this behavior.
> Update thread.ParallelizeWithCancel to thread.ParallelizeWithCancelOnFailure that no longer takes a context.CancelFunc

- private/bufpkg/bufremoteplugin/bufremotepluginref/bufremotepluginref.go
The version suffix should be parsed from the last ':' present in the string to avoid splitting the string on the address of the BSR. For example the value '0.0.0.0:60156/protocolbuffers/go:v1.33.0' is a valid plugin reference.
> Fix parse plugin references for hosts with ports

- private/buf/cmd/buf/command/beta/registry/plugin/pluginpush/pluginpush.go
This PR adds support for pushing docker images built with the [containerd image store](https://docs.docker.com/desktop/containerd/) feature enabled. Specifically, we need to handle [image index](https://github.com/opencontainers/image-spec/blob/v1.1.0/image-index.md) digests.
Without these changes users trying to push plugins might run into the following error (in the case an image already exists in the registry):
> Failure: no child with platform linux/amd64 in index {registry}/asdf/go-json@sha256:4830ada11bc5df2123086fbc85af7ac9555db7c7095b0ea982cf372aa9a0c84f
This is because in [`getImageIDAndDigestFromReference`](https://github.com/bufbuild/buf/blob/b029c1f2151dff3f08c848c3e797a4c248840e57/private/buf/cmd/buf/command/beta/registry/plugin/pluginpush/pluginpush.go#L437-L440) we were …
> Improve support for docker plugins built with containerd image store

- CHANGELOG.md
- private/pkg/git/cloner.go
- private/pkg/git/git_test.go
Annotated tag [fix](https://github.com/bufbuild/buf/pull/3198) caused a regression on `ref=HEAD~` and similar git refs. We need to be more lenient with error handling to try the fallback checkout, before finally resolving the checkout. 
Fixes https://github.com/bufbuild/buf/issues/3265
> Fix git checkout for relative HEAD refs

- .golangci.yml
- private/bufpkg/bufcheck/internal/cmd/buf-plugin-protovalidate-ext/handlers.go
This fixes the [lint error](https://github.com/bufbuild/buf/actions/runs/10690978756/job/29636516892?pr=3288) of a test plugin calling a deprecate method, `GetSkipped`.
> Fix linting for a test lint plugin

- .github/workflows/make-upgrade.yaml
Routine make upgrades are failing. See https://github.com/bufbuild/buf/actions/runs/10665104712/job/29621728404 . Looks related to the golangci-lint go version. Force go version to be 1.23, avoid caching of deps to avoid poising caches on upgrades.
> Chore fix make upgrade go version

- private/buf/bufworkspace/workspace_provider.go
If there is a config override, we need to populate the plugin configs from
the override for module refs.
> Populate plugin configs from override for module refs

- CHANGELOG.md
- private/bufpkg/bufcheck/client.go
- private/bufpkg/bufcheck/lint_test.go
- private/bufpkg/bufcheck/testdata/lint/comment_ignores_with_trailing_comment/a.proto
- private/bufpkg/bufcheck/testdata/lint/comment_ignores_with_trailing_comment/buf.yaml
This fixes the problem where comment ignores with a trailing comment is not recognized as a comment ignore:
```
// buf:lint:ignore PACKAGE_DIRECTORY_MATCH some comment ...
```
> Fix comment ignore with trailing comment not recognized

- .golangci.yml
- go.mod
- go.sum
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/bufimageutil/testdata/options/Files.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/options/all-with-Files.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/options/all.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/options/pkg.Foo.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/options/pkg.FooEnum.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/options/pkg.FooService.Do.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/options/pkg.FooService.txtar
Removes the dep on github.com/golang/protobuf. See discussion in #3308.
Closes #3308
> Update bufimageutil test to protoprint v2

- private/pkg/storage/storageos/storageos_test.go
Fix flaky test failing to remove all as file is still open. Forces the close on the opened bucket object. Removes the t.Cleanup to allow testing to handle windows closes more gracefully. See https://github.com/golang/go/blob/c208b913954514ac7cab0fa701fba9c89af70392/src/testing/testing.go#L1271
```
--- FAIL: TestOS (0.00s)
--- FAIL: TestOS/get_non_existent_file_symlink (1.27s)
testing.go:1232: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestOSget_non_existent_file_symlink229375574\001\foo.txt: The process cannot access the file because it is being used by another proces
```
> Fix flaky symlink test on windows

- private/buf/bufcurl/resolver.go
- private/buf/cmd/buf/command/curl/curl.go
Appends a WKT resolver, by default, to the list of provided schemas. This WKT resolver is needed on request or responses that include a `google.protobuf.Any` that contains a WKT when marshalling to and form JSON (for displaying to the user). 
Tested on a custom server. Resolvers are used starting from the reflection service, next schemas, then finally WKT image. This allows overriding the WKT if a schema is provided that includes them.
> Add WKT resolver for bufcurl

- .golangci.yml
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/workspace_test.go
- private/bufpkg/bufcheck/bufcheckserver/internal/buflintvalidate/numeric.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/import_tracker.go
- private/bufpkg/bufimage/util_test.go
This probably should have been done a long time ago. This forces usage of `private/pkg/protoencoding` so that we don't keep on getting marshal/unmarshal problems, and stay consistent. A follow-up should do this in core as well.
> Force usage of private/pkg/protoencoding

- private/pkg/protoencoding/json_marshaler.go
- private/pkg/protoencoding/json_unmarshaler.go
- private/pkg/protoencoding/protoencoding.go
- private/pkg/protoencoding/txtpb_marshaler.go
- private/pkg/protoencoding/txtpb_unmarshaler.go
- private/pkg/protoencoding/wire_unmarshaler.go
- private/pkg/protoencoding/yaml_marshaler.go
- private/pkg/protoencoding/yaml_unmarshaler.go
This changes the behaviour of protoencoding to always set a resolver on init, defaulting to the `protoencoding.EmtpyResolver`. Currently, Marshaller and Unmarshallers will default to the `protoregistry.GlobalTypes` if a nil resolver is set. To keep the same behaviour the caller must pass in the GlobalTypes explicitly.
> Default protoencoding resolver to an empty resolver 

- private/buf/cmd/buf/workspace_test.go
Eagerly close the file by using `storage.PutPath`. The logic on `t.Cleanup` looks correct but we don't need to hold the file open for the entire test.
```
--- FAIL: TestWorkspaceNestedArchive (6.49s)
testing.go:1232: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestWorkspaceNestedArchive931609167\006\testdata\workspace\success\v2\nested\archive.zip: The process cannot access the file because it is being used by another process.
```
> Fix flaky zip archive test

- .github/workflows/previous.yaml
We are up to Go 1.22 now. As of Go 1.21, we no longer need to go back three versions, and we went to 1.22 a while back.
> Remove CI for Go 1.21

- private/buf/bufprotopluginexec/protoc_proxy_handler.go
- private/bufpkg/bufimage/bufimagefuzz/bufimagefuzz_unix_test.go
- private/pkg/git/cloner.go
- private/pkg/storage/storagetesting/storagetesting.go
- private/pkg/tmp/tmp.go
- private/pkg/tmp/tmp_test.go
Makes cleanup rely on context cancellation instead of directly depending on signals. Also does a few other associated cleanups - this was an old package.
> Cleanup tmp package

- private/pkg/app/app.go
- private/pkg/interrupt/interrupt.go
- private/pkg/interrupt/interrupt_other.go
- private/pkg/interrupt/interrupt_unix.go
This standardizes on `signal.NotifyContext` and cleans up the build tags. We still want to additionally handle `syscall.SIGTERM` - it's moderately annoying that the stdlib doesn't provide a platform-specific variable for this.
> Clean up interrupt package

- README.md
Update buf README to reflect that IntelliJ/GoLand support is available and fix some links (and remove unused ones).
> Update buf README to include newer features

- CHANGELOG.md
- private/buf/bufprint/bufprint.go
This adds information for the default label name of a module
to the JSON output of `buf registry module info`. The text output
remains unchanged.
```
$ buf registry module info buf.build/bufbuild/registry
Name                         Create Time
buf.build/bufbuild/registry  2023-10-27T20:23:20Z
$ buf registry module info buf.build/bufbuild/registry --format json | jq .
{
"id": "11bdb5abfb544d54b2a3b7a354a07112",
"remote": "buf.build",
"owner": "bufbuild",
"name": "registry",
"create_time": "2023-10-27T20:23:20.396779Z",
"state": "MODULE_STATE_ACTIVE",
"default_label_name": "main"
}
```
> Add `default_label_name` to JSON output of `buf registry module info`

- private/buf/cmd/buf/command/push/push.go
This provides more details for users in the deprecation messages
for `--tag`, `--draft`, and `--branch`, including commands that can
be used to replace their current use-cases.
```
$ buf push --tag bar
Flag --tag has been deprecated, use --label instead. Replace "buf push --tag <tag-name>" with "buf push --label <default-label-name> --label <label-name>" (<tag-name> and <label-name> are equivalent in this case).
You can also use "buf registry commit add-label <remote/owner/module:commit> --label <label>" to add a label to an existing commit.
<commit>
$ buf push --draft bar
Flag --draft has been deprecated, use --label instead. Replace "buf push --draft <draft-name>" with "buf push --label <label-name>" (<draft-name> and <label-name> are equivalent in this case).
<commit>
$ buf push …
```
> Provide clearer instructions in buf push deprecation messages

- private/pkg/storage/multi.go
Small optimization for `multiReadBucket`. The goal is to avoid a `Stat` call when overlay is enabled and the file is found.
> Add short-circuit to multi read bucket in overlay mode

- private/buf/buftarget/controlling_workspace.go
- private/bufpkg/bufprotoplugin/bufprotoplugin.go
- private/pkg/protosourcepath/README.md
- private/pkg/protosourcepath/enum.go
- private/pkg/protosourcepath/enumvalue.go
- private/pkg/protosourcepath/field.go
- private/pkg/protosourcepath/message.go
- private/pkg/protosourcepath/method.go
- private/pkg/protosourcepath/protosourcepath.go
- private/pkg/protosourcepath/service.go
This PR clarifies the documentation for the `protosourcepath` package,
both in the `README` and in-line comments.
> Improve docs for protosourcepath package

- private/pkg/app/app.go
- private/pkg/interrupt/interrupt.go
- private/pkg/interrupt/interrupt_other.go
- private/pkg/interrupt/interrupt_unix.go
This exposes `interrupt.Signals`, removes `interrupt.NotifyContext`, and adds `interrupt.Handle`, which does the functionality that most programs will want.
> Cleanup interrupt even further

- private/buf/buflsp/file.go
This change makes it so that the LSP publishes diagnostics on refresh regardless of whether there are any diagnostics to publish. This is necessary, because if there are currently N diagnostics displayed for the current file, we need to explicitly set them to zero on some clients, such as VSCode, when the user updates the file to be syntactically/semantically correct.
In other words, not doing this results in red squiggles that don't go away after fixing the issue.
> Make LSP always publish diagnostics

- private/pkg/slogapp/slogapp.go
- private/pkg/slogapp/slogapp_test.go
As part of the migration to slog, stack traces are now computed and included in logs at `slog.LevelError` and above. Update the `zapslog` handler to pass `slog.LevelError+1` as the level at which stack traces should be included, which should better match the previous behavior of buf when using zap.
In prior releases of buf before the migration to slog, `zaputil.NewLogger` called `zap.New` without passing the `zap.AddStacktrace` option, which meant that the `addStackAt` level defaulted to `zapcore.FatalLevel + 1` (disabling the inclusion of stack traces in logs).
> Omit stack trace from error level logs

- private/buf/cmd/buf/command/generate/generate.go
Noticed this in `buf generate --help` / on the docs site.
> Fix typo in buf generate template file

- private/bufpkg/bufcobra/bufcobra.go
- private/bufpkg/bufcobra/config.go
For the `buf` CLI, we always have a config, but this might not
be true, and therefore we should allow generating with no config.
> Allow webpages to have an empty config

- go.mod
- go.sum
Updates to the latest buf gen registry APIs. Closes #3412, closes #3400, closes #3399.
> Update protocolbuffers go to v1.35.1

- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
To aid debugging include the remote in the error response for invalid tokens. This helps debug cases where the user didn't set the correct domain.
> Include remote for invalid token errors

- private/buf/buflsp/server.go
> Fix LSP leading comment formatting

- private/buf/buflsp/server.go
In the case that the formatted text is the same as the existing text in the document, we shouldn't return a TextEdit. (This manifests in needing multiple undo operations in an editor to get back to a change, because the TextEdit is registered as a change to the document despite not changing the text.)
> Avoid returning TextEdit on empty diff

- go.mod
- go.sum
- private/buf/bufcurl/verbose_transport.go
- private/pkg/storage/limit.go
- private/pkg/storage/storageos/bucket.go
- private/pkg/storage/storagetesting/storagetesting.go
- private/pkg/thread/thread_test.go
The primitives in sync/atomic are not as good as those in uber/atomic; happy to drop this.
> Drop go.uber.org/atomic in favor of sync/atomic

- private/buf/buflsp/file.go
- private/buf/buflsp/report.go
- private/buf/buflsp/server.go
This removes the extraneous information from the diagnostic report (filename, line, column), which is already included in the range.
It also adds a hard-coded `buf` as the source of the diagnostic.
Before:
After:
> Improve LSP diagnostic info

- private/buf/cmd/buf/command/generate/generate.go
This adds the `clean` key to the example `buf.gen.yaml` in
the `buf generate` command long description.
> Add `clean` key to `buf generate` long description

- private/buf/cmd/buf/command/registry/module/modulecommit/modulecommitlist/modulecommitlist.go
- private/buf/cmd/buf/command/registry/module/modulelabel/modulelabellist/modulelabellist.go
This fixes the output of `buf registry module commit list` and `buf registry module label list` to return the non-deprecated command when outputting the help docs.
> Fix buf registry modules listing help output

- private/bufpkg/bufcheck/bufcheckserver/internal/bufcheckserverhandle/lint.go
The annotation for `FIELD_NOT_REQUIRED` did not
pass in the field name.
> Fix annotation for FIELD_NOT_REQUIRED rule

- private/buf/buflsp/symbol.go
This PR adds three new hoverable things in the LSP:
1. You can hover over the path of an import to show the contents of that file.
2. You can hover over the tag of a field to show its varint encoding.
3. You can hover over the number of an enum value to show its varint encoding and hex/bin values.
Example of varint encoding hovers:
> Add more types of hovers to LSP

- CHANGELOG.md
- private/buf/bufcli/errors.go
- private/buf/bufcli/flags_args.go
- private/buf/bufprint/bufprint.go
- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/command/registry/plugin/plugincreate/plugincreate.go
- private/buf/cmd/buf/command/registry/plugin/plugincreate/usage.gen.go
- private/buf/cmd/buf/command/registry/plugin/plugindelete/plugindelete.go
- private/buf/cmd/buf/command/registry/plugin/plugindelete/usage.gen.go
- private/buf/cmd/buf/command/registry/plugin/plugininfo/plugininfo.go
- private/buf/cmd/buf/command/registry/plugin/plugininfo/usage.gen.go
- private/buf/cmd/buf/command/registry/plugin/pluginupdate/pluginupdate.go
- private/buf/cmd/buf/command/registry/plugin/pluginupdate/usage.gen.go
This adds new plugin registry commands to get, create, delete and update plugins in the BSR. These commands are used for the upcoming check plugins.
The trimmed output from `buf registry plugin --help`:
```
Manage BSR plugins
Usage:
buf registry plugin [flags]
buf registry plugin [command]
Available Commands:
create      Create a BSR plugin
delete      Delete a BSR plugin
info        Get a BSR plugin
update      Update BSR plugin settings
```
> Add registry plugin commands

- private/buf/buflsp/symbol.go
The crash is a nil dereference when creating a tag symbol, if the tag happens to be nil. This can happen if the field is missing a tag number (and under other circumstances).
> Fix a crash when opening files that contain fields with no numbers

- private/buf/bufcli/connectclient_config.go
- private/bufpkg/bufconnect/interceptors.go
This adds an interceptor for RPC-level debug logs that were lost
when the tracing instrumentation was removed (#3374).
Fixes #3484
> Add debug logging interceptor for RPC logs

- CHANGELOG.md
- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
Prior to this change, we used a map to keep track of imports
when filtering an image based on type. This resulted in a bug
where iterating through the imports was non-deterministic, and
resulted in non-deterministic images.
This change uses an ordered set for imports instead of a map.
Fixes #3506
> Use ordered set for imports to iterate deterministically when filtering an image

- CHANGELOG.md
- private/buf/bufcli/flags_args.go
- private/buf/bufprint/bufprint.go
- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/command/registry/plugin/pluginlabel/pluginlabelarchive/pluginlabelarchive.go
- private/buf/cmd/buf/command/registry/plugin/pluginlabel/pluginlabelarchive/usage.gen.go
- private/buf/cmd/buf/command/registry/plugin/pluginlabel/pluginlabelinfo/pluginlabelinfo.go
- private/buf/cmd/buf/command/registry/plugin/pluginlabel/pluginlabelinfo/usage.gen.go
- private/buf/cmd/buf/command/registry/plugin/pluginlabel/pluginlabellist/pluginlabellist.go
- private/buf/cmd/buf/command/registry/plugin/pluginlabel/pluginlabellist/usage.gen.go
- private/buf/cmd/buf/command/registry/plugin/pluginlabel/pluginlabelunarchive/pluginlabelunarchive.go
- private/buf/cmd/buf/command/registry/plugin/pluginlabel/pluginlabelunarchive/usage.gen.go
This adds `buf registry plugin label {archive,info,list,unarchive}` commands to manage BSR plugin labels.
The trimmed output of `buf plugin registry label --help`:
```
Manage a plugin's labels
Usage:
buf registry plugin label [flags]
buf registry plugin label [command]
Available Commands:
archive     Archive a plugin label
info        Show label information
list        List plugin labels
unarchive   Unarchive a plugin label
```
> Add `buf registry plugin label` commands

- private/bufpkg/bufmodule/module_read_bucket.go
In the case where multiple modules have shared module roots
due to the `includes` key in the module configuration, when using
a proto file ref with the `includes_package_files` option (https://buf.build/docs/reference/inputs/?#protofile)
the proto file ref may not exist in the module. We need to check for
that and skip accordingly.
> Fix shared module read bucket for proto file refs and include_package_files

- private/bufpkg/bufconfig/buf_lock_file.go
This adds missing validation for buf.lock plugins to ensure duplicates and invalid digest types are correctly checked.
> Improve validation for buf.lock plugins

- go.mod
- go.sum
- private/bufpkg/bufcheck/bufcheckserver/internal/buflintvalidate/field.go
We had a breaking change in protovalidate-go v0.8.0, nothing major. Also updates protoyaml-go to v0.3.0 for the same reason.
Looks like the structured field path API might make it possible to improve this code. That said, it looks pretty carefully constructed, so I chose to do a 1:1 update instead. "First, do no harm."
I'll leave it to the reviewers to decide if I should be more aggressive about trying to refactor the code instead.
> Update protovalidate-go to v0.8.0

- private/buf/buflsp/file.go
Since lint and breaking change detection are more
expensive, we do not need to run them on every single
file refresh. Instead, we use the top-level LSP lock and a
short stagger (5ms) and only run when the attempt to get
the top-level lock is successful. Otherwise, we no-op and
assume that the checks are handled by another `Refresh`
request.
> Stagger lint and breaking checks in LSP Refresh

- private/buf/buflsp/symbol.go
- private/buf/buflsp/symbol_test.go
This PR introduces a new `formatComment` function to enhance the formatting of comments displayed in hover definitions. The implementation handles both single-line and multi-line comments, ensuring proper formatting while maintaining Markdown compatibility.
As shown above, hover definitions currently display unnecessary asterisks from the proto file's comment syntax, making the documentation harder to read.
The new implementation removes the redundant asterisks while preserving the comment's structure, resulting in cleaner and more readable documentation in hover definitions.
> Improve lsp hover definition comment formatting

- private/buf/bufmigrate/migrator.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/beta/lsp/lsp.go
- private/buf/cmd/buf/command/breaking/breaking.go
- private/buf/cmd/buf/command/config/internal/internal.go
- private/buf/cmd/buf/command/lint/lint.go
- private/buf/cmd/buf/command/mod/internal/internal.go
- private/buf/cmd/buf/command/plugin/pluginpush/pluginpush.go
- private/buf/cmd/protoc-gen-buf-breaking/breaking.go
- private/buf/cmd/protoc-gen-buf-lint/lint.go
- private/bufpkg/bufcheck/breaking_test.go
- private/bufpkg/bufcheck/bufcheck.go
- private/bufpkg/bufcheck/lint_test.go
- private/bufpkg/bufcheck/multi_client_test.go
- private/bufpkg/bufcheck/runner_provider.go
- private/bufpkg/bufconfig/plugin_config.go
- private/bufpkg/bufplugin/plugin.go
- private/pkg/pluginrpcutil/pluginrpcutil.go
- private/pkg/pluginrpcutil/wasm_runner.go
This adds a new bufplugin.RunnerProvider to support remote wasm plugins. The constructor `bufcheck.NewRunnerProvider` has been renamed to `NewLocalRunnerProvider` to clarify the runner interacts with the local filesystem when invoking plugins. It now takes a `bufplugin.PluginKeyProvider` and `bufplugin.PluginDataProvider` to resolve and load remote plugin references.
This also changes the PluginConfig to fix arguments for different plugin types. The method Path has been split into Name and Args. This is analogous to the naming in the std libraries `exec.Command` function. Name must not be empty. Args may be nil, but are valid for all plugin types. The name is either the path to the binary, the path to the wasm binary, or the fullname of the plugin in the form remote/owner/name.
Subset of …
> Add bufplugin.RunnerProvider for remote plugins

- .golangci.yml
- buf.yaml
- private/buf/bufformat/bufformat.go
- private/buf/bufgen/generator.go
- private/buf/buflsp/symbol_test.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/alpha/protoc/flags_test.go
- private/bufpkg/bufcheck/bufcheckserver/internal/bufcheckserverhandle/field_default_test.go
- private/bufpkg/bufcheck/multi_client.go
- private/bufpkg/bufconfig/buf_lock_file.go
- private/bufpkg/bufconfig/buf_work_yaml_file_test.go
- private/bufpkg/bufconfig/generate_config_test.go
- private/bufpkg/bufimage/bufimagemodify/bufimagemodify_test.go
- private/bufpkg/bufmodule/bufmoduleapi/module_key_provider.go
- private/bufpkg/bufmodule/bufmoduleapi/uploader.go
- private/bufpkg/bufprotoplugin/generator.go
- private/bufpkg/bufprotosource/files.go
- private/bufpkg/bufremoteplugin/bufremotepluginref/bufremotepluginref_test.go
- private/pkg/bandeps/checker.go
- private/pkg/oauth2/client_test.go
- private/pkg/storage/copy.go
- private/pkg/storage/storagetesting/storagetesting.go
This removes the lint warnings. Buf changed DEFAULT to STANDARD. Golangci-lint remove deprecated exportloopref for copyloopvar in Go v1.22+. Fixed up lint issues.
> Chore remove lint warnings

- CHANGELOG.md
- private/buf/cmd/buf/command/plugin/pluginpush/pluginpush.go
This fixes the command `buf plugin push` flag `--label` to allow specifying additional labels.
> Fix labels with buf plugin push

- CHANGELOG.md
- private/buf/cmd/buf/command/plugin/pluginpush/pluginpush.go
This fixes the command `buf plugin push` flag `--source-control-url` to allow setting parameter.
> Fix source-control-url with buf plugin push

- private/buf/buflsp/server.go
This will fix bufbuild/buf#3581
Before:
After:
> Fix nil pointer dereference in workspace capabilities check

- private/buf/cmd/buf/command/push/push.go
This comment is out of sync with the implementation.
Do we also need to check short flag names separately (like `-t`) or is that already handled?
> Fix outdated comment

- go.mod
- private/buf/bufwkt/cmd/wkt-go-data/main.go
- private/bufpkg/bufimage/bufimagemodify/internal/field_options_trie.go
The experimental functions in `golang.org/x/exp` are now available in the standard library in Go 1.21.
Reference: https://go.dev/doc/go1.21#slices
Reference: https://go.dev/doc/go1.21#cmp
> Replace `golang.org/x/exp` with stdlib

- .github/workflows/buf-binary-size.yaml
- .github/workflows/ci.yaml
- .github/workflows/previous.yaml
- .github/workflows/windows.yaml
This changes CI tests to trigger on [pull requests events](https://github.com/bufbuild/buf/pull/new/ed/ciOnPREvents), or when pushed to main. This has the following benefits:
- tests are run on the merged state of the target branch so can capture conflicting changes earlier
- forks from third party contributors will now have tests run as part of the PR workflow
- on merge, changes will still be tested on main
> CI trigger test runs on pull requests events

- private/bufpkg/bufcobra/markdown.go
The new docs site uses `console` instead of `terminal` to be compatible with Pygments.
> Change code example type

- private/buf/cmd/buf/command/registry/registrylogin/registrylogin.go
- private/buf/cmd/buf/command/registry/registrylogout/registrylogout.go
Update `buf registry logout` to document the domain optional argument, which if specified will log out of a specific BSR instance.
> Document registry logout argument

- private/pkg/app/appext/appext.go
In #3376 we switched `ReadConfig` from `UnmarshalYAMLStrict` to `UnmarshalYAMLNonStrict`. This was to enable a use case in an internal application. This PR switches `ReadConfig` back to `UnmarshalYAMLStrict` and adds `ReadConfigNonStrict` to enable the non-strict use case. The internal application will document why it needs the non-strict property.
I verified that nothing in the CLI needs non-strict parsing, everything is using the CLI's `NameContainer` and reads `bufapp.Config`.
> Parse app config strictly by default

- Dockerfile.buf
- go.mod
- go.sum
Upgrade our deps, excluding `protovalidate-go` and
`bufplugin` (which depends on the new version of `protovalidate-go`).
> Upgrade deps

- private/bufpkg/bufmodule/bufmoduleapi/module_data_provider.go
This is a small optimization to remove uneeded work when sorting module dependencies. No change in behavior.
> Cleanup TopoSort on module data deps

- private/pkg/oauth2/client.go
- private/pkg/oauth2/client_test.go
This adds validation to ensure that the URL scheme
returned from the oauth handler is only `http`/`https`.
> Add validation for verification URI in registry login

- private/bufpkg/bufmodule/added_module.go
- private/bufpkg/bufmodule/bufmoduleapi/module_data_provider.go
- private/bufpkg/bufmodule/bufmodulestore/module_data_store.go
- private/bufpkg/bufmodule/bufmoduletesting/bufmoduletesting.go
- private/bufpkg/bufmodule/module.go
- private/bufpkg/bufmodule/module_data.go
- private/bufpkg/bufmodule/module_set_builder.go
This fixes the b5 digest calculation for remote Modules when a transitive dependency is no longer a dependency in the parents ModuleSet. The digest calculation on Module.Digest would filter dependencies causing a ModuleData to fail tamper-proofing, as it would not filter it's dependencies. The documentation has been reworded to highlight the error case.
The ModuleData's method `DeclaredDepModuleKeys` has been renamed to `DepModuleKeys`. This clarifies the difference between declared dependencies, those in the `buf.yaml`, and the full dependency list, those in the `buf.lock`. The digest calculation must use the full list of dependencies, not the declared.
This is similar to the fix proposed in #3190 but does not cache the digest calculation in ModuleData for reuse in the Modules digest …
> Fix b5 module digest calculation with transitive dependencies

- private/buf/buffetch/ref_parser_unix_test.go
- private/buf/bufprotopluginexec/util_darwin.go
- private/buf/bufprotopluginexec/util_undarwin.go
- private/buf/cmd/buf/buf_unix_test.go
- private/buf/cmd/buf/command/alpha/protoc/const_unix.go
- private/buf/cmd/buf/command/alpha/protoc/const_windows.go
- private/buf/cmd/buf/command/alpha/protoc/flags_unix.go
- private/buf/cmd/buf/command/alpha/protoc/flags_windows.go
- private/buf/cmd/buf/command/generate/generate_unix_test.go
- private/buf/cmd/buf/command/generate/generate_windows_test.go
- private/buf/cmd/buf/command/registry/registrylogin/client.go
- private/buf/cmd/buf/command/registry/registrylogin/client_darwin.go
- private/buf/cmd/buf/workspace_unix_test.go
- private/buf/cmd/buf/workspace_windows_test.go
- private/bufpkg/bufimage/bufimagefuzz/bufimagefuzz_unix_test.go
- private/bufpkg/bufimage/build_image_unix_test.go
- private/pkg/app/app_unix.go
- private/pkg/app/app_windows.go
- private/pkg/app/appext/name_container_unix_test.go
- private/pkg/filepathext/filepathext_unix_test.go
- private/pkg/netrc/netrc_unix.go
- private/pkg/netrc/netrc_unix_test.go
- private/pkg/netrc/netrc_windows.go
- private/pkg/normalpath/normalpath_unix.go
- private/pkg/normalpath/normalpath_unix_test.go
- private/pkg/normalpath/normalpath_windows.go
- private/pkg/normalpath/normalpath_windows_test.go
- private/pkg/prototesting/prototesting_unix.go
- private/pkg/prototesting/prototesting_windows.go
The old format build lines are obsolete since Go 1.18 and are removed by running `go fix ./...`.
> Run go fix to remove obsolete build lines

- .github/workflows/buf-binary-size.yaml
- .github/workflows/ci.yaml
- .github/workflows/previous.yaml
- .github/workflows/windows.yaml
The CI workflow is the important one but it doesn't hurt to run the other workflows as well on tags.
> Ensure workflows continue to run on tags

- Dockerfile.buf
Fixes the following Docker warning:
- https://docs.docker.com/go/dockerfile/rule/from-as-casing/
> Fix warning from Docker build

- Dockerfile.buf
Fixes the redundant target platform warning:
- https://docs.docker.com/reference/build-checks/redundant-target-platform/
> Fix Docker warning

- .github/workflows/ci.yaml
The first tag appears to be used as the
`org.opencontainers.image.version`, so re-order the tags so the full version comes first for release builds.
> Re-order docker tags to correct image version

- CHANGELOG.md
- private/buf/cmd/buf/command/generate/generate.go
This fixes the flag `--include-types` for `buf generate`. This is a deprecated flag, replaced by `--type`. Currently this flag won't be applied. The behavior now allows for mixing of flag types, for example the following includes all 3 types:
```bash
buf generate --type=pkg.Foo --include-types=pkg.Bar --type=pkg.Baz
```
> Fix deprecated include types flag for buf generate

- private/pkg/git/cloner.go
When using `filter` `buf` will fail to run `git checkout` as the credentials aren't passed to `git`.
This results in failures such as:
```
Failure: could not clone https://github.com/foo/bar.git: exit status 128
fatal: could not read Username for 'https://github.com': No such device or address
fatal: could not fetch <SHA> from promisor remote
```
I noticed this while testing bufbuild/buf-action#142 which relies on overriding `credential.helper` for authentication in GitHub Actions.
> Include `gitConfigAuthArgs` on `git checkout` when `filter` is set

- CHANGELOG.md
- private/buf/bufctl/controller.go
- private/buf/bufctl/image_with_config.go
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/breaking/breaking.go
This PR adds a `--against-registry` flag to `buf breaking` that can be
set in lieu of `--against`. When `--against-registry` is set, breaking checks
are run against the latest commit on the default label of the remote module
in the registry.
`buf breaking` will error if one of `--against` or `--against-registry` is
not set:
```
$ buf breaking
Failure: Must set --against or --against-registry
```
`buf breaking --against-registry` will error if not all modules in the input
are named (and thus a remote cannot be resolved):
```
$ buf breaking --against-registry
Failure: cannot use --against-registry with unnamed module, proto/local
```
Fixes #3654
> Add `--against-registry` flag for `buf breaking`

- private/buf/buflsp/file.go
This changes the severity of the lint and breaking changes to `DiagnosticSeverityWarning`.
Checked a couple of reference implementations (e.g. gopls, rust-analyzer), surfacing lint/breaking
file annotations as "warning" level diagnostics is reasonable. We may want to make this configurable
in the future.
Fixes #3701, this would allow format to run with lint/breaking results.
We still want to continue blocking formatting with an invalid AST.
> Report lint/breaking check results as `DiagnosticSeverityWarning` in LSP

- go.mod
- private/buf/buflsp/file.go
Ensure go.lsp.dev/uri is used for path handling to correctly handle paths cross-platform e.g. windows.
Closes #3699.
> Fix path handling on windows

- private/buf/buflsp/file.go
This ensures checks diagnostics are always published to the LSP client. We adopt a worker model that runs checks in the background. On updates, the caller invalidates the previous checks. Checks are then re-evaluated and published. This ensures checks are eventually consistent.
Thanks to https://github.com/bufbuild/buf/pull/3706 for finding the issue for missing check diagnostics. This fixes that issue and solves the error case where the checks are never run due to try locking.
> LSP ensure check diagnostics are always published

- CHANGELOG.md
- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/bufimageutil/testdata/unuseddeps/a.proto
- private/bufpkg/bufimage/bufimageutil/testdata/unuseddeps/a.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/unuseddeps/ab.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/unuseddeps/b.proto
- private/bufpkg/bufimage/bufimageutil/testdata/unuseddeps/c.proto
This fixes unused dependencies when a type filter is applied for `buf generate`. The unused deps are validated when unmarshalling an image [here](https://github.com/bufbuild/buf/blob/37b5a2a496a2279aa03507be64cba00193644a1e/private/bufpkg/bufimage/validate.go#L44-L46). For a filtered image there are no unused deps as all unused are pruned. Test have been updated to capture the validation.
The fix has also been applied in #3624 .
> Fix unused dependencies on type filters for buf generate

- private/buf/cmd/buf/command/generate/generate.go
Fixes formatting by removing tabs in generate docs.
> Fix format of generate docs

- CHANGELOG.md
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/bufimageutil/image_filter.go
- private/bufpkg/bufimage/bufimageutil/testdata/options/pkg.Pkg.exclude.txtar
This fixes `exclude_type` for an excluded package which is also a target for the image. All target files are only implicitly included if no include `type`s are set. If the package is excluded and also a target for the image, this is no longer an error. If the package is excluded but also explicitly included, this is still an error.
> Fix exclude_type on non imported package

- CHANGELOG.md
- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/bufimageutil/testdata/deps/a.proto
- private/bufpkg/bufimage/bufimageutil/testdata/deps/b.proto
- private/bufpkg/bufimage/bufimageutil/testdata/deps/c.proto
- private/bufpkg/bufimage/bufimageutil/testdata/deps/test.EnumA.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/deps/test.FieldA.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/deps/test.proto
This fixes type filter import filtering for options. The parent file was incorrectly referred as the importer leading to unused imports for the file. This could be inconsistent depending on the order the types were resolved.
Fixes https://github.com/bufbuild/buf/issues/3725
> Fix type filter import filtering for options

- private/bufpkg/bufconfig/buf_yaml_file.go
This removes unused logic for the serialization of plugins in buf.yaml files. The map `stringToExternalPlugins` was never written to.
> Cleanup buf.yaml plugin config serialization

- CHANGELOG.md
- private/pkg/pluginrpcutil/pluginrpcutil.go
- private/pkg/pluginrpcutil/runner.go
This adds the os environment to locally run plugins. Local plugins inherit the environment from buf. 
As a use case, plugins can now be managed with `go tool`. For instance [buf-plugin-aep](https://github.com/aep-dev/api-linter/tree/main/cmd/buf-plugin-aep) in `buf.yaml`:
```yaml
version: v2
lint:
use:
- AEP_CORE
plugins:
- plugin: ["go", "tool", "buf-plugin-aep"]
```
> Add os environment for local plugins

- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/bufimageutil/image_filter.go
- private/bufpkg/bufimage/bufimageutil/testdata/deps/old.proto
- private/bufpkg/bufimage/bufimageutil/testdata/deps/test.PublicOrder.txtar
- private/bufpkg/bufimage/bufimageutil/testdata/deps/test.proto
This ensures that public imports are always added to the image in a deterministic way. It changes the current order by first seen to order by file name. First seen is not valid as when including options we range over them in an [undefined order](https://pkg.go.dev/google.golang.org/protobuf@v1.36.6/reflect/protoreflect#Message) (although from testing it looks to always be in tag order).
Related to https://github.com/bufbuild/buf/issues/3506  and https://github.com/bufbuild/buf/issues/3725 . Both these issues link to the same error of adding unused imports. This was fixed in https://github.com/bufbuild/buf/pull/3727 . This PR fixes an edge case where if 2 or more public imports are resolved for a file, they must be appended to the current imports in a deterministic way.
> Ensure deterministic order for filtered public imports

- CHANGELOG.md
- private/buf/cmd/buf/buf_test.go
- private/bufpkg/bufcheck/bufcheckserver/internal/bufcheckserverhandle/breaking.go
- private/bufpkg/bufcheck/bufcheckserver/internal/bufcheckserverhandle/lint.go
- private/bufpkg/bufcheck/bufcheckserver/internal/bufcheckserverhandle/tag_ranges.go
- private/bufpkg/bufcheck/bufcheckserver/internal/bufcheckserverutil/response_writer.go
This PR adds a back-up file path to `responseWriter.AddProtosourceAnnotation`,
so that in cases where `bufprotosource.Location` is `nil` (e.g. when the input does
not provide source code info), annotations will fallback and use the file path.
Currently, when no source code info is available, we get the following output:
```
<input>:1:1:RPC "Echo" has the same type "foo.v1.Message" for the request and response.
<input>:1:1:RPC request type "Message" should be named "EchoRequest" or "EchoServiceEchoRequest".
<input>:1:1:RPC response type "Message" should be named "EchoResponse" or "EchoServiceEchoResponse".
```
With this change, we will get:
```
foo/v1/foo.proto:1:1:RPC "Echo" has the same type "foo.v1.Message" for the request and response.
foo/v1/foo.proto:1:1:RPC request type "Message" …
```
> Add file path to file annotations without source code info

- private/gen/proto/go/buf/alpha/audit/v1alpha1/event.pb.go
- proto/buf/alpha/audit/v1alpha1/event.proto
Add some events that the `plugins` don’t have but `repositories` do, for consistency:
- plugin deprecated
- plugin undeprecated
- plugin visibility changed
Add missing field `visibility` for `plugins` events to match the ones we’re already logging for `repositories` events.
Add the same events, with the same fields, for `policies`.
> Add `Policy` audit events, and missing `Plugin` events and fields

- private/bufpkg/bufimage/bufimageutil/bufimageutil.go
- private/bufpkg/bufimage/bufimageutil/bufimageutil_test.go
- private/bufpkg/bufimage/bufimageutil/image_filter.go
- private/bufpkg/bufimage/bufimageutil/testdata/deps/test.IncludeWithExcludeExt.txtar
This fixes `exclude_type` for an included extension which is implicitly excluded due to all fields being excluded.
Closes https://github.com/bufbuild/buf/issues/3738
> Fix excluded_type imports for implicitly excluded extensions

- .pre-commit-hooks.yaml
- CHANGELOG.md
We currently require `go 1.23.4` (based on our dependency on
`protovalidate-go`), so pre-commit hooks need to be updated to
fetch a compliant version of Go.
Fixes #3750
> Update pre-commit hooks language version

- private/gen/proto/go/buf/alpha/audit/v1alpha1/event.pb.go
- private/gen/proto/go/buf/alpha/registry/v1alpha1/organization.pb.go
- proto/buf/alpha/audit/v1alpha1/event.proto
- proto/buf/alpha/registry/v1alpha1/organization.proto
This allows admins to associate a role override with the group, which will grant the specific role upon mapping instead of the 'member' role.
> Add `role_override` to `AddOrganizationGroupRequest`

- private/pkg/git/cloner.go
In the case where `buf` is being run in an environment where `GIT_DIR`
is set, e.g. within a submodule, `git init` will defer to using the `GIT_DIR`
rather than creating its own. We want to avoid mutating an existing `GIT_DIR`
through `CloneToBucket`, and should instead be treating it as a stand-alone
clone, so we filter out `GIT_DIR` from the environment variables.
An example of this came up in #3752 where a submodule is running `buf` in
repository-local pre-commit hooks.
Fixes #3752
> Filter out `GIT_DIR` from cloner environment variables

- private/bufpkg/bufcheck/bufcheckserver/internal/bufcheckserverhandle/breaking.go
This fixes a typo on the breaking annotation.  Looked at all other method calls, seems like the only out of order one.
> Fix AddProtosourceAnnotation file name for breaking

- private/buf/bufcli/cache.go
- private/buf/cmd/buf/command/beta/lsp/lsp.go
- private/buf/cmd/buf/command/breaking/breaking.go
- private/buf/cmd/buf/command/config/internal/internal.go
- private/buf/cmd/buf/command/lint/lint.go
This is a cleanup to bind the cache directory creation to the creation of the wasm runtime.
> Cleanup Wasm runtime creation

- make/go/dep_golangci_lint.mk
- make/go/go.mk
This integrates the new `golangci-lint fmt` command into the appropriate places to ensure code is formatted consistenty going forward. This used to be caught by the linter but after the migration to golangci-lint v2 we were missing this.
> Update to latest makego

- private/gen/proto/connect/buf/alpha/registry/v1alpha1/registryv1alpha1connect/repository.connect.go
- private/gen/proto/go/buf/alpha/audit/v1alpha1/event.pb.go
- private/gen/proto/go/buf/alpha/registry/v1alpha1/repository.pb.go
- private/gen/proto/go/buf/alpha/registry/v1alpha1/role.pb.go
- proto/buf/alpha/audit/v1alpha1/event.proto
- proto/buf/alpha/registry/v1alpha1/repository.proto
- proto/buf/alpha/registry/v1alpha1/role.proto
This PR adds the following RPCs and their associated audit logs:
- AddRepositoryGroup
- UpdateRepositoryGroup
- RemoveRepositoryGroup
For now, these RPCs live in v1alpha1 until we have stabilized the schema for roles/permissions generally.
I did not yet add an RPC to expose the set of groups currently configured as that is pending what we need for the UI.
> Repository IdP group mapping

- private/gen/proto/connect/buf/alpha/registry/v1alpha1/registryv1alpha1connect/resolve.connect.go
- private/gen/proto/go/buf/alpha/registry/v1alpha1/resolve.pb.go
- proto/buf/alpha/registry/v1alpha1/resolve.proto
This adds a `GetSDKInfo` rpc to the `ResolveService`.
This RPC will provide the SDK information based on the provided
module reference, plugin information, and optionally SDK version string.
If a specific module reference (commit or label) is and/or a plugin version
is specified, then the SDK for the specified information is resolved. If the
SDK version string is provided, then it will be validated with the module and
plugin information.
This allows us to replace the use of the subsequent RPCs in `buf registry sdk version`,
and make a single call to `GetSDKInfo` to resolve the SDK version information.
It also allows us to easily provide module commit and plugin version
information given the module, plugin, and SDK version string.
> Add `GetSDKInfo` rpc to `ResolveService`

- private/bufpkg/bufcheck/breaking_test.go
- private/bufpkg/bufcheck/testdata/breaking/current/breaking_field_same_cardinality/1.proto
- private/bufpkg/bufcheck/testdata/breaking/previous/breaking_field_same_cardinality/1.proto
This is a small PR to expand the testcase for proto3 optional behaviour on message cardinality. `optional` does not affect messages and there is no change in behaviour. The new testcases confirm this.
> Expand testcase for FIELD_CARDINALITY_SAME with optionals

- private/gen/proto/go/buf/alpha/audit/v1alpha1/event.pb.go
- proto/buf/alpha/audit/v1alpha1/event.proto
It includes the `[#next-free-field: x]` annotation for large audit events that keep growing as we audit more events. Seems to be a standard annotation: https://github.com/search?q=content%3Anext-free-field+language%3Aproto&type=code
> Add policy pushed event

- CHANGELOG.md
- make/buf/scripts/release.bash
This PR adds binary releases for riscv64 linux platform.
I find running `make bufrelease` a little slow. So as a bonus, I made the build parallel in a separate commit(Though it doesn't bring much benefits for GitHub CI because it only offers poor runners with merely 4 cores).
> Release binaries for riscv64 linux platform

- private/pkg/app/appext/builder.go
To my knowledge, this hasn't been used since circa 2020. This removes a dependency on the `thread` package.
> Remove hidden parallelism flag from app

- CHANGELOG.md
- private/bufpkg/bufcheck/bufcheckserver/internal/buflintvalidate/predefined_rules.go
- private/bufpkg/bufcheck/testdata/lint/protovalidate_predefined/import/import.proto
- private/bufpkg/bufcheck/testdata/lint/protovalidate_predefined/proto/rules.proto
- private/bufpkg/bufcheck/testdata/lint/protovalidate_predefined/proto/test.proto
This adds the variable `rules` to the CEL environment for the predefined protovalidate rules.
Fixes #3824.
> Fix protovalidate predefined CEL rules variable

- private/bufpkg/bufcheck/client.go
This PR fixes the error message for image failures on checks, `lint` and `breaking`. A image that does not include all the required dependencies cannot be used for evaluating checks. We now report a non syserror failure.
Closes #3808
> Fix check failure message on partial images

- CHANGELOG.md
- private/buf/bufprint/bufprint.go
- private/buf/bufprint/sdk_info_printer.go
- private/buf/cmd/buf/buf.go
- private/buf/cmd/buf/command/registry/sdk/sdkinfo/sdkinfo.go
- private/buf/cmd/buf/command/registry/sdk/sdkinfo/usage.gen.go
This PR implements a new command, `buf registry sdk info`. This command is
used for resolving SDK information. It always requires the user to provide the module
and plugin information.
This commands expands on `buf registry sdk version`, allowing the user to resolve
the SDK information based on the version string for the module and plugin. For example,
the user knows the SDK version string, they could provide the following to resolve the module
commit and plugin information for the SDK given version string:
```
$ buf registry sdk --module=buf.build/connectrpc/eliza --plugin=buf.build/bufbuild/es --version=1.2.1-20230727062025-d8fbf2620c60.1
Module
Owner:  connectrpc
Name:   eliza
Commit: d8fbf2620c604277a0ece1ff3a26f2ff
Plugin
Owner:    bufbuild
Name:     es
Version:  v1.2.1
Revision: 1 …
```
> Implement `buf registry sdk info` command

- .pre-commit-hooks.yaml
Updates the pre-commit hooks language version requirements
to match `go.mod`.
Fixes #3880
Follow-ups will be done to update our dep upgrade process
to include checking the pre-commit hooks language versions,
and running them as a part of CI checks.
> Upgrade pre-commit Go versions

- CHANGELOG.md
- private/buf/cmd/buf/buf_test.go
- private/buf/cmd/buf/command/export/export.go
- private/buf/cmd/buf/testdata/workspace/success/v2/export/another/proto/another.proto
- private/buf/cmd/buf/testdata/workspace/success/v2/export/buf.yaml
- private/buf/cmd/buf/testdata/workspace/success/v2/export/other/proto/request.proto
- private/buf/cmd/buf/testdata/workspace/success/v2/export/other/proto/unimported.proto
- private/buf/cmd/buf/testdata/workspace/success/v2/export/proto/rpc.proto
Add `buf export --all` flag for exporting non-proto sources,
such as documentation and license files with `buf export`.
Fixes #3870
> Add `--all` flag for `buf export`

- make/buf/all.mk
- make/buf/scripts/checkandupdateprecommithooks.bash
- make/buf/scripts/checkprecommithooks.bash
This PR adds a script to check that pre-commit hooks are up-to-date
with `go.mod` versions and if not, update them, as a part of `make upgrade`.
Fixes #3882
> Ensure pre-commit hooks are kept up-to-date

- private/gen/proto/go/buf/alpha/audit/v1alpha1/event.pb.go
- proto/buf/alpha/audit/v1alpha1/event.proto
This renames the audit Digest type to correctly reflect the policy type of o1.
> Rename audit event Digest type for policy commits

- CHANGELOG.md
- make/buf/scripts/release.bash
- make/go/dep_protoc.mk
Add s390x binaries for Linux to releases.
@doriable and @Jenkins-J I also fixed the ppc64le binaries which are being released as x86_64 binaries since I needed to change the same code. In a previous PR #3840 the bash function `goarch()` wasn't updated with the `ppc64le` value so the default `x86_64` ended up being used. 
Note that the `goarch()` function returns 1 if the arch wasn't found but since `goarch()` is only executed in a subshell, it doesn't fail and exit the script which I think was the intent. So I also made the `goarch()` and `goos()` functions return the string `"unsupported"` if the arch or os is not found so that the script will fail and exit. I'm happy to provide more details if you have more questions on this. It took me a while to figure out exactly what was going on.
> Add s390x binaries for Linux to releases and fix ppc64le release binaries

- private/bufpkg/bufplugin/plugin.go
This fixes the use of Plugin.Digest() method for calculating the plugin digest. Corrects the use of the bufcas digest to read from the plugin contents. Any current callers are expected to have failed using this method so no invalid digests should be seen.
> Fix bufplugin Plugin.Digest caclulation

- README.md
This adds the new `s390x` binary (introduced in #3900) to the README
for the next release.
> Add `s390x` build to README

- private/gen/proto/go/buf/alpha/audit/v1alpha1/event.pb.go
- proto/buf/alpha/audit/v1alpha1/event.proto
This adds audit log events for policy enforcements. The resource type is either server, owner (user/organization) or module. This aligns with current policy event types like `EVENT_TYPE_SERVER_UNIQUENESS_POLICY_ENABLED` that apply to the server resource.
> Add audit log for policy enforcements

- private/buf/cmd/buf/command/beta/registry/plugin/pluginpush/pluginpush.go
This fixes a panic on the edge case that the same plugin is uploaded multiple times at once. Also validation is added to ensure the image container digest match as this is not guaranteed by the error code alone (it could be from a conflict of revision number).
> Fix curated plugin latest fetching

- CHANGELOG.md
- private/buf/cmd/buf/command/curl/curl.go
This fixes buf curl commands with HTTP/2 services. Introduced in https://github.com/bufbuild/buf/pull/4011
> Fix buf curl with HTTP/2 services
